// quizdata_300_vragen_jongvolwassenen.js - 300 Vragen voor 18-40 jarigen (Algemeen, Sport, Vlaanderen & Eten)

var STANDAARD_R1_POOL = [
    // --- Algemene Kennis & Technologie (75 Vragen) ---
    { q: "Wat is de naam van de technologie achter Bitcoin en andere crypto?", a: "Blockchain" },
    { q: "Wat is de naam van de populaire app voor het delen van korte video's?", a: "TikTok" },
    { q: "Wie schilderde het beroemde werk 'De Sterrennacht'?", a: "Vincent van Gogh" },
    { q: "Wat is de chemische formule voor tafelzout?", a: "NaCl" },
    { q: "Wat is de naam van de bergketen die door de westkust van Zuid-Amerika loopt?", a: "Andes" },
    { q: "Wat is de valuta van Japan?", a: "Yen" },
    { q: "In welk jaar viel de Berlijnse Muur?", a: "1989" },
    { q: "Wat is de eenheid van elektrische weerstand?", a: "Ohm" },
    { q: "Welk land staat bekend om de uitvinding van de robotstofzuiger 'Roomba'?", a: "Verenigde Staten" },
    { q: "Wat is de naam van de wetenschapper die de relativiteitstheorie ontwikkelde?", a: "Albert Einstein" },
    { q: "Welke stad is de thuisbasis van de filmstudio Hollywood?", a: "Los Angeles" },
    { q: "Wat is de naam van het beroemde meer in Schotland waar een monster zou leven?", a: "Loch Ness" },
    { q: "Wie was de eerste vrouw die een Nobelprijs won?", a: "Marie Curie" },
    { q: "Wat is de naam van het social media platform dat vroeger Twitter heette?", a: "X (of Twitter)" },
    { q: "Wat is de naam van de grootste regenwoud ter wereld?", a: "Amazone" },
    { q: "Welke filmfranchise bevat de personages Tony Stark en Captain America?", a: "Marvel Cinematic Universe (MCU)" },
    { q: "Wat is de eenheid van kracht in het SI-stelsel?", a: "Newton" },
    { q: "Wat is de naam van de theorie die de oorsprong van het universum verklaart?", a: "Big Bang Theorie" },
    { q: "Hoeveel nullen heeft een miljoen?", a: "Zes" },
    { q: "Welke coureur won de meeste Formule 1-wereldtitels (samen met Schumacher)?", a: "Lewis Hamilton" },
    { q: "Wat is de valuta van India?", a: "Roepie" },
    { q: "Wat is de naam van de grote kloof in de VS?", a: "Grand Canyon" },
    { q: "Hoeveel spelers heeft een voetbalteam op het veld?", a: "11" },
    { q: "Welke filmstudio maakte de animatiefilms 'Toy Story' en 'Finding Nemo'?", a: "Pixar" },
    { q: "Welke stad organiseerde de Olympische Zomerspelen in 2016?", a: "Rio de Janeiro" },
    { q: "Wie is de auteur van de 'The Hunger Games' boekenreeks?", a: "Suzanne Collins" },
    { q: "Wat is de naam van de grootste maan van Jupiter?", a: "Ganymedes" },
    { q: "Wat is de naam van de populaire app voor het delen van je locatie met vrienden?", a: "Snapchat (of Life360/Find My)" },
    { q: "Wat is de naam van de wet die de relatie tussen stroom, spanning en weerstand beschrijft?", a: "Wet van Ohm" },
    { q: "Welke acteur speelt Ken in de Barbie-film uit 2023?", a: "Ryan Gosling" },
    { q: "Wat is de naam van de robot in Star Wars die 'Piep' geluiden maakt en rondrijdt?", a: "R2-D2" },
    { q: "Welke popzangeres had een hit met 'Drivers License'?", a: "Olivia Rodrigo" },
    { q: "Wat is de naam van de grootste waterval ter wereld (hoogte)?", a: "Angel Falls" },
    { q: "Wat is de naam van de president van Rusland?", a: "Vladimir Poetin" },
    { q: "Wat is de naam van het beroemde paleis in Parijs dat een museum is?", a: "Louvre" },
    { q: "Wat is de naam van het grootste wielerevenement ter wereld?", a: "Tour de France" },
    { q: "Wat is de naam van de ruimtetelescoop die in 2021 werd gelanceerd?", a: "James Webb" },
    { q: "Wat is de naam van de Britse spion met codenaam 007?", a: "James Bond" },
    { q: "Wat is de naam van het album van Taylor Swift dat in 2020 werd uitgebracht en zeer populair was?", a: "Folklore" },
    { q: "Wat is de naam van de magische school uit 'Harry Potter'?", a: "Zweinstein" },
    { q: "Welke popartiest staat bekend om het nummer 'Shape of You'?", a: "Ed Sheeran" },
    { q: "Welke stad is de thuisbasis van het Colosseum?", a: "Rome" },
    { q: "Welke band bracht het album 'The Dark Side of the Moon' uit?", a: "Pink Floyd" },
    { q: "Wat is de valuta van het Verenigd Koninkrijk?", a: "Pond Sterling" },
    { q: "Welke gamefranchise staat bekend om het 'First-Person Shooter' genre met jaarlijkse releases?", a: "Call of Duty" },
    { q: "Wat is de naam van de beroemde scheve toren in Italië?", a: "Toren van Pisa" },
    { q: "Wie was de eerste vrouwelijke premier van het Verenigd Koninkrijk?", a: "Margaret Thatcher" },
    { q: "Welke regisseur maakte films als 'Pulp Fiction' en 'Kill Bill'?", a: "Quentin Tarantino" },
    { q: "Wat is de naam van de planeet met de ringen?", a: "Saturnus" },
    { q: "Welke rapper staat bekend om zijn album 'DAMN.'?", a: "Kendrick Lamar" },
    { q: "Welke film won in 2019 de meeste Oscars, waaronder Beste Film?", a: "Green Book" },
    { q: "Wat is de naam van de grootste woestijn ter wereld?", a: "Sahara" },
    { q: "Wat is de naam van de centrale verwerkingseenheid in een computer?", a: "CPU (Central Processing Unit)" },
    { q: "Wie zingt het nummer 'Blinding Lights'?", a: "The Weeknd" },
    { q: "Wat is de naam van de populaire battle royale game van Epic Games?", a: "Fortnite" },
    { q: "Welke zangeres heeft hits zoals 'Bad Guy' en 'Ocean Eyes'?", a: "Billie Eilish" },
    { q: "Wie speelde Hermione Granger in de Harry Potter-films?", a: "Emma Watson" },
    { q: "Wat is de naam van de hoogste berg ter wereld?", a: "Mount Everest" },
    { q: "Wat is de naam van de bergketen die door de westkust van Zuid-Amerika loopt?", a: "Andes" },
    { q: "Wie schreef '1984'?", a: "George Orwell" },
    { q: "Wat is de naam van de meest verkochte game aller tijden (in één versie)?", a: "Minecraft" },
    { q: "Welke gamebedrijf ontwikkelde 'The Legend of Zelda' en 'Mario'?", a: "Nintendo" },
    { q: "Welke actrice speelt Wednesday Addams in de gelijknamige Netflix-serie?", a: "Jenna Ortega" },
    { q: "Wie is de zangeres van het nummer 'Hello'?", a: "Adele" },
    { q: "Welke streamingdienst is bekend van series als 'Stranger Things' en 'The Crown'?", a: "Netflix" },
    { q: "Wat is de naam van de ring die in 'Lord of the Rings' gezocht wordt?", a: "De Ene Ring" },
    { q: "Welk genre vertegenwoordigt artiest als Tiësto en Martin Garrix?", a: "EDM (Electronic Dance Music)" },
    { q: "Wat is de naam van de fictieve drug in de serie 'Breaking Bad'?", a: "Crystal Meth (Blue Sky)" },
    { q: "Welke streamingdienst is eigendom van Amazon?", a: "Prime Video" },
    { q: "Wie speelde de hoofdrol in 'Titanic'?", a: "Leonardo DiCaprio" },
    { q: "In welke fictieve stad speelt de Batman zich af?", a: "Gotham City" },
    { q: "Welke artiest had een hit met 'As It Was' in 2022?", a: "Harry Styles" },
    { q: "Wie is de regisseur van de film 'Inception' en 'Oppenheimer'?", a: "Christopher Nolan" },
    { q: "Welke planeet staat bekend als de 'Rode Planeet'?", a: "Mars" },
    { q: "Wat is de naam van de laag in de atmosfeer die ons beschermt tegen UV-straling?", a: "Ozonlaag" },
    { q: "Wat is de naam van de supercontinent dat 200 miljoen jaar geleden bestond?", a: "Pangea" },
    { q: "Wat is het grootste interne orgaan van het menselijk lichaam?", a: "Lever" },
    
    // --- Sport (75 Vragen) ---
    { q: "In welke sport scoort men een 'touchdown'?", a: "American Football" },
    { q: "Wat is de afstand van een marathon in kilometers?", a: "42,195 km" },
    { q: "Wat is de naam van de beroemdste tennistoernooi op gras?", a: "Wimbledon" },
    { q: "Hoeveel kegels (pins) moeten er worden omgegooid bij het bowlen?", a: "10" },
    { q: "Wat is de bijnaam van het Belgisch nationaal voetbalelftal?", a: "De Rode Duivels" },
    { q: "In welke sport gebruikt men een 'shuttlecock'?", a: "Badminton" },
    { q: "Wat is de term voor een doelpunt dat rechtstreeks uit een hoekschop wordt gescoord?", a: "Olympisch doelpunt" },
    { q: "Wat is de naam van het stadion van RSC Anderlecht?", a: "Lotto Park (of Constant Vanden Stockstadion)" },
    { q: "Hoe lang duurt een reguliere wedstrijd in het ijshockey (exclusief verlenging)?", a: "60 minuten" },
    { q: "Welke Belgische zwemmer won een gouden medaille op de Olympische Spelen van 2016?", a: "Pieter Timmers" },
    { q: "In welke stad werden de Olympische Zomerspelen van 2024 gehouden?", a: "Parijs" },
    { q: "Wat is de naam van de 'Koning van de Koppen' in het Belgisch voetbal?", a: "Jan Koller (of Christian Benteke, afhankelijk van generatie)" },
    { q: "Bij welke balsport is 'pitching' een belangrijke actie?", a: "Baseball" },
    { q: "Hoeveel sets moet een speler winnen om een grandslam-tennismatch te winnen (mannen)?", a: "Drie" },
    { q: "Wat is de naam van de Belgische renner die bekend stond als de 'Kannibaal'?", a: "Eddy Merckx" },
    { q: "Hoe wordt de sport 'gevecht op het zwaard' genoemd?", a: "Schermen" },
    { q: "In welk jaar werd de eerste editie van de Ronde van Vlaanderen gereden?", a: "1913" },
    { q: "Wat is de kleur van de trui die de leider van het bergklassement in de Tour de France draagt?", a: "Wit met rode stippen" },
    { q: "Wat is de scoreterm voor een slag van één onder par in golf?", a: "Birdie" },
    { q: "Welke stad organiseert jaarlijks de Formule 1 Grote Prijs van België?", a: "Spa-Francorchamps" },
    { q: "Wat is de naam van de Belgische volleybalploeg?", a: "Red Dragons (mannen) / Yellow Tigers (vrouwen)" },
    { q: "Hoeveel ringen heeft het Olympisch symbool?", a: "5" },
    { q: "Wat is een **'hattrick'** in het voetbal?", a: "Drie doelpunten in één wedstrijd (door één speler)" },
    { q: "Welke Belgische club won de Europa Cup II in 1976?", a: "RSC Anderlecht" },
    { q: "Wat is de naam van de beroemde racebaan in Spa-Francorchamps?", a: "Circuit de Spa-Francorchamps" },
    { q: "Wat is de naam van de Belgische basketbalspeler die in de NBA speelt (recent)?", a: "Frank Ntilikina (of Toumani Camara)" },
    { q: "Welke Belgische atleet won goud op de 400m horden op de Olympische Spelen van 2020?", a: "Bashir Abdi (of Nafi Thiam, maar zij won meerkamp)" },
    { q: "Wat is de naam van de Belgische club die de meeste landstitels heeft gewonnen?", a: "RSC Anderlecht" },
    { q: "Hoe wordt de sport met het zware gewicht aan een ketting genoemd?", a: "Kogelslingeren" },
    { q: "Hoe noemt men een perfecte score van 300 bij het bowlen?", a: "Perfect game" },
    { q: "Wat is de naam van de Belgische keeper die in 2023 verkozen werd tot beste keeper ter wereld?", a: "Thibaut Courtois" },
    { q: "Welke Belgische voetbalploeg wordt de 'Boeren' genoemd?", a: "KRC Genk (of Club Brugge)" },
    { q: "Wat is de naam van de sport waarbij men met een stok over een hindernis springt?", a: "Polsstokhoogspringen" },
    { q: "Wat is de naam van de Belgische olympische kampioene in het zeilen in 2016?", a: "Evi Van Acker" },
    { q: "In welke sport staat de term 'checkmate' centraal?", a: "Schaken" },
    { q: "Welke Belgische club speelt in het stadion 'Jan Breydel'?", a: "Club Brugge en Cercle Brugge" },
    { q: "Wat is de naam van de Belgische judoka die Olympisch goud won in 2000?", a: "Ulla Werbrouck (of Ingrid Berghmans - 1988)" },
    { q: "In welke sport wordt de term 'forehand' en 'backhand' gebruikt?", a: "Tennis" },
    { q: "Welk land organiseerde het WK Voetbal in 2010?", a: "Zuid-Afrika" },
    { q: "In welke sport kun je een 'strike' gooien?", a: "Bowling" },
    { q: "Wat is de naam van de beroemde basketbalcompetitie in de VS?", a: "NBA (National Basketball Association)" },
    { q: "Wie wordt vaak beschouwd als de beste voetballer aller tijden (samen met Pelé)?", a: "Lionel Messi (of Maradona)" },
    { q: "Wat is de naam van de Belgische wielerklassieker die ook 'Vlaanderens Mooiste' wordt genoemd?", a: "Ronde van Vlaanderen" },
    { q: "Welke kleur kaart krijgt een speler in voetbal voor een zware overtreding en moet hij het veld verlaten?", a: "Rood" },
    { q: "Wat is de naam van de sport die wordt gespeeld met een puck en sticks op ijs?", a: "IJshockey" },
    { q: "Hoeveel gaten telt een standaard golfbaan?", a: "18" },
    { q: "Wat is de naam van de beroemde Amerikaanse zwemmer met 23 Olympische gouden medailles?", a: "Michael Phelps" },
    { q: "Welke sport kent termen als 'halfpipe' en 'ollie'?", a: "Skateboarden (of Snowboarden)" },
    { q: "Welk land is de bakermat van de sport judo?", a: "Japan" },
    { q: "Wat is een 'triple-double' in basketbal?", a: "Tien of meer in drie statistische categorieën" },
    { q: "Welke club won de meeste keren de UEFA Champions League?", a: "Real Madrid" },
    { q: "Wat is de naam van de atleet die het wereldrecord polsstokhoogspringen bezit (per 2024)?", a: "Armand 'Mondo' Duplantis" },
    { q: "Wat is de naam van de sport waarbij je met een boog en pijlen op een doel schiet?", a: "Boogschieten" },
    { q: "Wat is de naam van de Belgische tennisspeelster die in 2011 de US Open won?", a: "Kim Clijsters" },
    { q: "Welke club won de Belgische beker in het seizoen 2022-2023?", a: "Royal Antwerp FC" },
    { q: "Hoeveel periodes worden er gespeeld in een basketbalwedstrijd (FIBA-regels)?", a: "Vier" },
    { q: "Wat is de naam van de Belgische meerkampster die Olympisch goud won in 2016 en 2020?", a: "Nafi Thiam" },
    { q: "In welke sport wordt de term 'grand slam' ook gebruikt (naast tennis)?", a: "Honkbal (Baseball)" },
    { q: "Welke wielerklassieker wordt ook wel 'De Hel van het Noorden' genoemd?", a: "Parijs-Roubaix" },
    { q: "Wat is de naam van de Belgische voetballegende die bekend staat als 'De Generaal'?", a: "Vincent Kompany (of Franky Van der Elst)" },
    { q: "Welk land is de bakermat van de sport tafeltennis?", a: "Engeland" },
    { q: "Wat is de naam van de Belgische hockeyploeg (mannen) die in 2018 wereldkampioen werd?", a: "Red Lions" },
    { q: "Hoeveel caramboles zijn er nodig voor een 'grote finale' in het carambolebiljart?", a: "Drie" },
    { q: "Welke sport maakt gebruik van een 'slalom'?", a: "Skiën (of Snowboarden)" },
    { q: "Welke club won de meeste Belgische bekers (Croky Cup)?", a: "Club Brugge" },
    { q: "Wat is de naam van de Belgische golfer die in 2018 het Ryder Cup-team haalde?", a: "Thomas Pieters" },
    { q: "Hoe noemt men de strafschop in het rugby?", a: "Penalty (of try)" },
    { q: "Wat is de naam van de Belgische wielrenner die in 2020 de wereldtitel op de weg won?", a: "Julian Alaphilippe (Fransman)" },
    { q: "Wat is de naam van de sport waarbij men met een 'curlende' steen over het ijs schuift?", a: "Curling" },
    { q: "Welk nummer droeg de beroemde Belgische basketballer Axel Hervelle?", a: "10 (of 11)" },
    
    // --- Vlaanderen, Cultuur, Films & Series (75 Vragen) ---
    { q: "Welke Vlaamse serie met **Matteo Simoni** en **Stef Aerts** draait rond de drugswereld?", a: "Patser (of Over Water)" },
    { q: "Wat is de titel van de film van **Felix Van Groeningen** die genomineerd was voor een Oscar?", a: "The Broken Circle Breakdown" },
    { q: "In welke populaire serie speelt **Koen De Bouw** de rol van Peter Van In?", a: "Aspe" },
    { q: "Wat is de naam van de komische serie die zich afspeelt in een rusthuis?", a: "Nonkels" },
    { q: "Welke Vlaamse serie volgt de belevenissen van een familie in de Tweede Wereldoorlog?", a: "Witse" },
    { q: "Wie speelde de hoofdrol in de film *Marina* over het leven van **Rocco Granata**?", a: "Matteo Simoni" },
    { q: "Welke film van **Erik Van Looy** draait rond vijf vrienden die een loft delen?", a: "De Zaak Alzheimer" },
    { q: "Wat is de titel van de serie waarin **Stany Crets** de hoofdrol speelt als privédetective?", a: "De Pfaffs (of De Kotmadam)" },
    { q: "Wie regisseerde de film *De Zaak Alzheimer*?", a: "Erik Van Looy" },
    { q: "Wat is de naam van de serie die zich afspeelt in een fictieve kuststad en draait rond een moordzaak?", a: "Beau Séjour" },
    { q: "Welke acteur speelde de rol van **Pietje** in *De Kotmadam*?", a: "Filip Peeters" },
    { q: "Wat is de titel van de Vlaamse oorlogsfilm over het **Fort van Breendonk**?", a: "Niet Schieten" },
    { q: "In welke serie speelde **An Swartenbroekx** de rol van Bieke Crucke?", a: "F.C. De Kampioenen" },
    { q: "Wie is de hoofdactrice in de serie *Thuis* die al sinds het begin meespeelt?", a: "Ann Pira (of Marleen Merckx)" },
    { q: "Wat is de titel van de film waarin **Jeroen Perceval** een ex-bokser speelt die zijn dochter probeert te beschermen?", a: "D'Ardennen" },
    { q: "Welke Vlaamse serie draait rond een busmaatschappij en haar werknemers?", a: "De Buurtpolitie" },
    { q: "Wat is de naam van de film uit 1999 die draait rond de moord op een jongetje in het Antwerpse Scheldeland?", a: "De Zaak Alzheimer" },
    { q: "Wat is de titel van de serie van **Bart De Pauw** over een groep vrienden die samen opgroeien?", a: "De Bende van Jan de Lichte" },
    { q: "Wat is de naam van de film van **Jan Verheyen** over de waargebeurde bankoverval in België?", a: "De Zaak Alzheimer" },
    { q: "In welke serie staat de brandweerkazerne van Post Oosteroever centraal?", a: "De Buurtpolitie" },
    { q: "Wat is de naam van de film van **Adil El Arbi** en **Bilall Fallah** die zich afspeelt in Brussel?", a: "Patser" },
    { q: "Welke acteur speelde de rol van de cafébaas in *F.C. De Kampioenen*?", a: "Jacques Vermeire" },
    { q: "Wat is de naam van de fictieve drug in de Vlaamse film 'Patser'?", a: "White T." },
    { q: "In welke Vlaamse serie staat een groep vrienden centraal die het kotleven ontdekken?", a: "Dertigers" },
    { q: "Wat is de naam van de Vlaamse film over een bankoverval waarbij de daders ontsnappen via de riolering?", a: "Rundskop" },
    { q: "Wie is de hoofdrolspeler in de Vlaamse serie 'Salamander'?", a: "Filip Peeters" },
    { q: "Wat is de naam van de populaire Vlaamse misdaadserie over een familie van motorcrossers?", a: "Eigen Kweek" },
    { q: "Welke Vlaamse komedie/drama film uit 2018 won de publieksprijs op Film Fest Gent?", a: "Niet Schieten" },
    { q: "Wie is de regisseur van de Vlaamse film 'De Zaak Alzheimer'?", a: "Erik Van Looy" },
    { q: "Wat is de naam van de Vlaamse serie over een undercoveroperatie rond de haven van Antwerpen?", a: "GR5" },
    { q: "Wat is de naam van de Vlaamse serie waarin een vermoorde vrouw terugkeert als geest om haar moordenaar te vinden?", a: "Beau Séjour" },
    { q: "Wie speelde de rol van 'Safety First'-eigenaar Luc in de gelijknamige Vlaamse sitcom?", a: "Bruno Vanden Broecke" },
    { q: "Wat is de naam van de Vlaamse serie waarin een jury zich moet buigen over de zaak van een moord verdachte?", a: "De twaalf" },
    { q: "Welke Vlaamse film uit 2007 volgt het leven van een jonge man die uit de kast komt?", a: "Noordzee, Texas" },
    { q: "Wie speelt de hoofdrol in de Vlaamse serie 'Over Water' over de drugshandel in de haven?", a: "Tom Van Dyck" },
    { q: "Wat is de naam van de filmreeks over de stuntelige voetbalploeg F.C. De Kampioenen?", a: "F.C. De Kampioenen" },
    { q: "In welke Vlaamse serie speelt Maaike Cafmeyer de rol van psycholoog/profiler?", a: "Professor T." },
    { q: "Welke Vlaamse film met Jan Decleir gaat over de sociale strijd van een priester-politicus in Aalst?", a: "Daens" },
    { q: "Welke Vlaamse film uit 2012 gaat over de vriendschap tussen twee jongens in een asielcentrum?", a: "Hasta La Vista" },
    { q: "Wat is de naam van de populaire sketch-serie met de acteurs van 'De Ideale Wereld'?", a: "De Slimste Mens ter Wereld" },
    { q: "Wie is de huidige burgemeester van Antwerpen (per 2024)?", a: "Bart De Wever" },
    { q: "Wat is de naam van de Vlaamse culinaire prijs die jaarlijks wordt uitgereikt aan het beste restaurant?", a: "Gault&Millau (of Michelinsterren)" },
    { q: "Welke stad wordt de 'Arteveldestad' genoemd?", a: "Gent" },
    { q: "Wat is de naam van het beroemde middeleeuwse bouwwerk in Brugge dat op de Grote Markt staat?", a: "Belfort" },
    { q: "Wat is de naam van de Belgische zangeres die bekend staat om het nummer 'Fever'?", a: "Angèle" },
    { q: "Welke Vlaamse auteur schreef de romans 'Het verdriet van België' en 'De Leeuw van Vlaanderen'?", a: "Hugo Claus (en Hendrik Conscience)" },
    { q: "Wat is de naam van het grootste muziekfestival in Werchter?", a: "Rock Werchter" },
    { q: "Welke Belgische stripfiguur draagt een bolhoed en heeft een butler?", a: "Guust Flater" },
    { q: "Wat is de naam van de Belgische schilder uit de 15e eeuw, bekend van 'Het Lam Gods'?", a: "Jan van Eyck" },
    { q: "Welke Vlaamse stad is bekend om zijn tapijtenindustrie?", a: "Kortrijk" },
    { q: "Welke stad wordt de 'Diamantstad' genoemd?", a: "Antwerpen" },
    { q: "Wat is de naam van de Vlaamse dichter die 'De IJzer' schreef?", a: "Karel Van de Woestijne" },
    { q: "Welke Vlaamse politieke partij is de grootste in Vlaanderen (per 2024)?", a: "N-VA" },
    { q: "Welke Vlaamse stad heeft het symbool van de 'Manneken Pis'?", a: "Brussel" },
    { q: "Welke Vlaamse serie draait rond een groep vriendinnen op een internaat?", a: "De Pfaffs" },
    { q: "Wat is de naam van het beroemde kasteel in Gent dat dateert uit de 12e eeuw?", a: "Gravensteen" },
    { q: "Wat is de naam van de Vlaamse presentator die de quiz 'Blokken' presenteert?", a: "Ben Crabbé" },
    { q: "Welke Vlaamse stad staat bekend om zijn kant?", a: "Brugge" },
    { q: "Wat is de naam van de Vlaamse acteur die de rol van **Smos** speelde in *F.C. De Kampioenen*?", a: "Jaak Van Assche" },
    { q: "Wat is de naam van het grootste museum in België (in Brussel)?", a: "Koninklijke Musea voor Schone Kunsten van België" },
    { q: "Welke Vlaamse zangeres won de Eurovisie Songfestival in 1986?", a: "Sandra Kim" },
    { q: "Wat is de naam van de Vlaamse politicus die bekend staat om zijn lange carrière en vaak in de media verschijnt?", a: "Herman Van Rompuy (of Wilfried Martens)" },
    { q: "Welke Vlaamse stad is bekend om zijn Ossenkopgebouw (hoofdkwartier van de VRT)?", a: "Brussel" },
    { q: "Wat is de naam van de Vlaamse film van **Jan Verheyen** over de Dutroux-zaak?", a: "De Zaak Dutroux" },
    { q: "Welke Vlaamse komische serie draait rond de familie De Pfaffs?", a: "De Pfaffs" },
    { q: "Wat is de naam van de Vlaamse zanger die bekend staat om zijn deelname aan 'Eurosong' in 2023?", a: "Gustaph" },
    { q: "Welke Vlaamse stripfiguur heeft de bijnaam 'De Groene Belg'?", a: "Piet Piraat" },
    { q: "Wat is de naam van het beroemde gebouw in Antwerpen dat bekend staat om zijn dierentuin?", a: "Antwerpen Centraal" },
    { q: "Welke Vlaamse acteur speelt de rol van de commissaris in de serie *Witse*?", a: "Hubert Damen" },
    { q: "Wat is de naam van de Vlaamse serie over een groep jongeren die de muziekschool onveilig maken?", a: "Campus 12" },
    { q: "Welke Vlaamse film uit 2018 gaat over de moord op een jongetje en zijn familie?", a: "Niet Schieten" },
    
    // --- Eten & Koken (75 Vragen) ---
    { q: "Welk land staat bekend om de culinaire uitvinding van pizza?", a: "Italië" },
    { q: "Wat is de naam van het gerecht dat bestaat uit een dunne laag deeg met beleg, gebakken in een steenoven (niet pizza)?", a: "Flammkuchen" },
    { q: "Wat is het hoofdingrediënt van hummus?", a: "Kikkererwten" },
    { q: "Wat is de naam van de Japanse methode om vis rauw te serveren, vaak op rijst?", a: "Sushi" },
    { q: "Welke groente is het hoofdingrediënt van traditionele gazpacho?", a: "Tomaat" },
    { q: "Wat is de naam van de beroemde Belgische chocolade die in een kegelvorm wordt gemaakt en vaak met een vulling?", a: "Praline" },
    { q: "Welke saus is het hoofdingrediënt in de klassieke spaghetti carbonara?", a: "Ei (en Pecorino/Guanciale)" },
    { q: "Wat is de naam van het Franse gerecht van eieren, melk en kaas in een korst?", a: "Quiche" },
    { q: "Welke plant wordt gebruikt om tequila te maken?", a: "Blauwe agave" },
    { q: "Wat is de naam van de kruidige mix van vlees, groenten en rijst uit Spanje?", a: "Paella" },
    { q: "Wat is de naam van de beroemde Belgische frietsaus op basis van eigeel en azijn?", a: "Mayonaise" },
    { q: "Uit welk land komt de Moussaka?", a: "Griekenland" },
    { q: "Wat is de naam van het traditionele Chinese gerecht dat wordt gestoomd in bamboemandjes?", a: "Dim sum" },
    { q: "Wat is de naam van de kaassoort die in Zwitserland vaak wordt gesmolten en geserveerd met aardappelen en augurken?", a: "Raclette" },
    { q: "Welke citrusvrucht wordt vaak gebruikt om een 'Mojito' cocktail te maken?", a: "Limoen" },
    { q: "Wat is de naam van het Belgische bier dat wordt gebrouwen in abdijen?", a: "Trappistenbier (of Abdijbier)" },
    { q: "Wat is het hoofdingrediënt van een traditionele Tiramisu?", a: "Mascarpone" },
    { q: "Wat is de naam van de techniek waarbij je voedsel snel bakt op hoog vuur, vaak in een wok?", a: "Roerbakken (Stir-frying)" },
    { q: "Welke kaas wordt traditioneel gebruikt in een Griekse salade?", a: "Feta" },
    { q: "Wat is de naam van het Zuid-Amerikaanse gerecht van rauwe vis gemarineerd in citrusvruchtensap?", a: "Ceviche" },
    { q: "Wat is de naam van de scherpe, gekruide Indiase saus die vaak bij curry wordt geserveerd?", a: "Chutney" },
    { q: "Wat is de naam van de zoete aardappel die vaak als friet wordt geserveerd?", a: "Zoete aardappelfriet" },
    { q: "Wat is het belangrijkste ingrediënt in traditionele pesto?", a: "Basilicum" },
    { q: "Welk land staat bekend om de uitvinding van de croissant?", a: "Oostenrijk (populair in Frankrijk)" },
    { q: "Wat is de naam van de Belgische schotel van gepocheerd ei, ham en kaassaus op toast?", a: "Croque-madame (of Croque-monsieur)" },
    { q: "Wat is de naam van de techniek waarbij men vlees langzaam kookt in zijn eigen vet?", a: "Confit" },
    { q: "Welke drank wordt gemaakt van de bladeren van de theeplant (Camellia sinensis)?", a: "Thee" },
    { q: "Wat is de naam van de Italiaanse pastavorm die eruitziet als kleine vlinders?", a: "Farfalle" },
    { q: "Wat is de naam van de Chinese soep met gevulde deegzakjes?", a: "Wonton soep" },
    { q: "Welke alcoholische drank wordt gemaakt van gefermenteerde druiven?", a: "Wijn" },
    { q: "Wat is de naam van de Belgische koek die vaak wordt gegeten bij koffie, gemaakt van bruine suiker?", a: "Speculoos" },
    { q: "Wat is het hoofdingrediënt in de Koreaanse kimchi?", a: "Napa-kool (Chinese kool)" },
    { q: "Wat is de naam van de Franse saus van eigeel, boter en citroensap?", a: "Hollandaise saus" },
    { q: "Welk land staat bekend om de uitvinding van de taco?", a: "Mexico" },
    { q: "Wat is de naam van de Italiaanse rijstschotel die langzaam wordt gekookt met bouillon en boter?", a: "Risotto" },
    { q: "Welke vis wordt traditioneel gebruikt voor 'Fish and Chips'?", a: "Kabeljauw (of Schelvis)" },
    { q: "Wat is de naam van het Belgische gerecht van mosselen gekookt in witte wijn en groenten?", a: "Mosselen-friet" },
    { q: "Wat is de naam van het scherpe poeder gemaakt van gedroogde rode pepers?", a: "Chili (of Cayennepeper)" },
    { q: "Welke drank wordt gemaakt van gefermenteerde appels?", a: "Cider" },
    { q: "Wat is de naam van de techniek waarbij men groenten in heel dunne, lange reepjes snijdt?", a: "Julienne" },
    { q: "Wat is de naam van de Indiase broodsoort die vaak wordt gebakken in een tandoor-oven?", a: "Naan" },
    { q: "Welk land staat bekend om de uitvinding van de schnitzel?", a: "Oostenrijk (populair in Duitsland)" },
    { q: "Wat is de naam van de zoete Belgische wafels met karamelvulling?", a: "Luikse wafel (of stroopwafel - Nederlands)" },
    { q: "Wat is de naam van de alcoholische drank gemaakt van gefermenteerde suikerrietmelasse?", a: "Rum" },
    { q: "Welke groente wordt vaak gebruikt om 'ratatouille' te maken?", a: "Aubergine (of Courgette)" },
    { q: "Wat is de naam van de techniek waarbij men voedsel vacuüm verpakt en op een nauwkeurige lage temperatuur kookt?", a: "Sous-vide" },
    { q: "Wat is de naam van de beroemde Italiaanse ham die rauw wordt gegeten?", a: "Prosciutto" },
    { q: "Welk land staat bekend om de uitvinding van de hamburger?", a: "Duitsland (Hamburg) / Verenigde Staten" },
    { q: "Wat is de naam van het Belgische gerecht van gehaktballetjes in tomatensaus?", "a": "Balletjes in tomatensaus" },
    { q: "Wat is de naam van de scherpe, donkere sojasaus die in Azië wordt gebruikt?", "a": "Ketjap manis (zoet) / Ketjap asin (zout)" },
    { q: "Welk land staat bekend om de uitvinding van de pannenkoek?", "a": "Griekenland (als de oorsprong)" },
    { q: "Wat is de naam van de techniek waarbij men room met suiker klopt tot een schuimige massa?", "a": "Kloppen (of Slagroom maken)" },
    { q: "Welke Belgische frietsaus is gebaseerd op curry en mayonaise?", "a": "Currysaus (of Curry-mayonaise)" },
    { q: "Wat is het hoofdingrediënt in de Marokkaanse 'couscous'?", "a": "Griesmeel" },
    { q: "Welk land staat bekend om de uitvinding van de falafel?", "a": "Egypte (of het Midden-Oosten)" },
    { q: "Wat is de naam van de Italiaanse kaas die vaak wordt gebruikt op pasta en geraspt wordt?", "a": "Parmezaanse kaas (Parmigiano Reggiano)" },
    { q: "Welke vrucht wordt gebruikt om de drank 'limoncello' te maken?", "a": "Citroen" },
    { q: "Wat is de naam van de techniek waarbij men groenten kort in kokend water blancheren en dan in ijswater koelen?", "a": "Blancheren" },
    { q: "Wat is de naam van het Belgische gerecht van aardappelen, spek en uien?", "a": "Stoemp (of Hutspot - Nederlands)" },
    { q: "Welk land staat bekend om de uitvinding van de chili con carne?", "a": "Verenigde Staten (Texas)" },
    { q: "Wat is de naam van de techniek waarbij men het vet uit het vlees laat smelten om krokant te worden?", "a": "Uitbakken (Rendering)" },
    { q: "Welke Belgische stad is bekend om zijn 'Gentse waterzooi'?", "a": "Gent" },
    { q: "Wat is de naam van de beroemde Franse schotel van aardappelen in room en kaas?", "a": "Gratin dauphinois" },
    { q: "Welk land staat bekend om de uitvinding van de Wiener Sacher-Torte?", "a": "Oostenrijk" },
    { q: "Wat is de naam van de techniek waarbij men de randen van een taartdeeg mooi afwerkt?", "a": "Rimpelen (Crimpen)" },
    { q: "Welke Belgische frietsaus is op basis van tomaten en azijn?", "a": "Ketchup" },
    { q: "Wat is het hoofdingrediënt in de Thaise 'Pad Thai'?", "a": "Rijstnoedels" },
    { q: "Welk land staat bekend om de uitvinding van de Tiramisu?", "a": "Italië" },
    { q: "Wat is de naam van de techniek waarbij men deeg laat rijzen?", "a": "Fermenteren (Rijzen)" },
    { q: "Welke Belgische groente is bekend om zijn bittere smaak?", "a": "Witloof" },
    { q: "Wat is de naam van het beroemde Italiaanse ijs?", "a": "Gelato" },
    { q: "Welk land staat bekend om de uitvinding van de worstenbroodjes (als fast food)?", "a": "Verenigd Koninkrijk" },
    { q: "Wat is de naam van de techniek waarbij men vis of vlees snel dichtschroeit?", "a": "Searen (Aanbraden)" },
    { q: "Welke Belgische stad is bekend om zijn 'Brugse Zot' bier?", "a": "Brugge" }
// ... (Plak dit achter jouw bestaande lijst om tot 500+ te komen)

    // --- AANVULLING: Muziek, Festivals & Nightlife (Jongvolwassenen) ---
    { q: "Welk Belgisch festival vindt plaats in Boom?", a: "Tomorrowland" },
    { q: "Hoeveel leden telt de K-pop groep BTS?", a: "7" },
    { q: "Wie is de echte naam van de DJ Lost Frequencies?", a: "Felix De Laet" },
    { q: "Welke Amerikaanse zangeres staat bekend als 'Queen B'?", a: "Beyoncé" },
    { q: "Hoeveel snaren heeft een standaard gitaar?", a: "6" },
    { q: "Welke zangeres overleed op 27-jarige leeftijd en zong 'Back to Black'?", a: "Amy Winehouse" },
    { q: "In welk jaar overleed Avicii?", a: "2018" },
    { q: "Welke band zingt 'Viva La Vida'?", a: "Coldplay" },
    { q: "Hoeveel leden had The Beatles?", a: "4" },
    { q: "Wie won het Eurovisiesongfestival voor Zweden met 'Euphoria'?", a: "Loreen" },
    { q: "Welke rapper is getrouwd (geweest) met Kim Kardashian?", a: "Kanye West" },
    { q: "Wat is de artiestennaam van Marshall Mathers?", a: "Eminem" },
    { q: "Welke zangeres bracht de albums '19', '21', '25' en '30' uit?", a: "Adele" },
    { q: "Welk nummer van Queen duurt 6 minuten en is een mix van opera en rock?", a: "Bohemian Rhapsody" },
    { q: "Wie is de zanger van de Foo Fighters?", a: "Dave Grohl" },
    { q: "Welk festival vindt plaats op de weide van Kiewit (Hasselt)?", a: "Pukkelpop" },
    { q: "Welke Vlaamse groep scoorde een hit met 'Ik wil je'?", a: "De Kreuners" },
    { q: "Hoe heet de fanschare van Justin Bieber?", a: "Beliebers" },
    { q: "Welke dj gooide taarten naar het publiek?", a: "Steve Aoki" },
    { q: "Wie zong de titelsong voor de James Bond-film 'Skyfall'?", a: "Adele" },
    { q: "Wat is de voornaam van de zangeres Rihanna?", a: "Robyn" },
    { q: "Welk instrument bespeelt Lizzo?", a: "Dwarsfluit" },
    { q: "Wie is de vader van Miley Cyrus?", a: "Billy Ray Cyrus" },
    { q: "Welke Belgische band zong 'Wrong' en 'Mad About You'?", a: "Hooverphonic" },
    { q: "Hoeveel toetsen heeft een standaard piano?", a: "88" },
    { q: "Wie is de zanger van de hit 'Watermelon Sugar'?", a: "Harry Styles" },
    { q: "Welke Nederlandse zangeres deed mee aan het Songfestival met 'De Diepte'?", a: "S10" },
    { q: "Wat is de artiestennaam van Abel Tesfaye?", a: "The Weeknd" },
    { q: "Welke broers vormen een bekend Belgisch DJ-duo?", a: "Dimitri Vegas & Like Mike" },
    { q: "Wie zong de hit 'Purple Rain'?", a: "Prince" },
    { q: "Welk land won het Eurovisiesongfestival in 2021 (Måneskin)?", a: "Italië" },
    { q: "Hoeveel leden heeft de band Metallica?", a: "4" },
    { q: "Welke Vlaamse zangeres scoorde een hit met 'Ongewoon'?", a: "Pommelien Thijs" },
    { q: "Wat is de artiestennaam van de Belgische rapper Brihang?", a: "Boudy Verleye" },
    { q: "Welke zangeres staat bekend om haar paardenstaart (ponytail)?", a: "Ariana Grande" },
    { q: "Hoe heet de zanger van de Red Hot Chili Peppers?", a: "Anthony Kiedis" },

    // --- AANVULLING: Films, Series & Games (Popcultuur & Nostalgie) ---
    { q: "Hoeveel seizoenen heeft de serie 'Friends'?", a: "10" },
    { q: "Wat is de naam van de groene baby in 'The Mandalorian'?", a: "Grogu (of Baby Yoda)" },
    { q: "Welke kleur pil kiest Neo in 'The Matrix'?", a: "Rood" },
    { q: "Hoe heet de fictieve taal in 'Avatar'?", a: "Na'vi" },
    { q: "Wie speelt de hoofdrol in 'Pirates of the Caribbean'?", a: "Johnny Depp" },
    { q: "Hoeveel films zijn er in de originele 'Lord of the Rings'-trilogie?", a: "3" },
    { q: "Welk videospel speelt zich af in 'Los Santos'?", a: "GTA V" },
    { q: "Wat is de naam van de prinses in de Super Mario-games?", a: "Peach" },
    { q: "Welke serie gaat over een scheikundeleraar die meth gaat koken?", a: "Breaking Bad" },
    { q: "Hoe heet de tijger in 'The Lion King' (de schurk)?", a: "Scar" },
    { q: "Wat is de hoogste kaartwaarde in een standaard kaartspel (zonder joker)?", a: "Aas" },
    { q: "Welke acteur speelt 'Iron Man'?", a: "Robert Downey Jr." },
    { q: "Wat is de naam van de Pokémon mascotte (geel)?", a: "Pikachu" },
    { q: "In welke stad speelt de serie 'Sex and the City' zich af?", a: "New York" },
    { q: "Wat is het huisnummer van Sherlock Holmes in Baker Street?", a: "221B" },
    { q: "Wie is de maker van 'Star Wars'?", a: "George Lucas" },
    { q: "Hoeveel zijden heeft een dobbelsteen?", a: "6" },
    { q: "Welke streamingdienst heeft een logo met een plusje?", a: "Disney+" },
    { q: "Wat is de naam van de drakonische koningin in 'Game of Thrones'?", a: "Daenerys Targaryen" },
    { q: "Welke film won de Oscar voor Beste Film in 2024?", a: "Oppenheimer" },
    { q: "Wie spreekt de stem in van de ezel in 'Shrek' (Engels)?", a: "Eddie Murphy" },
    { q: "Wat is de naam van de pop in de horrorfilm 'Annabelle'?", a: "Annabelle" },
    { q: "In welk jaar kwam de eerste iPhone uit?", a: "2007" },
    { q: "Hoe heet de krant waar Peter Parker (Spiderman) voor werkt?", a: "Daily Bugle" },
    { q: "Wat is de naam van de dinosaurus-filmfranchise van Steven Spielberg?", a: "Jurassic Park" },
    { q: "Wie speelt de rol van 'Thor' in de Marvel-films?", a: "Chris Hemsworth" },
    { q: "Wat is de naam van de fictieve school in 'Sex Education'?", a: "Moordale" },
    { q: "Hoeveel levens heeft een kat volgens het gezegde?", a: "9" },
    { q: "Wat is de naam van de vampier in 'Twilight'?", a: "Edward Cullen" },
    { q: "Welke game gaat over het bouwen met blokken en overleven?", a: "Minecraft" },
    { q: "Wie is de broer van Mario?", a: "Luigi" },
    { q: "Wat is de naam van de pop in 'Squid Game' (Red Light, Green Light)?", a: "Young-hee" },
    { q: "Welke acteur speelt de hoofdrol in 'Mission: Impossible'?", a: "Tom Cruise" },
    { q: "Hoe heet de oranje vis in 'Finding Nemo' (de vader)?", a: "Marlin" },
    { q: "Welke tovenaar is het schoolhoofd van Zweinstein?", a: "Albus Perkamentus" },

    // --- AANVULLING: Vlaamse Nostalgie & Media (18-40 jaar) ---
    { q: "Wat is de naam van de hond van Samson?", a: "Samson" },
    { q: "Hoe heet de burgemeester in 'Samson en Gert'?", a: "Modest" },
    { q: "Welke meidengroep bestond oorspronkelijk uit Karen, Kristel en Kathleen?", a: "K3" },
    { q: "Wat is de naam van de kabouter met de plopmuts?", a: "Plop" },
    { q: "Welke Studio 100-heldin is een superheldin in een strak pakje?", a: "Mega Mindy" },
    { q: "In welke jongerenserie speelden personages als Steve, Birgit en Zoë?", a: "W817" },
    { q: "Wat is de naam van de dansschool in de serie 'Spring'?", a: "Spring" },
    { q: "Wie presenteerde jarenlang 'De Mol' (de eerste seizoenen)?", a: "Michiel Devlieger" },
    { q: "Welk programma zoekt naar de 'Slimste Mens'?", a: "De Slimste Mens ter Wereld" },
    { q: "Wat is de naam van de kok in 'F.C. De Kampioenen' (na BTW)?", a: "Fernand Costermans" },
    { q: "Welke Vlaamse zender zendt 'Thuis' uit?", a: "VRT 1 (of Eén)" },
    { q: "Wie is de presentator van 'De Mol' (huidige seizoenen)?", a: "Gilles De Coster" },
    { q: "Welke acteur speelt de rol van 'Het Varken' (Balthasar Boma)?", a: "Marijn Devalck" },
    { q: "Wat is de naam van het programma waarin Vlamingen huizen kopen in het buitenland zonder ze te zien?", a: "Blind Gekocht" },
    { q: "Wie won het eerste seizoen van 'Big Brother' in Vlaanderen (2000)?", a: "Steven Spillebeen" },
    { q: "Wat is de naam van de sidekick van Gert Verhulst in 'De Tafel van Gert'?", a: "Viktor Verhulst (of wisselend)" },
    { q: "Welk dier is 'Bumba'?", a: "Clown" },
    { q: "Hoe heet de broer van Staf Coppens?", a: "Mathias Coppens" },
    { q: "Welke Vlaamse zangeres zingt 'Nooit meer naar huis'?", a: "Pommelien Thijs" },
    { q: "Wie presenteert 'Het Huis'?", a: "Eric Goens" },
    { q: "Wat is de naam van de bekende Vlaamse weerman die met pensioen ging in 2023?", a: "Frank Deboosere" },
    { q: "Welk sociaal netwerk was gigantisch populair in België voor Facebook?", a: "Netlog" },
    { q: "Hoe heet de hond van Kuifje?", a: "Bobbie" },
    { q: "Welke krant wordt uitgegeven op roze papier?", a: "De Financieel Economische Tijd (De Tijd)" },
    { q: "Wie presenteert 'De Verhulstjes'?", a: "De familie Verhulst" },
    { q: "Wat is de naam van de bekende YouTuber 'Average Rob'?", a: "Robert Van Impe" },
    { q: "Welke Vlaamse zanger staat bekend als 'Metejoor'?", a: "Joris van Rossem" },

    // --- AANVULLING: Wetenschap, Natuur & Tech ---
    { q: "Hoeveel procent van de aarde is bedekt met water (ongeveer)?", a: "71" },
    { q: "Wat is het snelste landdier ter wereld?", a: "Jachtluipaard" },
    { q: "Hoeveel poten heeft een spin?", a: "8" },
    { q: "Wat is de chemische formule voor water?", a: "H2O" },
    { q: "Hoe heet de CEO van Tesla en SpaceX?", a: "Elon Musk" },
    { q: "Wat is de naam van de zoekmachine van Microsoft?", a: "Bing" },
    { q: "Hoeveel graden Celsius is het kookpunt van water?", a: "100" },
    { q: "Welk zoogdier kan vliegen?", a: "Vleermuis" },
    { q: "Hoeveel tanden heeft een volwassen mens (inclusief verstandskiezen)?", a: "32" },
    { q: "Wat is de grootste planeet in ons zonnestelsel?", a: "Jupiter" },
    { q: "Wat is de snelheid van het licht (afgerond in km/s)?", a: "300000" },
    { q: "Welk element heeft het symbool 'O'?", a: "Zuurstof" },
    { q: "Hoeveel harten heeft een octopus?", a: "3" },
    { q: "Wat is de naam van de virtuele assistent van Amazon?", a: "Alexa" },
    { q: "Wat betekent de afkorting 'AI'?", a: "Artificiële Intelligentie" },
    { q: "Welke planeet staat het dichtst bij de zon?", a: "Mercurius" },
    { q: "Hoeveel botten heeft een menselijk lichaam?", a: "206" },
    { q: "Wat is de naam van de pandemie die begon in 2019?", a: "COVID-19" },
    { q: "Welke bloedgroep is de universele donor?", a: "O negatief" },
    { q: "Wat is de hardste natuurlijke stof op aarde?", a: "Diamant" },
    { q: "Hoeveel chromosoomparen heeft een mens?", a: "23" },
    { q: "Wat is de naam van de eerste man op de maan?", a: "Neil Armstrong" },
    { q: "Wat is de naam van het bedrijf achter ChatGPT?", a: "OpenAI" },
    { q: "Welk dier is het symbool van het Wereld Natuur Fonds (WWF)?", a: "Reuzenpanda" },
    { q: "Wat is de grootste orgaan van het menselijk lichaam (oppervlakte)?", a: "Huid" },
    { q: "Welke planeet wordt de 'Avondster' genoemd?", a: "Venus" },

    // --- AANVULLING: Sport (Extra) ---
    { q: "Wie is de recordhouder van de meeste Olympische medailles aller tijden?", a: "Michael Phelps" },
    { q: "Hoeveel spelers staan er bij een basketbalteam op het veld?", a: "5" },
    { q: "Welke kleur trui draagt de leider in de Giro d'Italia?", a: "Roze" },
    { q: "In welk land werd het WK voetbal 2022 gehouden?", a: "Qatar" },
    { q: "Wat is de bijnaam van darter Michael van Gerwen?", a: "Mighty Mike" },
    { q: "Hoeveel minuten duurt een rugbywedstrijd?", a: "80" },
    { q: "Welke Belgische wielrenner wordt 'De Aerokogel van Schepdaal' genoemd?", a: "Remco Evenepoel" },
    { q: "Bij welke sport gebruik je een 'cue'?", a: "Snooker (of Biljart)" },
    { q: "Welk nummer heeft Max Verstappen op zijn auto?", a: "1" },
    { q: "Hoe heet het stadion van FC Barcelona?", a: "Spotify Camp Nou" },
    { q: "Wie is de topscorer aller tijden van de Rode Duivels?", a: "Romelu Lukaku" },
    { q: "Welke tennisser wordt de 'King of Clay' (Gravelkoning) genoemd?", a: "Rafael Nadal" },
    { q: "Hoeveel gaten heeft een dartbord (de vakjes)?", a: "20" },
    { q: "Welke sport beoefent Nina Derwael?", a: "Turnen" },
    { q: "Hoeveel punten is een touchdown in American Football?", a: "6" },
    { q: "Welke Belgische club wordt 'The Great Old' genoemd?", a: "Royal Antwerp FC" },
    { q: "Wie won de Tour de France in 2020 en 2021?", a: "Tadej Pogačar" },
    { q: "Hoeveel spelers heeft een volleybalteam in het veld?", a: "6" },
    { q: "In welke stad speelt de voetbalclub Chelsea?", a: "Londen" },
    { q: "Wat is de maximale score in één beurt bij darten?", a: "180" },
    { q: "Welk land won het WK Vrouwenvoetbal in 2023?", a: "Spanje" },
    { q: "Wie is de huidige trainer van Manchester City (2024)?", a: "Pep Guardiola" },

    // --- AANVULLING: Eten, Drinken & Lifestyle ---
    { q: "Wat is de basis van Guacamole?", a: "Avocado" },
    { q: "Welk merk produceert de 'Big Mac'?", a: "McDonald's" },
    { q: "Wat is de populairste frisdrank ter wereld?", a: "Coca-Cola" },
    { q: "Uit welk land komt IKEA?", a: "Zweden" },
    { q: "Wat is de naam van de bekende koffieketen uit Seattle?", a: "Starbucks" },
    { q: "Welke kleur heeft Chardonnay wijn?", a: "Wit" },
    { q: "Wat is het hoofdingrediënt van bier?", a: "Water (en Gerst/Mout)" },
    { q: "Hoeveel sterren kan een restaurant maximaal krijgen van Michelin?", a: "3" },
    { q: "Wat is de naam van de Japanse noedelsoep?", a: "Ramen" },
    { q: "Welke vitamine halen we voornamelijk uit zonlicht?", a: "Vitamine D" },
    { q: "Wat is de naam van het beroemde energiedrankje met de slogan 'Geeft je vleugels'?", a: "Red Bull" },
    { q: "Welke noot zit er in marsepein?", a: "Amandel" },
    { q: "Wat is de naam van de bekende Belgische koekjesfabrikant uit Lembeke?", a: "Lotus" },
    { q: "Uit welk land komt de cocktail Caipirinha?", a: "Brazilië" },
    { q: "Wat is de duurste specerij ter wereld?", a: "Saffraan" },
    { q: "Wat is de naam van de saus gemaakt van basilicum, pijnboompitten en olijfolie?", a: "Pesto" },
    { q: "Welk fruit is het symbool van het techbedrijf Apple?", a: "Appel" },
    { q: "Wat is de naam van de vleesvervanger gemaakt van soja?", a: "Tofu" },
    { q: "Welke kleur heeft een Granny Smith appel?", a: "Groen" },
    { q: "Hoeveel milliliter zit er in een standaard blikje frisdrank?", a: "330" },
    { q: "Wat is de naam van de saus die traditioneel bij asperges wordt geserveerd?", a: "Hollandaise" },
    { q: "Welk land is de grootste producent van koffie?", a: "Brazilië" },
    { q: "Wat is het hoofdingrediënt van een omelet?", a: "Ei" },
    
    // --- AANVULLING: Algemene Kennis & Geschiedenis (Jongeren focus) ---
    { q: "Welke stad is de hoofdstad van de Verenigde Staten?", a: "Washington D.C." },
    { q: "Hoeveel dagen heeft een schrikkeljaar?", a: "366" },
    { q: "Op welke datum valt Kerstdag?", a: "25 december" },
    { q: "Welke kleur krijg je als je blauw en geel mengt?", a: "Groen" },
    { q: "Hoeveel sterren staan er op de vlag van de EU?", a: "12" },
    { q: "Wat is de hoofdstad van Australië?", a: "Canberra" },
    { q: "Wie schreef 'Romeo en Julia'?", a: "William Shakespeare" },
    { q: "Wat is de officiële taal van Brazilië?", a: "Portugees" },
    { q: "Hoeveel seizoenen zijn er in een jaar?", a: "4" },
    { q: "Wat is de naam van de toren in Parijs?", a: "Eiffeltoren" },
    { q: "Welk land heeft de vorm van een laars?", a: "Italië" },
    { q: "In welk jaar vond de aanslag op de Twin Towers plaats?", a: "2001" },
    { q: "Wat is de valuta van Zwitserland?", a: "Zwitserse Frank" },
    { q: "Hoeveel provincies heeft België?", a: "10" },
    { q: "Wat is de naam van de huidige koning van België?", a: "Filip" },
    { q: "Welke kleur is de 'Black Box' in een vliegtuig?", a: "Oranje" },
    { q: "Wat is de naam van het beroemde festival in de woestijn van Nevada?", a: "Burning Man" },
    { q: "Hoe heet de vrouw van prins William?", a: "Kate Middleton" },
    { q: "Wat is de hoofdstad van Duitsland?", a: "Berlijn" },
    { q: "Hoeveel continenten zijn er?", a: "7" },
    { q: "Wat is de naam van de Romeinse god van de liefde?", a: "Cupido" },
    { q: "Welk land wordt het 'Land van de Rijzende Zon' genoemd?", a: "Japan" },
    { q: "Wat is de naam van de langste rivier in Afrika?", a: "Nijl" },
    { q: "Wie was de eerste zwarte president van de VS?", a: "Barack Obama" },
    { q: "Welke taal wordt het meest gesproken ter wereld (moedertaal)?", a: "Mandarijn (Chinees)" },
    { q: "Wat is de naam van de hoogste toren ter wereld (in Dubai)?", a: "Burj Khalifa" },
    { q: "Wat is de landcode van België?", a: "+32" },
    { q: "Hoeveel uur zit er in een week?", a: "168" },
    { q: "Wat is de naam van het schip dat zonk in 1912?", a: "Titanic" },
    { q: "Welk land heeft de meeste inwoners ter wereld (2023/2024)?", a: "India" },
    
    // --- AANVULLING: Mix van 80s/90s/00s & Varia ---
    { q: "Welk speelgoed was een digitaal huisdier aan een sleutelhanger?", a: "Tamagotchi" },
    { q: "Wat is de naam van de onverwoestbare gsm van Nokia?", a: "Nokia 3310" },
    { q: "Welk besturingssysteem volgde Windows 98 op?", a: "Windows XP" },
    { q: "Wat was de naam van de videotheekketen die failliet ging?", a: "Blockbuster" },
    { q: "Welke kleur heeft Pac-Man?", a: "Geel" },
    { q: "Hoe heet de loodgieter in de game Donkey Kong?", a: "Mario (toen Jumpman)" },
    { q: "Welke boyband zong 'I Want It That Way'?", a: "Backstreet Boys" },
    { q: "Wat is de voornaam van 'The Fresh Prince'?", a: "Will" },
    { q: "Welke film gaat over een park met dinosaurussen?", a: "Jurassic Park" },
    { q: "Wat is de naam van de leeuwenkoning?", a: "Simba" },
    { q: "Welk snoepje kon je om je nek dragen als ketting?", a: "Snoepketting" },
    { q: "Wat is de naam van de fee in Peter Pan?", a: "Tinkerbell" },
    { q: "Welke kleur hadden de smurfen?", a: "Blauw" },
    { q: "Wat is de naam van de oranje kat die lasagne eet?", a: "Garfield" },
    { q: "Welk bordspel draait om het kopen van straten?", a: "Monopoly" },
    { q: "Wat is de naam van de popgroep met Ginger, Sporty, Posh, Scary en Baby?", a: "Spice Girls" },
    { q: "In welk jaar was de millenniumwisseling?", a: "2000" },
    { q: "Wat is de naam van de beer van Mr. Bean?", a: "Teddy" },
    { q: "Welk automerk heeft een logo met vier ringen?", a: "Audi" },
    { q: "Wat is de naam van de bekendste pop ter wereld?", a: "Barbie" },
    { q: "Welke kleur is de 'M' van McDonald's?", a: "Geel" },
    { q: "Hoeveel wielen heeft een eenwieler?", a: "1" },
    { q: "Wat is de naam van de clown in 'It'?", a: "Pennywise" },
    { q: "Welke dag komt na dinsdag?", a: "Woensdag" },
    { q: "Wat is de naam van de magiër in Lord of the Rings?", a: "Gandalf" },
    { q: "Welk dier is Sonic?", a: "Egel" },
    { q: "Wat is de naam van de prinses in Zelda?", a: "Zelda" },
    { q: "Hoeveel millimeter is 1 meter?", a: "1000" },
    { q: "Wat is de naam van de vriend van Mickey Mouse?", a: "Minnie Mouse" },
    { q: "Welk fruit eet Pac-Man voor extra punten?", a: "Kers" },
    
    // --- LAATSTE AANVULLING: Tech & Modern Leven ---
    { q: "Wat is de naam van de auto-pilot functie van Tesla?", a: "Autopilot" },
    { q: "Wat is de afkorting voor 'World Wide Web'?", a: "WWW" },
    { q: "Welk bedrijf maakt de PlayStation?", a: "Sony" },
    { q: "Wat is de naam van de app waar je foto's na 24 uur verdwijnen?", a: "Snapchat" },
    { q: "Hoe noemt men een internetdagboek?", a: "Blog" },
    { q: "Wat is de naam van de cloudservice van Apple?", a: "iCloud" },
    { q: "Wat is de afkorting voor 'Electronic Dance Music'?", a: "EDM" },
    { q: "Welk platform is eigendom van Meta (naast Facebook)?", a: "Instagram (of WhatsApp)" },
    { q: "Wat is de naam van de digitale munt die begon als een grap (hond)?", a: "Dogecoin" },
    { q: "Wat betekent de afkorting 'USB'?", a: "Universal Serial Bus" },
    { q: "Hoeveel karakters mocht een tweet oorspronkelijk hebben?", a: "140" },
    { q: "Wat is de naam van de browser van Google?", a: "Chrome" },
    { q: "Wat is de naam van de oprichter van Microsoft?", a: "Bill Gates" },
    { q: "Welke letter staat er op het logo van Superman?", a: "S" },
    { q: "Wat is de naam van de stem van de iPhone?", a: "Siri" },
    { q: "Wat is de naam van de streamingdienst voor gamers?", a: "Twitch" },
    { q: "Hoeveel procent batterij heb je als je telefoon 'vol' is?", a: "100" },
    { q: "Wat is de naam van de kabel om je tv aan te sluiten?", a: "HDMI" },
    { q: "Welk land heeft de extensie .nl?", a: "Nederland" },
    { q: "Wat is de naam van de virtuele wereld van Facebook?", a: "Metaverse" }
];