// quizdata_300_vragen_jongvolwassenen.js - 300 Vragen voor 18-40 jarigen

var STANDAARD_R1_POOL = [
    // --- Algemene Kennis & Technologie ---
    { q: "Wat is de naam van de technologie achter Bitcoin en andere crypto?", a: "Blockchain" },
    { q: "Wat is de naam van de populaire app voor het delen van korte video's?", a: "TikTok" },
    { q: "Wie schilderde het beroemde werk 'De Sterrennacht'?", a: "Vincent van Gogh" },
    { q: "Wat is de chemische formule voor tafelzout?", a: "NaCl" },
    { q: "Wat is de naam van de bergketen die door de westkust van Zuid-Amerika loopt?", a: "Andes" },
    { q: "Wat is de valuta van Japan?", a: "Yen" },
    { q: "In welk jaar viel de Berlijnse Muur?", a: "1989" },
    // ... (Je eerdere vragen zijn hier weggelaten voor de leesbaarheid, maar zorg dat de structuur klopt) ...
    
    // [LET OP: Hier zat de fout. Zorg dat de regel hieronder eindigt met een komma!]
    { q: "Welke Belgische stad is bekend om zijn 'Brugse Zot' bier?", a: "Brugge" }, 

    // --- AANVULLING: Muziek, Festivals & Nightlife ---
    { q: "Welk Belgisch festival vindt plaats in Boom?", a: "Tomorrowland" },
    { q: "Hoeveel leden telt de K-pop groep BTS?", a: "7" },
    { q: "Wie is de echte naam van de DJ Lost Frequencies?", a: "Felix De Laet" },
    { q: "Welke Amerikaanse zangeres staat bekend als 'Queen B'?", a: "Beyoncé" },
    { q: "Hoeveel snaren heeft een standaard gitaar?", a: "6" },
    { q: "Welke zangeres overleed op 27-jarige leeftijd en zong 'Back to Black'?", a: "Amy Winehouse" },
    { q: "In welk jaar overleed Avicii?", a: "2018" },
    { q: "Welke band zingt 'Viva La Vida'?", a: "Coldplay" },
    { q: "Hoeveel leden had The Beatles?", a: "4" },
    { q: "Wie won het Eurovisiesongfestival voor Zweden met 'Euphoria'?", a: "Loreen" },
    { q: "Welke rapper is getrouwd (geweest) met Kim Kardashian?", a: "Kanye West" },
    { q: "Wat is de artiestennaam van Marshall Mathers?", a: "Eminem" },
    { q: "Welke zangeres bracht de albums '19', '21', '25' en '30' uit?", a: "Adele" },
    { q: "Welk nummer van Queen duurt 6 minuten en is een mix van opera en rock?", a: "Bohemian Rhapsody" },
    { q: "Wie is de zanger van de Foo Fighters?", a: "Dave Grohl" },
    { q: "Welk festival vindt plaats op de weide van Kiewit (Hasselt)?", a: "Pukkelpop" },
    { q: "Welke Vlaamse groep scoorde een hit met 'Ik wil je'?", a: "De Kreuners" },
    { q: "Hoe heet de fanschare van Justin Bieber?", a: "Beliebers" },
    { q: "Welke dj gooide taarten naar het publiek?", a: "Steve Aoki" },
    { q: "Wie zong de titelsong voor de James Bond-film 'Skyfall'?", a: "Adele" },
    { q: "Wat is de voornaam van de zangeres Rihanna?", a: "Robyn" },
    { q: "Welk instrument bespeelt Lizzo?", a: "Dwarsfluit" },
    { q: "Wie is de vader van Miley Cyrus?", a: "Billy Ray Cyrus" },
    { q: "Welke Belgische band zong 'Wrong' en 'Mad About You'?", a: "Hooverphonic" },
    { q: "Hoeveel toetsen heeft een standaard piano?", a: "88" },
    { q: "Wie is de zanger van de hit 'Watermelon Sugar'?", a: "Harry Styles" },
    { q: "Welke Nederlandse zangeres deed mee aan het Songfestival met 'De Diepte'?", a: "S10" },
    { q: "Wat is de artiestennaam van Abel Tesfaye?", a: "The Weeknd" },
    { q: "Welke broers vormen een bekend Belgisch DJ-duo?", a: "Dimitri Vegas & Like Mike" },
    { q: "Wie zong de hit 'Purple Rain'?", a: "Prince" },
    { q: "Welk land won het Eurovisiesongfestival in 2021 (Måneskin)?", a: "Italië" },
    { q: "Hoeveel leden heeft de band Metallica?", a: "4" },
    { q: "Welke Vlaamse zangeres scoorde een hit met 'Ongewoon'?", a: "Pommelien Thijs" },
    { q: "Wat is de artiestennaam van de Belgische rapper Brihang?", a: "Boudy Verleye" },
    { q: "Welke zangeres staat bekend om haar paardenstaart (ponytail)?", a: "Ariana Grande" },
    { q: "Hoe heet de zanger van de Red Hot Chili Peppers?", a: "Anthony Kiedis" },
    { q: "Hoeveel seizoenen heeft de serie 'Friends'?", a: "10" },
    { q: "Wat is de naam van de groene baby in 'The Mandalorian'?", a: "Grogu" },
    { q: "Welke kleur pil kiest Neo in 'The Matrix'?", a: "Rood" },
    { q: "Hoe heet de fictieve taal in 'Avatar'?", a: "Na'vi" },
    { q: "Wie speelt de hoofdrol in 'Pirates of the Caribbean'?", a: "Johnny Depp" },
    { q: "Hoeveel films zijn er in de originele 'Lord of the Rings'-trilogie?", a: "3" },
    { q: "Welk videospel speelt zich af in 'Los Santos'?", a: "GTA V" },
    { q: "Wat is de naam van de prinses in de Super Mario-games?", a: "Peach" },
    { q: "Welke serie gaat over een scheikundeleraar die meth gaat koken?", a: "Breaking Bad" },
    { q: "Hoe heet de tijger in 'The Lion King' (de schurk)?", a: "Scar" },
    { q: "Wat is de hoogste kaartwaarde in een standaard kaartspel?", a: "Aas" },
    { q: "Welke acteur speelt 'Iron Man'?", a: "Robert Downey Jr." },
    { q: "Wat is de naam van de Pokémon mascotte (geel)?", a: "Pikachu" },
    { q: "In welke stad speelt de serie 'Sex and the City' zich af?", a: "New York" },
    { q: "Wat is het huisnummer van Sherlock Holmes in Baker Street?", a: "221B" },
    { q: "Wie is de maker van 'Star Wars'?", a: "George Lucas" },
    { q: "Hoeveel zijden heeft een dobbelsteen?", a: "6" },
    { q: "Welke streamingdienst heeft een logo met een plusje?", a: "Disney+" },
    { q: "Wat is de naam van de drakonische koningin in 'Game of Thrones'?", a: "Daenerys Targaryen" },
    { q: "Welke film won de Oscar voor Beste Film in 2024?", a: "Oppenheimer" },
    { q: "Wie spreekt de stem in van de ezel in 'Shrek' (Engels)?", a: "Eddie Murphy" },
    { q: "Wat is de naam van de pop in de horrorfilm 'Annabelle'?", a: "Annabelle" },
    { q: "In welk jaar kwam de eerste iPhone uit?", a: "2007" },
    { q: "Hoe heet de krant waar Peter Parker (Spiderman) voor werkt?", a: "Daily Bugle" },
    { q: "Wat is de naam van de dinosaurus-filmfranchise van Steven Spielberg?", a: "Jurassic Park" },
    { q: "Wie speelt de rol van 'Thor' in de Marvel-films?", a: "Chris Hemsworth" },
    { q: "Wat is de naam van de fictieve school in 'Sex Education'?", a: "Moordale" },
    { q: "Hoeveel levens heeft een kat volgens het gezegde?", a: "9" },
    { q: "Wat is de naam van de vampier in 'Twilight'?", a: "Edward Cullen" },
    { q: "Welke game gaat over het bouwen met blokken en overleven?", a: "Minecraft" },
    { q: "Wie is de broer van Mario?", a: "Luigi" },
    { q: "Wat is de naam van de pop in 'Squid Game'?", a: "Young-hee" },
    { q: "Welke acteur speelt de hoofdrol in 'Mission: Impossible'?", a: "Tom Cruise" },
    { q: "Hoe heet de oranje vis in 'Finding Nemo' (de vader)?", a: "Marlin" },
    { q: "Welke tovenaar is het schoolhoofd van Zweinstein?", a: "Albus Perkamentus" },
    { q: "Wat is de naam van de hond van Samson?", a: "Samson" },
    { q: "Hoe heet de burgemeester in 'Samson en Gert'?", a: "Modest" },
    { q: "Welke meidengroep bestond oorspronkelijk uit Karen, Kristel en Kathleen?", a: "K3" },
    { q: "Wat is de naam van de kabouter met de plopmuts?", a: "Plop" },
    { q: "Welke Studio 100-heldin is een superheldin in een strak pakje?", a: "Mega Mindy" },
    { q: "In welke jongerenserie speelden personages als Steve, Birgit en Zoë?", a: "W817" },
    { q: "Wat is de naam van de dansschool in de serie 'Spring'?", a: "Spring" },
    { q: "Wie presenteerde jarenlang 'De Mol' (de eerste seizoenen)?", a: "Michiel Devlieger" },
    { q: "Welk programma zoekt naar de 'Slimste Mens'?", a: "De Slimste Mens ter Wereld" },
    { q: "Wat is de naam van de kok in 'F.C. De Kampioenen' (na BTW)?", a: "Fernand Costermans" },
    { q: "Welke Vlaamse zender zendt 'Thuis' uit?", a: "VRT 1" },
    { q: "Wie is de presentator van 'De Mol' (huidige seizoenen)?", a: "Gilles De Coster" },
    { q: "Welke acteur speelt de rol van 'Het Varken' (Balthasar Boma)?", a: "Marijn Devalck" },
    { q: "Wat is de naam van het programma waarin Vlamingen huizen kopen in het buitenland zonder ze te zien?", a: "Blind Gekocht" },
    { q: "Wie won het eerste seizoen van 'Big Brother' in Vlaanderen (2000)?", a: "Steven Spillebeen" },
    { q: "Wat is de naam van de sidekick van Gert Verhulst in 'De Tafel van Gert'?", a: "Viktor Verhulst" },
    { q: "Welk dier is 'Bumba'?", a: "Clown" },
    { q: "Hoe heet de broer van Staf Coppens?", a: "Mathias Coppens" },
    { q: "Welke Vlaamse zangeres zingt 'Nooit meer naar huis'?", a: "Pommelien Thijs" },
    { q: "Wie presenteert 'Het Huis'?", a: "Eric Goens" },
    { q: "Wat is de naam van de bekende Vlaamse weerman die met pensioen ging in 2023?", a: "Frank Deboosere" },
    { q: "Welk sociaal netwerk was gigantisch populair in België voor Facebook?", a: "Netlog" },
    { q: "Hoe heet de hond van Kuifje?", a: "Bobbie" },
    { q: "Welke krant wordt uitgegeven op roze papier?", a: "De Tijd" },
    { q: "Wie presenteert 'De Verhulstjes'?", a: "De familie Verhulst" },
    { q: "Wat is de naam van de bekende YouTuber 'Average Rob'?", a: "Robert Van Impe" },
    { q: "Welke Vlaamse zanger staat bekend als 'Metejoor'?", a: "Joris van Rossem" },
    { q: "Hoeveel procent van de aarde is bedekt met water (ongeveer)?", a: "71" },
    { q: "Wat is het snelste landdier ter wereld?", a: "Jachtluipaard" },
    { q: "Hoeveel poten heeft een spin?", a: "8" },
    { q: "Wat is de chemische formule voor water?", a: "H2O" },
    { q: "Hoe heet de CEO van Tesla en SpaceX?", a: "Elon Musk" },
    { q: "Wat is de naam van de zoekmachine van Microsoft?", a: "Bing" },
    { q: "Hoeveel graden Celsius is het kookpunt van water?", a: "100" },
    { q: "Welk zoogdier kan vliegen?", a: "Vleermuis" },
    { q: "Hoeveel tanden heeft een volwassen mens (inclusief verstandskiezen)?", a: "32" },
    { q: "Wat is de grootste planeet in ons zonnestelsel?", a: "Jupiter" },
    { q: "Wat is de snelheid van het licht (afgerond in km/s)?", a: "300000" },
    { q: "Welk element heeft het symbool 'O'?", a: "Zuurstof" },
    { q: "Hoeveel harten heeft een octopus?", a: "3" },
    { q: "Wat is de naam van de virtuele assistent van Amazon?", a: "Alexa" },
    { q: "Wat betekent de afkorting 'AI'?", a: "Artificiële Intelligentie" },
    { q: "Welke planeet staat het dichtst bij de zon?", a: "Mercurius" },
    { q: "Hoeveel botten heeft een menselijk lichaam?", a: "206" },
    { q: "Wat is de naam van de pandemie die begon in 2019?", a: "COVID-19" },
    { q: "Welke bloedgroep is de universele donor?", a: "O negatief" },
    { q: "Wat is de hardste natuurlijke stof op aarde?", a: "Diamant" },
    { q: "Hoeveel chromosoomparen heeft een mens?", a: "23" },
    { q: "Wat is de naam van de eerste man op de maan?", a: "Neil Armstrong" },
    { q: "Wat is de naam van het bedrijf achter ChatGPT?", a: "OpenAI" },
    { q: "Welk dier is het symbool van het Wereld Natuur Fonds (WWF)?", a: "Reuzenpanda" },
    { q: "Wat is de grootste orgaan van het menselijk lichaam (oppervlakte)?", a: "Huid" },
    { q: "Welke planeet wordt de 'Avondster' genoemd?", a: "Venus" },
    { q: "Wie is de recordhouder van de meeste Olympische medailles aller tijden?", a: "Michael Phelps" },
    { q: "Hoeveel spelers staan er bij een basketbalteam op het veld?", a: "5" },
    { q: "Welke kleur trui draagt de leider in de Giro d'Italia?", a: "Roze" },
    { q: "In welk land werd het WK voetbal 2022 gehouden?", a: "Qatar" },
    { q: "Wat is de bijnaam van darter Michael van Gerwen?", a: "Mighty Mike" },
    { q: "Hoeveel minuten duurt een rugbywedstrijd?", a: "80" },
    { q: "Welke Belgische wielrenner wordt 'De Aerokogel van Schepdaal' genoemd?", a: "Remco Evenepoel" },
    { q: "Bij welke sport gebruik je een 'cue'?", a: "Snooker" },
    { q: "Welk nummer heeft Max Verstappen op zijn auto?", a: "1" },
    { q: "Hoe heet het stadion van FC Barcelona?", a: "Spotify Camp Nou" },
    { q: "Wie is de topscorer aller tijden van de Rode Duivels?", a: "Romelu Lukaku" },
    { q: "Welke tennisser wordt de 'King of Clay' (Gravelkoning) genoemd?", a: "Rafael Nadal" },
    { q: "Hoeveel gaten heeft een dartbord (de vakjes)?", a: "20" },
    { q: "Welke sport beoefent Nina Derwael?", a: "Turnen" },
    { q: "Hoeveel punten is een touchdown in American Football?", a: "6" },
    { q: "Welke Belgische club wordt 'The Great Old' genoemd?", a: "Royal Antwerp FC" },
    { q: "Wie won de Tour de France in 2020 en 2021?", a: "Tadej Pogačar" },
    { q: "Hoeveel spelers heeft een volleybalteam in het veld?", a: "6" },
    { q: "In welke stad speelt de voetbalclub Chelsea?", a: "Londen" },
    { q: "Wat is de maximale score in één beurt bij darten?", a: "180" },
    { q: "Welk land won het WK Vrouwenvoetbal in 2023?", a: "Spanje" },
    { q: "Wie is de huidige trainer van Manchester City (2024)?", a: "Pep Guardiola" },
    { q: "Wat is de basis van Guacamole?", a: "Avocado" },
    { q: "Welk merk produceert de 'Big Mac'?", a: "McDonald's" },
    { q: "Wat is de populairste frisdrank ter wereld?", a: "Coca-Cola" },
    { q: "Uit welk land komt IKEA?", a: "Zweden" },
    { q: "Wat is de naam van de bekende koffieketen uit Seattle?", a: "Starbucks" },
    { q: "Welke kleur heeft Chardonnay wijn?", a: "Wit" },
    { q: "Wat is het hoofdingrediënt van bier?", a: "Water" },
    { q: "Hoeveel sterren kan een restaurant maximaal krijgen van Michelin?", a: "3" },
    { q: "Wat is de naam van de Japanse noedelsoep?", a: "Ramen" },
    { q: "Welke vitamine halen we voornamelijk uit zonlicht?", a: "Vitamine D" },
    { q: "Wat is de naam van het beroemde energiedrankje met de slogan 'Geeft je vleugels'?", a: "Red Bull" },
    { q: "Welke noot zit er in marsepein?", a: "Amandel" },
    { q: "Wat is de naam van de bekende Belgische koekjesfabrikant uit Lembeke?", a: "Lotus" },
    { q: "Uit welk land komt de cocktail Caipirinha?", a: "Brazilië" },
    { q: "Wat is de duurste specerij ter wereld?", a: "Saffraan" },
    { q: "Wat is de naam van de saus gemaakt van basilicum, pijnboompitten en olijfolie?", a: "Pesto" },
    { q: "Welk fruit is het symbool van het techbedrijf Apple?", a: "Appel" },
    { q: "Wat is de naam van de vleesvervanger gemaakt van soja?", a: "Tofu" },
    { q: "Welke kleur heeft een Granny Smith appel?", a: "Groen" },
    { q: "Hoeveel milliliter zit er in een standaard blikje frisdrank?", a: "330" },
    { q: "Wat is de naam van de saus die traditioneel bij asperges wordt geserveerd?", a: "Hollandaise" },
    { q: "Welk land is de grootste producent van koffie?", a: "Brazilië" },
    { q: "Wat is het hoofdingrediënt van een omelet?", a: "Ei" },
    { q: "Welke stad is de hoofdstad van de Verenigde Staten?", a: "Washington D.C." },
    { q: "Hoeveel dagen heeft een schrikkeljaar?", a: "366" },
    { q: "Op welke datum valt Kerstdag?", a: "25 december" },
    { q: "Welke kleur krijg je als je blauw en geel mengt?", a: "Groen" },
    { q: "Hoeveel sterren staan er op de vlag van de EU?", a: "12" },
    { q: "Wat is de hoofdstad van Australië?", a: "Canberra" },
    { q: "Wie schreef 'Romeo en Julia'?", a: "William Shakespeare" },
    { q: "Wat is de officiële taal van Brazilië?", a: "Portugees" },
    { q: "Hoeveel seizoenen zijn er in een jaar?", a: "4" },
    { q: "Wat is de naam van de toren in Parijs?", a: "Eiffeltoren" },
    { q: "Welk land heeft de vorm van een laars?", a: "Italië" },
    { q: "In welk jaar vond de aanslag op de Twin Towers plaats?", a: "2001" },
    { q: "Wat is de valuta van Zwitserland?", a: "Zwitserse Frank" },
    { q: "Hoeveel provincies heeft België?", a: "10" },
    { q: "Wat is de naam van de huidige koning van België?", a: "Filip" },
    { q: "Welke kleur is de 'Black Box' in een vliegtuig?", a: "Oranje" },
    { q: "Wat is de naam van het beroemde festival in de woestijn van Nevada?", a: "Burning Man" },
    { q: "Hoe heet de vrouw van prins William?", a: "Kate Middleton" },
    { q: "Wat is de hoofdstad van Duitsland?", a: "Berlijn" },
    { q: "Hoeveel continenten zijn er?", a: "7" },
    { q: "Wat is de naam van de Romeinse god van de liefde?", a: "Cupido" },
    { q: "Welk land wordt het 'Land van de Rijzende Zon' genoemd?", a: "Japan" },
    { q: "Wat is de naam van de langste rivier in Afrika?", a: "Nijl" },
    { q: "Wie was de eerste zwarte president van de VS?", a: "Barack Obama" },
    { q: "Welke taal wordt het meest gesproken ter wereld (moedertaal)?", a: "Mandarijn" },
    { q: "Wat is de naam van de hoogste toren ter wereld (in Dubai)?", a: "Burj Khalifa" },
    { q: "Wat is de landcode van België?", a: "+32" },
    { q: "Hoeveel uur zit er in een week?", a: "168" },
    { q: "Wat is de naam van het schip dat zonk in 1912?", a: "Titanic" },
    { q: "Welk land heeft de meeste inwoners ter wereld (2023/2024)?", a: "India" },
    { q: "Welk speelgoed was een digitaal huisdier aan een sleutelhanger?", a: "Tamagotchi" },
    { q: "Wat is de naam van de onverwoestbare gsm van Nokia?", a: "Nokia 3310" },
    { q: "Welk besturingssysteem volgde Windows 98 op?", a: "Windows XP" },
    { q: "Wat was de naam van de videotheekketen die failliet ging?", a: "Blockbuster" },
    { q: "Welke kleur heeft Pac-Man?", a: "Geel" },
    { q: "Hoe heet de loodgieter in de game Donkey Kong?", a: "Mario" },
    { q: "Welke boyband zong 'I Want It That Way'?", a: "Backstreet Boys" },
    { q: "Wat is de voornaam van 'The Fresh Prince'?", a: "Will" },
    { q: "Welke film gaat over een park met dinosaurussen?", a: "Jurassic Park" },
    { q: "Wat is de naam van de leeuwenkoning?", a: "Simba" },
    { q: "Welk snoepje kon je om je nek dragen als ketting?", a: "Snoepketting" },
    { q: "Wat is de naam van de fee in Peter Pan?", a: "Tinkerbell" },
    { q: "Welke kleur hadden de smurfen?", a: "Blauw" },
    { q: "Wat is de naam van de oranje kat die lasagne eet?", a: "Garfield" },
    { q: "Welk bordspel draait om het kopen van straten?", a: "Monopoly" },
    { q: "Wat is de naam van de popgroep met Ginger, Sporty, Posh, Scary en Baby?", a: "Spice Girls" },
    { q: "In welk jaar was de millenniumwisseling?", a: "2000" },
    { q: "Wat is de naam van de beer van Mr. Bean?", a: "Teddy" },
    { q: "Welk automerk heeft een logo met vier ringen?", a: "Audi" },
    { q: "Wat is de naam van de bekendste pop ter wereld?", a: "Barbie" },
    { q: "Welke kleur is de 'M' van McDonald's?", a: "Geel" },
    { q: "Hoeveel wielen heeft een eenwieler?", a: "1" },
    { q: "Wat is de naam van de clown in 'It'?", a: "Pennywise" },
    { q: "Welke dag komt na dinsdag?", a: "Woensdag" },
    { q: "Wat is de naam van de magiër in Lord of the Rings?", a: "Gandalf" },
    { q: "Welk dier is Sonic?", a: "Egel" },
    { q: "Wat is de naam van de prinses in Zelda?", a: "Zelda" },
    { q: "Hoeveel millimeter is 1 meter?", a: "1000" },
    { q: "Wat is de naam van de vriend van Mickey Mouse?", a: "Minnie Mouse" },
    { q: "Welk fruit eet Pac-Man voor extra punten?", a: "Kers" },
    { q: "Wat is de naam van de auto-pilot functie van Tesla?", a: "Autopilot" },
    { q: "Wat is de afkorting voor 'World Wide Web'?", a: "WWW" },
    { q: "Welk bedrijf maakt de PlayStation?", a: "Sony" },
    { q: "Wat is de naam van de app waar je foto's na 24 uur verdwijnen?", a: "Snapchat" },
    { q: "Hoe noemt men een internetdagboek?", a: "Blog" },
    { q: "Wat is de naam van de cloudservice van Apple?", a: "iCloud" },
    { q: "Wat is de afkorting voor 'Electronic Dance Music'?", a: "EDM" },
    { q: "Welk platform is eigendom van Meta (naast Facebook)?", a: "Instagram" },
    { q: "Wat is de naam van de digitale munt die begon als een grap (hond)?", a: "Dogecoin" },
    { q: "Wat betekent de afkorting 'USB'?", a: "Universal Serial Bus" },
    { q: "Hoeveel karakters mocht een tweet oorspronkelijk hebben?", a: "140" },
    { q: "Wat is de naam van de browser van Google?", a: "Chrome" },
    { q: "Wat is de naam van de oprichter van Microsoft?", a: "Bill Gates" },
    { q: "Welke letter staat er op het logo van Superman?", a: "S" },
    { q: "Wat is de naam van de stem van de iPhone?", a: "Siri" },
    { q: "Wat is de naam van de streamingdienst voor gamers?", a: "Twitch" },
    { q: "Hoeveel procent batterij heb je als je telefoon 'vol' is?", a: "100" },
    { q: "Wat is de naam van de kabel om je tv aan te sluiten?", a: "HDMI" },
    { q: "Welk land heeft de extensie .nl?", a: "Nederland" },
    { q: "Wat is de naam van de virtuele wereld van Facebook?", a: "Metaverse" }
];