// quizdata_r3.js - Complete data voor Ronde 3 (Open Deur)
// Geoptimaliseerd: Geen vage termen, sterke associaties.

var STANDAARD_R3_POOL = [
    // --- 🇧🇪 & 🇳🇱 Bekende Vlamingen/Nederlanders & Cultuur ---
    { subject: "Manneken Pis", keywords: ["Brussel", "Plassen", "Standbeeld", "Kostuumpjes"] },
    { subject: "Atomium", keywords: ["Bollen", "Brussel", "Expo 58", "IJzerkristal"] },
    { subject: "Stromae", keywords: ["Alors on Danse", "Vlinderdas", "Maestro", "Formidable"] },
    { subject: "K3", keywords: ["Hanne, Marthe & Julia", "Regenboogjurkjes", "Meidengroep", "Studio 100"] },
    { subject: "Max Verstappen", keywords: ["Red Bull", "Formule 1", "Wereldkampioen", "Nederland"] },
    { subject: "Vincent van Gogh", keywords: ["Zonnebloemen", "Oor", "Schilder", "Sterrennacht"] },
    { subject: "Rembrandt", keywords: ["De Nachtwacht", "Schilder", "Licht en donker", "Gouden Eeuw"] },
    { subject: "Anne Frank", keywords: ["Achterhuis", "Dagboek", "Amsterdam", "Tweede Wereldoorlog"] },
    { subject: "Kuifje", keywords: ["Bobbie", "Kuif", "Hergé", "Reporter"] },
    { subject: "Suske en Wiske", keywords: ["Lambik", "Tante Sidonia", "Stripverhaal", "Rode kaft"] },
    { subject: "Kabouter Plop", keywords: ["Plopperdeplop", "Melkherberg", "Mutsen", "Koekjes"] },
    { subject: "Samson & Gert", keywords: ["Hond", "Bel", "Alberto", "Marlèneke"] },
    { subject: "De Efteling", keywords: ["Pretpark", "Sprookjesbos", "Langnek", "Holle Bolle Gijs"] },
    { subject: "Tomorrowland", keywords: ["Festival", "Boom", "Dance", "Mainstage"] },
    { subject: "Rode Duivels", keywords: ["Voetbal", "België", "Drietand", "Kevin De Bruyne"] },
    { subject: "Oranje", keywords: ["Nederland", "Voetbal", "Leeuw", "EK/WK"] },
    { subject: "Koning Filip", keywords: ["België", "Mathilde", "Elisabeth", "Saxofoon"] },
    { subject: "Willem-Alexander", keywords: ["Koning", "Maxima", "Piloot", "Nederland"] },
    { subject: "Friet", keywords: ["Mayonaise", "Aardappel", "Frituur", "Zout"] },
    { subject: "Chocolade", keywords: ["Praline", "Cacao", "België", "Reep"] },
    { subject: "Gouda", keywords: ["Kaas", "Wiel", "Geel", "Nederland"] },
    { subject: "Molen", keywords: ["Wind", "Wieken", "Malen", "Kinderdijk"] },
    { subject: "Tulpen", keywords: ["Bollen", "Keukenhof", "Lente", "Nederland"] },
    { subject: "Eddy Merckx", keywords: ["Kannibaal", "Wielrennen", "Gele trui", "Fiets"] },
    { subject: "Mathieu van der Poel", keywords: ["Veldrijden", "Wielrennen", "Adrie", "Alleskunner"] },
    { subject: "Arjen Robben", keywords: ["Voetbal", "Naar binnen kappen", "Bayern München", "Glasman"] },
    { subject: "Jacques Brel", keywords: ["Zanger", "Ne me quitte pas", "Brussel", "Chanson"] },
    { subject: "De Nachtwacht", keywords: ["Rembrandt", "Rijksmuseum", "Amsterdam", "Schilderij"] },
    { subject: "Delfts Blauw", keywords: ["Aardewerk", "Porselein", "Wit en blauw", "Tegeltjes"] },
    { subject: "Sinterklaas", keywords: ["Stoomboot", "Piet", "Mijter", "5 december/6 december"] },

    // --- 🎬 Film, TV & Streaming ---
    { subject: "James Bond", keywords: ["007", "Aston Martin", "Martini", "Licence to Kill"] },
    { subject: "Star Wars", keywords: ["Lightsaber", "Darth Vader", "The Force", "Yoda"] },
    { subject: "Harry Potter", keywords: ["Zweinstein", "Litteken", "Toverstok", "J.K. Rowling"] },
    { subject: "Titanic", keywords: ["IJsberg", "Leonardo DiCaprio", "Boot", "Rose"] },
    { subject: "The Lord of the Rings", keywords: ["Ring", "Frodo", "Gandalf", "Midden-Aarde"] },
    { subject: "Game of Thrones", keywords: ["Draken", "Winter is Coming", "Iron Throne", "Jon Snow"] },
    { subject: "Friends", keywords: ["Central Perk", "Rachel & Ross", "Smelly Cat", "New York"] },
    { subject: "Mickey Mouse", keywords: ["Oren", "Disney", "Minnie", "Pluto"] },
    { subject: "The Lion King", keywords: ["Simba", "Hakuna Matata", "Mufasa", "Disney"] },
    { subject: "Batman", keywords: ["Gotham", "Joker", "Batmobile", "Bruce Wayne"] },
    { subject: "Superman", keywords: ["Kryptonite", "S", "Rode cape", "Clark Kent"] },
    { subject: "Spider-Man", keywords: ["Web", "Peter Parker", "Spin", "Marvel"] },
    { subject: "Netflix", keywords: ["Bingewatchen", "Streaming", "Tudum", "Series"] },
    { subject: "Breaking Bad", keywords: ["Crystal Meth", "Walter White", "Scheikunde", "Camper"] },
    { subject: "Squid Game", keywords: ["Groen pak", "Rood licht groen licht", "Korea", "Geld"] },
    { subject: "La Casa de Papel", keywords: ["Maskers", "Rode overals", "Bella Ciao", "Professor"] },
    { subject: "Home Alone", keywords: ["Kevin", "Inbrekers", "Kerstmis", "Alleen"] },
    { subject: "Shrek", keywords: ["Groen", "Ezel", "Moeras", "Fiona"] },
    { subject: "Toy Story", keywords: ["Buzz Lightyear", "Woody", "Speelgoed", "Pixar"] },
    { subject: "Pirates of the Caribbean", keywords: ["Jack Sparrow", "Schip", "Johnny Depp", "Schat"] },
    { subject: "Avatar", keywords: ["Blauw", "Pandora", "James Cameron", "3D"] },
    { subject: "Jaws", keywords: ["Haai", "Spannende muziek", "Steven Spielberg", "Strand"] },
    { subject: "Jurassic Park", keywords: ["Dinosaurus", "T-Rex", "Amber", "Pretpark"] },
    { subject: "Forrest Gump", keywords: ["Run Forrest Run", "Chocolade", "Bankje", "Tom Hanks"] },
    { subject: "The Matrix", keywords: ["Rode of blauwe pil", "Neo", "Slow motion", "Keanu Reeves"] },
    { subject: "Frozen", keywords: ["Let it Go", "Elsa", "Sneeuwpop", "Anna"] },
    { subject: "Indiana Jones", keywords: ["Zweep", "Hoed", "Archeoloog", "Harrison Ford"] },
    { subject: "The Simpsons", keywords: ["Geel", "Homer", "Donut", "Springfield"] },
    { subject: "SpongeBob", keywords: ["Ananas", "Bikini Broek", "Krab", "Geel"] },
    { subject: "Tom & Jerry", keywords: ["Kat en Muis", "Vallen", "Jagen", "Cartoon"] },

    // --- 🎵 Muziek & Iconen ---
    { subject: "Michael Jackson", keywords: ["King of Pop", "Moonwalk", "Thriller", "Handschoen"] },
    { subject: "Elvis Presley", keywords: ["King of Rock", "Vetkuif", "Graceland", "Jailhouse Rock"] },
    { subject: "The Beatles", keywords: ["Liverpool", "Abbey Road", "John Lennon", "Paul McCartney"] },
    { subject: "Queen", keywords: ["Freddie Mercury", "Bohemian Rhapsody", "Snor", "Wembley"] },
    { subject: "Madonna", keywords: ["Queen of Pop", "Vogue", "Puntbeha", "Like a Virgin"] },
    { subject: "Beyoncé", keywords: ["Jay-Z", "Single Ladies", "Queen B", "Destiny's Child"] },
    { subject: "Taylor Swift", keywords: ["Ex-vriendjes", "Eras Tour", "Shake it Off", "Country/Pop"] },
    { subject: "Adele", keywords: ["Hello", "Londen", "Stem", "Ballades"] },
    { subject: "Ed Sheeran", keywords: ["Ros", "Gitaar", "Shape of You", "Loop station"] },
    { subject: "Eminem", keywords: ["Rap", "8 Mile", "Slim Shady", "Mom's Spaghetti"] },
    { subject: "Bob Marley", keywords: ["Reggae", "Dreadlocks", "Jamaica", "No Woman No Cry"] },
    { subject: "ABBA", keywords: ["Zweden", "Dancing Queen", "Eurovisiesongfestival", "Mamma Mia"] },
    { subject: "David Bowie", keywords: ["Ziggy Stardust", "Ogen", "Heroes", "Space Oddity"] },
    { subject: "Prince", keywords: ["Purple Rain", "Klein", "Kiss", "Symbool"] },
    { subject: "Rolling Stones", keywords: ["Mick Jagger", "Tong", "Satisfaction", "Keith Richards"] },
    { subject: "U2", keywords: ["Bono", "Ierland", "Zonnebril", "With or Without You"] },
    { subject: "Coldplay", keywords: ["Yellow", "Chris Martin", "Kleurrijk", "Piano"] },
    { subject: "Billie Eilish", keywords: ["Groen haar", "Bad Guy", "Fluisteren", "Zangeres"] },
    { subject: "Lady Gaga", keywords: ["Vleesjurk", "Poker Face", "A Star Is Born", "Monsters"] },
    { subject: "Metallica", keywords: ["Metal", "Gitaar", "Enter Sandman", "Headbangen"] },
    { subject: "Rihanna", keywords: ["Umbrella", "Barbados", "Make-up", "Super Bowl"] },
    { subject: "Elton John", keywords: ["Piano", "Brillen", "Rocket Man", "Lion King"] },
    { subject: "Britney Spears", keywords: ["Baby One More Time", "Blond", "Prinses", "Toxic"] },
    { subject: "Kurt Cobain", keywords: ["Nirvana", "Grunge", "Smells Like Teen Spirit", "Gitaar"] },
    { subject: "Mozart", keywords: ["Componist", "Wenen", "Piano", "Wonderkind"] },
    { subject: "Beethoven", keywords: ["Doof", "Symfonie", "Duitsland", "Piano"] },
    { subject: "Pavarotti", keywords: ["Opera", "Tenor", "Baard", "Nessun Dorma"] },

    // --- 🌍 Aardrijkskunde & Steden ---
    { subject: "Parijs", keywords: ["Eiffeltoren", "Louvre", "Liefde", "Seine"] },
    { subject: "Londen", keywords: ["Big Ben", "Rode bus", "Theems", "Buckingham Palace"] },
    { subject: "New York", keywords: ["Vrijheidsbeeld", "Yellow Cab", "Times Square", "Manhattan"] },
    { subject: "Rome", keywords: ["Colosseum", "Paus", "Vaticaan", "Pasta"] },
    { subject: "Egypte", keywords: ["Piramides", "Sfinx", "Farao", "Nijl"] },
    { subject: "China", keywords: ["Chinese Muur", "Panda", "Rijst", "Peking"] },
    { subject: "Japan", keywords: ["Sushi", "Tokio", "Kersenbloesem", "Anime"] },
    { subject: "Australië", keywords: ["Kangoeroe", "Sydney Opera House", "Outback", "Koala"] },
    { subject: "Brazilië", keywords: ["Carnaval", "Rio de Janeiro", "Voetbal", "Christusbeeld"] },
    { subject: "Venetië", keywords: ["Gondel", "Water", "Brug", "Italië"] },
    { subject: "Berlijn", keywords: ["Muur", "Duitsland", "Brandenburger Tor", "Techno"] },
    { subject: "Amsterdam", keywords: ["Grachten", "Fietsen", "Wallen", "Rijksmuseum"] },
    { subject: "Barcelona", keywords: ["Sagrada Familia", "Gaudi", "Strand", "Spanje"] },
    { subject: "Las Vegas", keywords: ["Casino", "Gokken", "Woestijn", "Neon"] },
    { subject: "Hollywood", keywords: ["Films", "Letters", "Sterren", "Los Angeles"] },
    { subject: "Mount Everest", keywords: ["Hoogste berg", "Himalaya", "Sneeuw", "Klimmen"] },
    { subject: "Antarctica", keywords: ["Zuidpool", "IJs", "Pinguïn", "Koud"] },
    { subject: "Amazone", keywords: ["Regenwoud", "Rivier", "Zuid-Amerika", "Natuur"] },
    { subject: "Niagara Falls", keywords: ["Waterval", "Water", "Canada/VS", "Boot"] },
    { subject: "Sahara", keywords: ["Woestijn", "Zand", "Kameel", "Droog"] },
    { subject: "Hawaii", keywords: ["Surfen", "Vulkaan", "Bloemenkrans", "Eiland"] },
    { subject: "IJsland", keywords: ["Geiser", "Vulkaan", "Noorderlicht", "Reykjavik"] },
    { subject: "Rusland", keywords: ["Wodka", "Moskou", "Rode Plein", "Poetin"] },
    { subject: "India", keywords: ["Taj Mahal", "Curry", "Bollywood", "Koe"] },
    { subject: "Griekenland", keywords: ["Akropolis", "Eilanden", "Ouzo", "Oudheid"] },

    // --- 👑 Geschiedenis & Politiek ---
    { subject: "Donald Trump", keywords: ["Make America Great Again", "Melania", "Twitter/X", "Toren"] },
    { subject: "Barack Obama", keywords: ["Yes We Can", "Eerste zwarte president", "Democraat", "Huis"] },
    { subject: "Nelson Mandela", keywords: ["Apartheid", "Zuid-Afrika", "Vrijheid", "Robbeneiland"] },
    { subject: "Adolf Hitler", keywords: ["Tweede Wereldoorlog", "Dictator", "Duitsland", "Snor"] },
    { subject: "Julius Caesar", keywords: ["Rome", "Keizer", "Brutus", "Latijn"] },
    { subject: "Napoleon", keywords: ["Waterloo", "Hand in jas", "Frankrijk", "Keizer"] },
    { subject: "Cleopatra", keywords: ["Egypte", "Slang", "Koningin", "Caesar"] },
    { subject: "Winston Churchill", keywords: ["Sigaar", "Engeland", "V-teken", "Oorlog"] },
    { subject: "John F. Kennedy", keywords: ["Moordaanslag", "Dallas", "President", "Marilyn Monroe"] },
    { subject: "Martin Luther King", keywords: ["I Have a Dream", "Burgerrechten", "Dominee", "Gelijkheid"] },
    { subject: "Albert Einstein", keywords: ["E=mc²", "Relativiteit", "Warrig haar", "Genie"] },
    { subject: "Neil Armstrong", keywords: ["Maan", "Astronaut", "Stap", "Apollo 11"] },
    { subject: "Columbus", keywords: ["Amerika", "Schip", "Ontdekkingsreiziger", "1492"] },
    { subject: "Berlijnse Muur", keywords: ["Val", "1989", "Oost en West", "Beton"] },
    { subject: "Titanic", keywords: ["1912", "Onzinkbaar", "White Star Line", "Ramp"] },
    { subject: "9/11", keywords: ["Twin Towers", "New York", "Vliegtuigen", "Terrorisme"] },
    { subject: "Franse Revolutie", keywords: ["Guillotine", "Marie Antoinette", "Bastille", "Vrijheid"] },
    { subject: "Vikingen", keywords: ["Schip", "Helm", "Noorden", "Plunderen"] },
    { subject: "Ridders", keywords: ["Harnas", "Zwaard", "Kasteel", "Middeleeuwen"] },
    { subject: "Piraten", keywords: ["Ooglapje", "Papegaai", "Schedel", "Schat"] },

    // --- ⚽ Sport & Spel ---
    { subject: "Voetbal", keywords: ["Bal", "Doelpunt", "Buitenspel", "Strafschop"] },
    { subject: "Tennis", keywords: ["Racket", "Wimbledon", "Gravel", "Ace"] },
    { subject: "Basketbal", keywords: ["Dunk", "NBA", "Michael Jordan", "Ring"] },
    { subject: "Wielrennen", keywords: ["Tour de France", "Gele trui", "Peloton", "Sprint"] },
    { subject: "Formule 1", keywords: ["Auto", "Circuit", "Pitstop", "Finishvlag"] },
    { subject: "Golf", keywords: ["Hole-in-one", "Club", "Green", "Tiger Woods"] },
    { subject: "Boksen", keywords: ["Ring", "Handschoenen", "Knock-out", "Muhammad Ali"] },
    { subject: "Darts", keywords: ["180", "Bord", "Pijl", "Bullseye"] },
    { subject: "Schaken", keywords: ["Koning", "Dame", "Schaakmat", "Bord"] },
    { subject: "Monopoly", keywords: ["Geld", "Gevangenis", "Hotel", "Start"] },
    { subject: "Poker", keywords: ["Kaarten", "Bluf", "Chips", "Full House"] },
    { subject: "Olympische Spelen", keywords: ["Ringen", "Vuur", "Goud", "Atleet"] },
    { subject: "Marathon", keywords: ["42 km", "Hardlopen", "Griekenland", "Uithouding"] },
    { subject: "Zwembad", keywords: ["Chloor", "Baan", "Duikplank", "Badmuts"] },
    { subject: "Schaatsen", keywords: ["IJs", "Elfstedentocht", "Sven Kramer", "Winter"] },
    { subject: "Messi", keywords: ["Argentinië", "FC Barcelona", "Gouden Bal", "Klein"] },
    { subject: "Ronaldo (CR7)", keywords: ["Portugal", "Siiuuu", "Nummer 7", "Spieren"] },
    { subject: "Usain Bolt", keywords: ["Snelste", "Jamaica", "Sprint", "Pose"] },
    { subject: "Serena Williams", keywords: ["Tennis", "Amerika", "Grand Slam", "Kracht"] },
    { subject: "Michael Jordan", keywords: ["Chicago Bulls", "23", "Space Jam", "Schoenen"] },

    // --- 🧬 Wetenschap, Natuur & Dieren ---
    { subject: "Dinosaurus", keywords: ["Uitgestorven", "Fossiel", "Meteoriet", "Jurassic"] },
    { subject: "Haai", keywords: ["Vin", "Tanden", "Zee", "Roofdier"] },
    { subject: "Leeuw", keywords: ["Manen", "Afrika", "Koning", "Brullen"] },
    { subject: "Olifant", keywords: ["Slurf", "Ivoor", "Geheugen", "Groot"] },
    { subject: "Giraffe", keywords: ["Nek", "Vlekken", "Tong", "Acacia"] },
    { subject: "Pinguïn", keywords: ["Waggelen", "Zuidpool", "Vis", "Vogel"] },
    { subject: "Kangaroo", keywords: ["Buidel", "Springen", "Australië", "Joey"] },
    { subject: "Panda", keywords: ["Bamboe", "China", "Zwart-wit", "Beer"] },
    { subject: "Hond", keywords: ["Blaffen", "Trouw", "Uitlaten", "Bot"] },
    { subject: "Kat", keywords: ["Miauwen", "Spinnen", "Muis", "Negen levens"] },
    { subject: "Bij", keywords: ["Honing", "Geel-zwart", "Steken", "Koningin"] },
    { subject: "Spin", keywords: ["Web", "Acht poten", "Bang", "Insect"] },
    { subject: "Maan", keywords: ["Eb en Vloed", "Nacht", "Krater", "Ruimte"] },
    { subject: "Zon", keywords: ["Ster", "Warmte", "Licht", "Zonnestelsel"] },
    { subject: "Mars", keywords: ["Rode planeet", "Aliens", "Rover", "Ruimte"] },
    { subject: "Water", keywords: ["H2O", "Drinken", "Zee", "Blauw"] },
    { subject: "Vuur", keywords: ["Heet", "Vlam", "Rook", "As"] },
    { subject: "Skelet", keywords: ["Botten", "Schedel", "Ribben", "Kalk"] },
    { subject: "Hersenen", keywords: ["Denken", "Grijs", "Geheugen", "Hoofd"] },
    { subject: "Hart", keywords: ["Pompen", "Bloed", "Slag", "Levensbelangrijk"] },
    { subject: "DNA", keywords: ["Erfelijk", "Code", "Genen", "Spiraal"] },
    { subject: "Zwaartekracht", keywords: ["Newton", "Vallen", "Appel", "Aantrekking"] },
    { subject: "Elektriciteit", keywords: ["Stopcontact", "Volt", "Licht", "Schok"] },
    { subject: "Vulkaan", keywords: ["Lava", "Uitbarsting", "As", "Magma"] },
    { subject: "Regenboog", keywords: ["Kleuren", "Pot goud", "Zon en regen", "Boog"] },
    
    // --- 🍔 Eten, Drinken & Objecten ---
    { subject: "Pizza", keywords: ["Italië", "Oven", "Mozzarella", "Rond"] },
    { subject: "Sushi", keywords: ["Rijst", "Rauwe vis", "Stokjes", "Wasabi"] },
    { subject: "Hamburger", keywords: ["Broodje", "Fastfood", "McDonald's", "Amerika"] },
    { subject: "Pasta", keywords: ["Spaghetti", "Italië", "Saus", "Deeg"] },
    { subject: "Koffie", keywords: ["Cafeïne", "Bonen", "Ochtend", "Starbucks"] },
    { subject: "Wijn", keywords: ["Druiven", "Rood of Wit", "Fles", "Alcohol"] },
    { subject: "Bier", keywords: ["Schuim", "Pintje", "Hop", "Brouwerij"] },
    { subject: "Cola", keywords: ["Prik", "Zwart", "Suiker", "Rood label"] },
    { subject: "IJsje", keywords: ["Hoorntje", "Smelten", "Zomer", "Bolletje"] },
    { subject: "Banaan", keywords: ["Krom", "Geel", "Fruit", "Schil"] },
    { subject: "Ei", keywords: ["Schaal", "Kip", "Omelet", "Dooier"] },
    { subject: "Brood", keywords: ["Bakker", "Sneetje", "Korst", "Beleg"] },
    { subject: "Kaas", keywords: ["Geel", "Gaten", "Melk", "Nederland"] },
    { subject: "Chocolade", keywords: ["Cacao", "Zoet", "Melk/Puur", "Reep"] },
    { subject: "Ui", keywords: ["Tranen", "Ringen", "Geur", "Snijden"] },
    { subject: "Knoflook", keywords: ["Teentje", "Geur", "Vampier", "Smaak"] },
    { subject: "Smartphone", keywords: ["App", "Touchscreen", "Bellen", "Batterij"] },
    { subject: "Auto", keywords: ["Stuur", "Wielen", "Motor", "Rijden"] },
    { subject: "Fiets", keywords: ["Trappers", "Ketting", "Bel", "Zadel"] },
    { subject: "Bed", keywords: ["Slapen", "Matras", "Deken", "Kussen"] },
    { subject: "Tandenborstel", keywords: ["Poetsen", "Tandpasta", "Badkamer", "Mond"] },
    { subject: "Sleutel", keywords: ["Slot", "Deur", "Metaal", "Bos"] },
    { subject: "Paraplu", keywords: ["Regen", "Droog", "Openklappen", "Handvat"] },
    { subject: "Bril", keywords: ["Glazen", "Zien", "Ogen", "Montuur"] },
    { subject: "Schoen", keywords: ["Veters", "Lopen", "Zool", "Voet"] },
    { subject: "Horloge", keywords: ["Tijd", "Pols", "Wijzers", "Tikken"] },
    { subject: "Boek", keywords: ["Lezen", "Bladzijden", "Verhaal", "Bibliotheek"] },
    { subject: "Laptop", keywords: ["Toetsenbord", "Scherm", "Draagbaar", "Computer"] },
    { subject: "Geld", keywords: ["Betalen", "Munten", "Briefjes", "Rijk"] },

    // --- 💻 Technologie & Merken ---
    { subject: "Apple", keywords: ["iPhone", "Steve Jobs", "MacBook", "Logo"] },
    { subject: "Google", keywords: ["Zoekmachine", "Maps", "Internet", "Antwoord"] },
    { subject: "Facebook", keywords: ["Mark Zuckerberg", "Blauw", "Vrienden", "Social Media"] },
    { subject: "Tesla", keywords: ["Elon Musk", "Elektrisch", "Auto", "Batterij"] },
    { subject: "Amazon", keywords: ["Pakketje", "Jeff Bezos", "Webwinkel", "Doos"] },
    { subject: "Coca-Cola", keywords: ["Rood", "Frisdrank", "Kerstman", "Recept"] },
    { subject: "McDonald's", keywords: ["Grote M", "Big Mac", "Frietjes", "Clown"] },
    { subject: "IKEA", keywords: ["Zweeds", "Geel-blauw", "Zelfbouw", "Gehaktballetjes"] },
    { subject: "Nike", keywords: ["Swoosh", "Just Do It", "Schoenen", "Sport"] },
    { subject: "LEGO", keywords: ["Blokjes", "Denemarken", "Bouwen", "Pijn aan voet"] },
    { subject: "PlayStation", keywords: ["Sony", "Controller", "Gamen", "Console"] },
    { subject: "Nintendo", keywords: ["Mario", "Switch", "Zelda", "Japan"] },
    { subject: "YouTube", keywords: ["Video's", "Vloggers", "Rood", "Abonneren"] },
    { subject: "Instagram", keywords: ["Foto's", "Filters", "Influencer", "Hartje"] },
    { subject: "TikTok", keywords: ["Dansjes", "Filmpjes", "Scrollen", "Viraal"] },
    { subject: "WhatsApp", keywords: ["Groen", "Chatten", "Berichten", "Bellen"] },
    { subject: "Wikipedia", keywords: ["Encyclopedie", "Kennis", "Online", "Gratis"] },
    { subject: "Spotify", keywords: ["Muziek", "Streamen", "Groen", "Playlist"] },
    
    // --- 🦸 Fictie & Personages ---
    { subject: "Sherlock Holmes", keywords: ["Detective", "Londen", "Watson", "Vergrootglas"] },
    { subject: "Dracula", keywords: ["Vampier", "Bloed", "Tanden", "Transsylvanië"] },
    { subject: "Frankenstein", keywords: ["Monster", "Groen", "Schroeven", "Dokter"] },
    { subject: "Tarzan", keywords: ["Jungle", "Jane", "Lianen", "Schreeuw"] },
    { subject: "Zorro", keywords: ["Zwaard", "Z", "Masker", "Paard"] },
    { subject: "Robin Hood", keywords: ["Stelen", "Rijken", "Armen", "Boogschutter"] },
    { subject: "Peter Pan", keywords: ["Vliegen", "Nooitgedachtland", "Kapitein Haak", "Kind"] },
    { subject: "Sneeuwwitje", keywords: ["Zeven dwergen", "Appel", "Spiegel", "Prinses"] },
    { subject: "Assepoester", keywords: ["Glazen muiltje", "Klok", "Middernacht", "Prins"] },
    { subject: "Pinokkio", keywords: ["Neus", "Liegen", "Hout", "Pop"] },
    { subject: "De Hulk", keywords: ["Groen", "Sterk", "Boos", "Marvel"] },
    { subject: "Wonder Woman", keywords: ["Lasso", "Vrouw", "Superheld", "DC"] },
    { subject: "Joker", keywords: ["Lach", "Slecht", "Batman", "Clown"] },
    { subject: "Darth Vader", keywords: ["Helm", "Ademhaling", "Father", "Zwart"] },
    { subject: "Homer Simpson", keywords: ["Doh!", "Bier", "Kaal", "Vader"] },
    { subject: "Mr. Bean", keywords: ["Onhandig", "Teddy", "Engels", "Mini"] },

    // --- 🛠️ Beroepen & Dagelijks ---
    { subject: "Dokter", keywords: ["Ziekenhuis", "Witte jas", "Stethoscoop", "Patiënt"] },
    { subject: "Politie", keywords: ["Blauw", "Boeien", "Sirene", "Boete"] },
    { subject: "Brandweer", keywords: ["Vuur", "Slang", "Ladderwagen", "Blussen"] },
    { subject: "Leraar", keywords: ["School", "Lesgeven", "Bord", "Huiswerk"] },
    { subject: "Piloot", keywords: ["Vliegtuig", "Cockpit", "Uniform", "Vliegen"] },
    { subject: "Kok", keywords: ["Eten", "Restaurant", "Muts", "Keuken"] },
    { subject: "Boer", keywords: ["Tractor", "Land", "Dieren", "Oogst"] },
    { subject: "Timmerman", keywords: ["Hout", "Hamer", "Zaag", "Bouwen"] },
    { subject: "Kapper", keywords: ["Schaar", "Haar", "Knippen", "Spiegel"] },
    { subject: "Astronaut", keywords: ["Ruimte", "Raket", "Pak", "Zweven"] },
    { subject: "Clown", keywords: ["Neus", "Circus", "Schmink", "Grappig"] },
    { subject: "Rechter", keywords: ["Hamer", "Rechtbank", "Toga", "Vonnis"] },
    
    // --- 🎲 Willekeurig & Abstract ---
    { subject: "Liefde", keywords: ["Hart", "Rood", "Valentijn", "Kus"] },
    { subject: "Oorlog", keywords: ["Wapens", "Vechten", "Soldaten", "Vrede"] },
    { subject: "Tijd", keywords: ["Klok", "Laat", "Uur", "Toekomst"] },
    { subject: "Geld", keywords: ["Euro", "Bank", "Rijk", "Sparen"] },
    { subject: "Vakantie", keywords: ["Reizen", "Zon", "Vrij", "Hotel"] },
    { subject: "School", keywords: ["Leren", "Boeken", "Examen", "Klas"] },
    { subject: "Verjaardag", keywords: ["Taart", "Kaarsjes", "Cadeau", "Feest"] },
    { subject: "Huwelijk", keywords: ["Ring", "Ja-woord", "Bruid", "Feest"] },
    { subject: "Kerstmis", keywords: ["Boom", "Cadeaus", "Jezus", "December"] },
    { subject: "Pasen", keywords: ["Eieren", "Haas", "Chocolade", "Lente"] },
    { subject: "Zomer", keywords: ["Warm", "Zon", "Strand", "Vakantie"] },
    { subject: "Winter", keywords: ["Koud", "Sneeuw", "Jas", "Donker"] },
    
    // --- 🎨 Kunst & Literatuur Extra ---
    { subject: "Mona Lisa", keywords: ["Glimlach", "Da Vinci", "Louvre", "Klein"] },
    { subject: "Shakespeare", keywords: ["Romeo & Julia", "Hamlet", "Engeland", "Schrijver"] },
    { subject: "Bijbel", keywords: ["Boek", "Kerk", "God", "Verhalen"] },
    { subject: "Sprookje", keywords: ["Er was eens", "Einde", "Fantasie", "Disney"] },
    { subject: "Poëzie", keywords: ["Gedicht", "Rijm", "Vers", "Dichter"] },
    { subject: "Theater", keywords: ["Podium", "Acteurs", "Gordijn", "Publiek"] },
    { subject: "Fotorolletje", keywords: ["Camera", "Ontwikkelen", "Oud", "Negatief"] },

    // --- 🦁 Dieren Extra ---
    { subject: "Kameel", keywords: ["Bulten", "Woestijn", "Water", "Dier"] },
    { subject: "Vleermuis", keywords: ["Ondersteboven", "Nacht", "Echo", "Batman"] },
    { subject: "Walvis", keywords: ["Grootste", "Zee", "Spuiten", "Zoogdier"] },
    { subject: "Kikker", keywords: ["Groen", "Kwak", "Springen", "Prins"] },
    { subject: "Vlinder", keywords: ["Rups", "Vleugels", "Kleurrijk", "Natuur"] },
    { subject: "Mier", keywords: ["Klein", "Sterk", "Kolonie", "Insect"] },
    { subject: "Uil", keywords: ["Oehoe", "Nacht", "Wijsheid", "Vogel"] },
    
    // --- 🌍 Landen & Steden Extra ---
    { subject: "Turkije", keywords: ["Istanbul", "Kebab", "Vakantie", "Moskee"] },
    { subject: "Marokko", keywords: ["Couscous", "Atlasgebergte", "Munt", "Kamelen"] },
    { subject: "Zwitserland", keywords: ["Bergen", "Chocolade", "Horloges", "Neutraal"] },
    { subject: "Ierland", keywords: ["Groen", "Guinness", "Pub", "Eiland"] },
    { subject: "Mexico", keywords: ["Taco", "Sombrero", "Pittig", "Spaans"] },
    { subject: "Canada", keywords: ["Esdoornblad", "Koud", "Natuur", "Engels/Frans"] },
    { subject: "Brussel", keywords: ["Hoofdstad", "Europa", "Wafels", "Manneken Pis"] },
    { subject: "Antwerpen", keywords: ["Diamant", "Schelde", "Haven", "Zoo"] },
    
    // --- 🔬 Techniek & Wetenschap Extra ---
    { subject: "Robot", keywords: ["Metaal", "Toekomst", "Programmeren", "Kunstmatig"] },
    { subject: "Microscoop", keywords: ["Vergroten", "Klein", "Laboratorium", "Onderzoek"] },
    { subject: "Telescoop", keywords: ["Sterren", "Kijken", "Ruimte", "Lens"] },
    { subject: "Raket", keywords: ["Lancering", "Ruimte", "NASA", "Vuur"] },
    { subject: "Satelliet", keywords: ["Baan", "Communicatie", "Ruimte", "GPS"] },
    { subject: "Batterij", keywords: ["Plus en min", "Energie", "Opladen", "Leeg"] },
    
    // --- 🎵 Muziekinstrumenten ---
    { subject: "Gitaar", keywords: ["Snaren", "Spelen", "Rock", "Hout"] },
    { subject: "Piano", keywords: ["Toetsen", "Zwart-wit", "Vleugel", "Muziek"] },
    { subject: "Drumstel", keywords: ["Stokken", "Slaan", "Ritme", "Lawaai"] },
    { subject: "Viool", keywords: ["Strijkstok", "Kin", "Orkest", "Klassiek"] },
    { subject: "Trompet", keywords: ["Blazen", "Koper", "Jazz", "Goud"] },
    { subject: "Saxofoon", keywords: ["Jazz", "Blazen", "Krom", "Goud"] },

    // --- 🏠 In Huis Extra ---
    { subject: "Wasmachine", keywords: ["Draaien", "Kleren", "Zeep", "Water"] },
    { subject: "Koelkast", keywords: ["Koud", "Eten", "Bewaren", "Keuken"] },
    { subject: "Stofzuiger", keywords: ["Zuigen", "Lawaai", "Schoonmaken", "Huis"] },
    { subject: "Televisie", keywords: ["Kijken", "Afstandsbediening", "Scherm", "Zappen"] },
    { subject: "Kaars", keywords: ["Vlam", "Licht", "Was", "Gezellig"] },
    { subject: "Spiegel", keywords: ["Reflectie", "Zelf", "Glas", "Badkamer"] },
    { subject: "Kussen", keywords: ["Zacht", "Slapen", "Bed", "Hoofd"] },

    // --- 👗 Kleding ---
    { subject: "Jeans", keywords: ["Broek", "Blauw", "Denim", "Zakken"] },
    { subject: "T-shirt", keywords: ["Kort", "Katoen", "Dragen", "Kleding"] },
    { subject: "Jas", keywords: ["Buiten", "Warm", "Rits", "Winter"] },
    { subject: "Sokken", keywords: ["Voeten", "Twee", "Schoenen", "Wassen"] },
    { subject: "Hoed", keywords: ["Hoofd", "Rand", "Zon", "Dragen"] },
    { subject: "Handschoenen", keywords: ["Winter", "Vingers", "Warm", "Handen"] },
    { subject: "Riem", keywords: ["Broek", "Leder", "Gespen", "Middel"] }
];