// quizdata_r3.js - Complete data voor Ronde 3 (Open Deur)

const STANDAARD_R3_POOL = [
    // --- Oorspronkelijke 20 Items ---
    { subject: "Tom Cruise", keywords: ["Acteur", "Mission Impossible", "Top Gun", "Scientology"] },
    { subject: "Marilyn Monroe", keywords: ["Actrice", "Blond", "Kennedy", "Jaren 50"] },
    { subject: "Leonardo DiCaprio", keywords: ["Acteur", "Titanic", "Oscar", "Wolf of Wall Street"] },
    { subject: "Netflix", keywords: ["Streamen", "Series", "Film", "Abonnement"] },
    { subject: "Michael Jackson", keywords: ["King of Pop", "Moonwalk", "Thriller", "Neverland"] },
    { subject: "Beatles", keywords: ["John Lennon", "Liverpool", "Muziek", "Yellow Submarine"] },
    { subject: "Elvis Presley", keywords: ["Zanger", "Rock n Roll", "Jailhouse Rock", "Graceland"] },
    { subject: "Albert Einstein", keywords: ["E=mc²", "Relativiteit", "Duitsland", "Nobelprijs"] },
    { subject: "Charles Darwin", keywords: ["Evolutie", "Bioloog", "Galapagos", "The Origin of Species"] },
    { subject: "Sigmund Freud", keywords: ["Psychoanalyse", "Oostenrijk", "Dromen", "Psycholoog"] },
    { subject: "Stephen Hawking", keywords: ["Fysicus", "Zwarte Gaten", "ALS", "Rolstoel"] },
    { subject: "Mona Lisa", keywords: ["Da Vinci", "Schilderij", "Louvre", "Glimlach"] },
    { subject: "De Zonnebloem", keywords: ["Plant", "Geel", "Olie", "Van Gogh"] },
    { subject: "William Shakespeare", keywords: ["Schrijver", "Engeland", "Romeo en Julia", "Hamlet"] },
    { subject: "Rembrandt", keywords: ["Schilder", "De Nachtwacht", "Nederland", "Gouden Eeuw"] },
    { subject: "Picasso", keywords: ["Schilder", "Spanje", "Kubisme", "Guernica"] },
    { subject: "Donald Trump", keywords: ["President", "Amerika", "Republikein", "Miljardair"] },
    { subject: "Koning Filip", keywords: ["België", "Koning", "Mathilde", "Troonopvolger"] },
    { subject: "Willem-Alexander", keywords: ["Nederland", "Koning", "Maxima", "Troonopvolger"] },
    { subject: "Angela Merkel", keywords: ["Duitsland", "Kanselier", "Politiek", "CDU"] },

    // --- 🎬 Film & TV (30x) ---
    { subject: "Star Wars", keywords: ["Jedi", "Darth Vader", "Lightsaber", "George Lucas"] },
    { subject: "Game of Thrones", keywords: ["Draken", "Winter", "Westeros", "IJzeren Troon"] },
    { subject: "Harry Potter", keywords: ["Zweinstein", "Tovenaar", "Dreuzel", "Voldemort"] },
    { subject: "The Matrix", keywords: ["Neo", "Rode pil", "Kogels ontwijken", "Keanu Reeves"] },
    { subject: "SpongeBob", keywords: ["Ananas", "Patrick", "Bikini Bottom", "Krabs"] },
    { subject: "Titanic", keywords: ["Zinken", "DiCaprio", "IJsberg", "1912"] },
    { subject: "The Big Bang Theory", keywords: ["Sitcom", "Sheldon", "Nerd", "Wetenschapper"] },
    { subject: "Breaking Bad", keywords: ["Walter White", "Meth", "New Mexico", "Leraar"] },
    { subject: "Friends", keywords: ["Central Perk", "New York", "Sitcom", "Ross, Rachel, Monica, Chandler, Joey, Phoebe"] },
    { subject: "Marvel", keywords: ["Superhelden", "Avengers", "Thanos", "Stripboeken"] },
    { subject: "DC Comics", keywords: ["Batman", "Superman", "Gotham", "Justice League"] },
    { subject: "James Bond", keywords: ["007", "Martini", "MI6", "Aston Martin"] },
    { subject: "The Lord of the Rings", keywords: ["Hobbit", "Tolkien", "Ring", "Midden-Aarde"] },
    { subject: "Toy Story", keywords: ["Woody", "Buzz Lightyear", "Pixar", "Speelgoed"] },
    { subject: "The Godfather", keywords: ["Maffia", "Corleone", "Marlon Brando", "Italië"] },
    { subject: "Frozen", keywords: ["Elsa", "Disney", "IJs", "Olaf"] },
    { subject: "Pulp Fiction", keywords: ["Tarantino", "Dans", "Koffer", "Samuel L. Jackson"] },
    { subject: "The Simpsons", keywords: ["Geel", "Springfield", "Homer", "Duff Bier"] },
    { subject: "Shrek", keywords: ["Oger", "Ezel", "Moeras", "Fiona"] },
    { subject: "Pirates of the Caribbean", keywords: ["Jack Sparrow", "Piraat", "Johnny Depp", "Zeeslag"] },
    { subject: "Forrest Gump", keywords: ["Tom Hanks", "Rennen", "Chocolade", "Vietnam"] },
    { subject: "Jaws", keywords: ["Haai", "Zee", "Steven Spielberg", "Muziek"] },
    { subject: "Doctor Who", keywords: ["TARDIS", "Tijdreizen", "Alien", "Britse serie"] },
    { subject: "Peaky Blinders", keywords: ["Birmingham", "Bende", "Hoeden", "Cillian Murphy"] },
    { subject: "Squid Game", keywords: ["Zuid-Korea", "Rood en groen", "Spellen", "Netflix"] },
    { subject: "Rick and Morty", keywords: ["Animatie", "Wetenschap", "Dimensionaal", "Gekke wetenschapper"] },
    { subject: "Black Mirror", keywords: ["Technologie", "Dystopie", "Toekomst", "Britse serie"] },
    { subject: "Interstellar", keywords: ["Ruimte", "Tijd", "Wormgat", "Christopher Nolan"] },
    { subject: "The Silence of the Lambs", keywords: ["Hannibal Lecter", "Clarice", "Moordenaar", "Anthony Hopkins"] },
    { subject: "Jurassic Park", keywords: ["Dino's", "Eiland", "Steven Spielberg", "Mosquito"] },

    // --- 🎵 Muziek & Artiesten (30x) ---
    { subject: "Queen", keywords: ["Freddie Mercury", "Bohemian Rhapsody", "Rock", "Gitaar"] },
    { subject: "Madonna", keywords: ["Queen of Pop", "Material Girl", "Blond", "Verenigde Staten"] },
    { subject: "Beyoncé", keywords: ["Queen B", "Single Ladies", "Destiny's Child", "Jay-Z"] },
    { subject: "Adele", keywords: ["Zangeres", "Hello", "Groot-Brittannië", "Grammy"] },
    { subject: "Ed Sheeran", keywords: ["Singer-songwriter", "Gitaar", "Rood haar", "Engels"] },
    { subject: "Taylor Swift", keywords: ["Pop", "Country", "Fearless", "Amerikaans"] },
    { subject: "Bob Dylan", keywords: ["Tekstdichter", "Nobelprijs", "Folk", "Amerikaans"] },
    { subject: "Lady Gaga", keywords: ["Vleesjurk", "Pop", "Excentriek", "Poker Face"] },
    { subject: "Pink Floyd", keywords: ["Progressieve rock", "The Wall", "Dark Side of the Moon", "Britse band"] },
    { subject: "Metallica", keywords: ["Metal", "San Francisco", "Gitaar", "Heavy"] },
    { subject: "Rihanna", keywords: ["Barbados", "Fenty", "Pop", "Umbrella"] },
    { subject: "Coldplay", keywords: ["Britse band", "Chris Martin", "Yellow", "Pop-rock"] },
    { subject: "U2", keywords: ["Ierse band", "Bono", "One", "Rock"] },
    { subject: "Whitney Houston", keywords: ["Zangeres", "Bodyguard", "I Will Always Love You", "Amerikaans"] },
    { subject: "Prince", keywords: ["Paars", "Zanger", "Gitaar", "Purple Rain"] },
    { subject: "AC/DC", keywords: ["Australië", "Hard Rock", "Angus Young", "Back in Black"] },
    { subject: "Katy Perry", keywords: ["Pop", "Californië Gurls", "Zangeres", "Kleurrijk"] },
    { subject: "Elton John", keywords: ["Piano", "Groot-Brittannië", "Rocket Man", "Bril"] },
    { subject: "Dua Lipa", keywords: ["Pop", "Britse zangeres", "New Rules", "Future Nostalgia"] },
    { subject: "Kendrick Lamar", keywords: ["Rap", "Compton", "Pulitzerprijs", "Hiphop"] },
    { subject: "Eminem", keywords: ["Witte rapper", "Detroit", "Slim Shady", "8 Mile"] },
    { subject: "Sting", keywords: ["The Police", "Zanger", "Engels", "Bass"] },
    { subject: "Aretha Franklin", keywords: ["Queen of Soul", "Respect", "Amerikaans", "Zangeres"] },
    { subject: "David Bowie", keywords: ["Ziggy Stardust", "Britse zanger", "Kameleon", "Space Oddity"] },
    { subject: "ABBA", keywords: ["Zweeds", "Waterloo", "Mamma Mia", "Pop"] },
    { subject: "Rolling Stones", keywords: ["Mick Jagger", "Britse band", "Rock", "Tong logo"] },
    { subject: "Ariana Grande", keywords: ["Zangeres", "Hoge stem", "Pop", "Amerikaans"] },
    { subject: "Edith Piaf", keywords: ["Franse zangeres", "Mus", "La Vie en Rose", "Parijs"] },
    { subject: "Justin Bieber", keywords: ["Canadees", "Pop", "Baby", "Zanger"] },
    { subject: "Mariah Carey", keywords: ["Hoge noten", "Kerst", "Zangeres", "Amerikaans"] },

    // --- 🔬 Wetenschap & Uitvindingen (30x) ---
    { subject: "Isaac Newton", keywords: ["Zwaartekracht", "Appel", "Engels", "Wetten"] },
    { subject: "Galileo Galilei", keywords: ["Telescoop", "Italië", "Astronoom", "Kerk"] },
    { subject: "Marie Curie", keywords: ["Radioactiviteit", "Polonium", "Nobelprijs", "Vrouw"] },
    { subject: "Nikola Tesla", keywords: ["Elektriciteit", "Wisselstroom", "Servië", "Genie"] },
    { subject: "Thomas Edison", keywords: ["Gloeilamp", "Uitvinder", "Amerikaans", "Phonograaf"] },
    { subject: "Johannes Gutenberg", keywords: ["Drukpers", "Duitsland", "Boeken", "Uitvinder"] },
    { subject: "Alexander Fleming", keywords: ["Penicilline", "Schotland", "Nobelprijs", "Bacteriën"] },
    { subject: "Louis Pasteur", keywords: ["Pasteuriseren", "Frans", "Microbiologie", "Rabiës"] },
    { subject: "Archimedes", keywords: ["Oud-Grieks", "Wiskundige", "Hevel", "Eureka"] },
    { subject: "Copernicus", keywords: ["Pools", "Zon centraal", "Astronoom", "Heliocentrisch"] },
    { subject: "DNA", keywords: ["Dubbele Helix", "Genen", "Erfelijkheid", "Watson & Crick"] },
    { subject: "Zwaartekracht", keywords: ["Massa", "Aantrekking", "Valt", "Newton"] },
    { subject: "Relativiteit", keywords: ["Tijd", "Snelheid van licht", "Einstein", "Theorie"] },
    { subject: "Fotosynthese", keywords: ["Planten", "Zonlicht", "Zuurstof", "Groen"] },
    { subject: "Koolstof", keywords: ["Element", "C", "Diamant", "Leven"] },
    { subject: "Zuurstof", keywords: ["Gas", "Ademen", "O2", "Water"] },
    { subject: "Internet", keywords: ["WWW", "Netwerk", "Wereldwijd", "Communicatie"] },
    { subject: "Vaccin", keywords: ["Edward Jenner", "Immuun", "Ziekte", "Prik"] },
    { subject: "Stoommachine", keywords: ["James Watt", "Industrie", "Hitte", "Beweging"] },
    { subject: "Radiogolf", keywords: ["Electromagnetisch", "Zender", "Communicatie", "Marconi"] },
    { subject: "De Pil", keywords: ["Anticonceptie", "Hormonen", "Vrouw", "Jaren '60"] },
    { subject: "Microscoop", keywords: ["Vergroten", "Klein", "Leeuwenhoek", "Wetenschap"] },
    { subject: "Telescoop", keywords: ["Sterren", "Verre", "Galileo", "Kijken"] },
    { subject: "Luchtband", keywords: ["Wiel", "Rubber", "Oplossing", "John Boyd Dunlop"] },
    { subject: "Pen", keywords: ["Schrijven", "Inkt", "Bic", "László Bíró"] },
    { subject: "Anesthesie", keywords: ["Pijnloos", "Operatie", "Verdoven", "Ether"] },
    { subject: "Thermometer", keywords: ["Temperatuur", "Kwik", "Koorts", "Meting"] },
    { subject: "GPS", keywords: ["Satelliet", "Navigatie", "Locatie", "Kaart"] },
    { subject: "Batterij", keywords: ["Alessandro Volta", "Energie", "Stroom", "Opslag"] },
    { subject: "Laser", keywords: ["Licht", "Gebundeld", "Chirurgie", "Hologram"] },

    // --- 🌍 Geografie: Landen (30x) ---
    { subject: "China", keywords: ["Grote Muur", "Peking", "Volk", "Rijst"] },
    { subject: "India", keywords: ["Taj Mahal", "Curry", "Mumbai", "Heilig"] },
    { subject: "Brazilië", keywords: ["Voetbal", "Rio de Janeiro", "Carnaval", "Portugees"] },
    { subject: "Rusland", keywords: ["Grootste", "Kremlin", "Siberië", "Wodka"] },
    { subject: "Frankrijk", keywords: ["Eiffeltoren", "Parijs", "Wijn", "Baguette"] },
    { subject: "Duitsland", keywords: ["Oktoberfest", "Berlijn", "Auto", "Kanselier"] },
    { subject: "Italië", keywords: ["Rome", "Pizza", "Colosseum", "Laars"] },
    { subject: "Japan", keywords: ["Tokio", "Sushi", "Yen", "Technologie"] },
    { subject: "Egypte", keywords: ["Piramide", "Nijl", "Farao", "Caïro"] },
    { subject: "Zuid-Afrika", keywords: ["Nelson Mandela", "Kaapstad", "Apartheid", "Goud"] },
    { subject: "Mexico", keywords: ["Tequila", "Azteken", "Mexico-Stad", "Spaans"] },
    { subject: "Canada", keywords: ["Esdoornblad", "Groot", "Ottawa", "Frans/Engels"] },
    { subject: "Australië", keywords: ["Kangoeroe", "Sydney", "Down Under", "Groot Barrièrerif"] },
    { subject: "Zwitserland", keywords: ["Alpen", "Chocolade", "Neutrale", "Klokken"] },
    { subject: "Griekenland", keywords: ["Olympos", "Apostolos", "Mythologie", "Akropolis"] },
    { subject: "Ierland", keywords: ["Groen", "Dublin", "Guinness", "Keltisch"] },
    { subject: "Polen", keywords: ["Warschau", "Katholiek", "Chopin", "Slavisch"] },
    { subject: "Noorwegen", keywords: ["Fjord", "Oslo", "Olie", "Scandinavië"] },
    { subject: "Argentinië", keywords: ["Tango", "Buenos Aires", "Messi", "Zuid-Amerika"] },
    { subject: "Turkije", keywords: ["Istanbul", "Ottomaans", "Ankara", "Bosporus"] },
    { subject: "Thailand", keywords: ["Boeddha", "Bangkok", "Rijst", "Zuid-Oost Azië"] },
    { subject: "Peru", keywords: ["Machu Picchu", "Lima", "Andes", "Inca"] },
    { subject: "Nieuw-Zeeland", keywords: ["Kiwi", "Wellington", "Maori", "Rugby"] },
    { subject: "Zuid-Korea", keywords: ["K-Pop", "Seoel", "Technologie", "DMZ"] },
    { subject: "Portugal", keywords: ["Lissabon", "Fado", "Zeevaart", "Iberisch"] },
    { subject: "Oostenrijk", keywords: ["Wenen", "Mozart", "Alpen", "Habsburg"] },
    { subject: "Cuba", keywords: ["Havana", "Sigaren", "Fidel Castro", "Caribisch"] },
    { subject: "Marokko", keywords: ["Rabat", "Atlas", "Koning", "Noord-Afrika"] },
    { subject: "Hongarije", keywords: ["Boedapest", "Donau", "Puszta", "Goulash"] },
    { subject: "IJsland", keywords: ["Geiser", "Reykjavik", "Vulkaan", "Koud"] },

    // --- 🎭 Fictieve Personages (30x) ---
    { subject: "Sherlock Holmes", keywords: ["Detective", "Londen", "Watson", "Pijp"] },
    { subject: "SpongeBob", keywords: ["Geel", "Ananas", "Patrick", "Bikini Bottom"] },
    { subject: "Superman", keywords: ["Krypton", "Rood-blauwe", "Clark Kent", "Vliegen"] },
    { subject: "Batman", keywords: ["Vleermuis", "Gotham", "Joker", "Bruce Wayne"] },
    { subject: "Mickey Mouse", keywords: ["Disney", "Oren", "Minnie", "Amerikaans"] },
    { subject: "Pikachu", keywords: ["Pokémon", "Geel", "Elektrisch", "Staart"] },
    { subject: "Homer Simpson", keywords: ["Donut", "Springfield", "Duff", "Geel"] },
    { subject: "Kuifje", keywords: ["Reporter", "Haddock", "Wit haar", "België"] },
    { subject: "Winnie de Poeh", keywords: ["Honing", "Beer", "Biggetje", "100 Bunderbos"] },
    { subject: "Dracula", keywords: ["Vampier", "Transsylvanië", "Bloed", "Graaf"] },
    { subject: "Sinterklaas", keywords: ["Schoen", "Spanje", "Stoomboot", "Paard"] },
    { subject: "Robin Hood", keywords: ["Boogschutter", "Sherwood", "Rijk/Arm", "Engeland"] },
    { subject: "Peter Pan", keywords: ["Nooitgedachtland", "Vliegen", "Tinkerbell", "Jongen"] },
    { subject: "Gandalf", keywords: ["Tolkien", "Tovenaar", "Baard", "Grijze"] },
    { subject: "Vito Corleone", keywords: ["Maffia", "The Godfather", "Italiaans", "Don"] },
    { subject: "Tarzan", keywords: ["Jungle", "Lianen", "Apen", "Mensenkind"] },
    { subject: "Captain Jack Sparrow", keywords: ["Piraat", "Johnny Depp", "Krakken", "Vloek"] },
    { subject: "Frodo Balings", keywords: ["Hobbit", "Ring", "Midden-Aarde", "Gimli"] },
    { subject: "Joker", keywords: ["Glimlach", "Aartsvijand", "Paars", "Batman"] },
    { subject: "Optimus Prime", keywords: ["Transformer", "Truck", "Robot", "Leider"] },
    { subject: "Godzilla", keywords: ["Kaiju", "Japan", "Monster", "Atoom"] },
    { subject: "De Smurfen", keywords: ["Blauw", "Paddestoel", "Gargamel", "België"] },
    { subject: "Dory", keywords: ["Vis", "Vergeetachtig", "Finding Nemo", "Blauw/Geel"] },
    { subject: "Cruella De Vil", keywords: ["Bont", "Dalmatiërs", "Schurk", "Disney"] },
    { subject: "Don Quichot", keywords: ["Spaanse", "Windmolen", "Roman", "Ridder"] },
    { subject: "Pinokkio", keywords: ["Neus", "Hout", "Leugen", "Pop"] },
    { subject: "Wickie de Viking", keywords: ["Jongen", "Viking", "Helm", "Slim"] },
    { subject: "Popeye", keywords: ["Zeeman", "Spinazie", "Pijp", "Olijf"] },
    { subject: "King Kong", keywords: ["Aap", "Eiland", "Groot", "Empire State"] },
    { subject: "Aladdin", keywords: ["Lamp", "Geest", "Prinses", "Disney"] },

    // --- 🍔 Eten & Drinken (30x) ---
    { subject: "Pizza", keywords: ["Italië", "Rond", "Oven", "Kaas"] },
    { subject: "Pasta", keywords: ["Deeg", "Italiaans", "Spaghetti", "Saus"] },
    { subject: "Chocolade", keywords: ["Cacao", "Zwitserland/België", "Zoet", "Bruin"] },
    { subject: "Koffie", keywords: ["Boontje", "Cafeïne", "Ochtend", "Zwart"] },
    { subject: "Bier", keywords: ["Alcohol", "Gerst", "Schuim", "Koud"] },
    { subject: "Wijn", keywords: ["Druiven", "Rood/Wit", "Fles", "Frankrijk"] },
    { subject: "Sushi", keywords: ["Rijst", "Japan", "Vis", "Rauw"] },
    { subject: "Hamburger", keywords: ["Broodje", "Vlees", "Amerika", "Fastfood"] },
    { subject: "Friet", keywords: ["Aardappel", "Geel", "België/Nederland", "Frituur"] },
    { subject: "Taco", keywords: ["Mexico", "Mais", "Gevuld", "Pittig"] },
    { subject: "Kip", keywords: ["Vogel", "Ei", "Geroosterd", "Gevogelte"] },
    { subject: "Kaas", keywords: ["Melk", "Gat", "Gouds", "Boterham"] },
    { subject: "IJs", keywords: ["Koud", "Zoet", "Zomer", "Bolletjes"] },
    { subject: "Honing", keywords: ["Bijen", "Zoet", "Stroperig", "Geel"] },
    { subject: "Brood", keywords: ["Graan", "Bakker", "Snijden", "Ontbijt"] },
    { subject: "Thee", keywords: ["Warm", "Blad", "Water", "Engeland"] },
    { subject: "Rijst", keywords: ["Azië", "Korrel", "Water", "Wok"] },
    { subject: "Soep", keywords: ["Warm", "Vloeibaar", "Lepel", "Voorgerecht"] },
    { subject: "Olijf", keywords: ["Boom", "Groen/Zwart", "Mediterraan", "Olie"] },
    { subject: "Pannenkoek", keywords: ["Rond", "Deeg", "Zoet/Hartig", "Bakken"] },
    { subject: "Kaviaar", keywords: ["Viskuit", "Duur", "Zwart", "Rusland"] },
    { subject: "Pinda", keywords: ["Noot", "Rood", "Zout", "Aard"] },
    { subject: "Champagne", keywords: ["Mousserend", "Frankrijk", "Feest", "Bubbel"] },
    { subject: "Wafel", keywords: ["België", "Stroop", "Suiker", "Oven"] },
    { subject: "Worst", keywords: ["Vlees", "Vorm", "BBQ", "Darm"] },
    { subject: "Kruidvat", keywords: ["Kruiden", "Sterk", "Azië", "Geur"] },
    { subject: "Mango", keywords: ["Tropisch", "Zoet", "Grote pit", "Oranje"] },
    { subject: "Avocado", keywords: ["Groen", "Grote pit", "Guacamole", "Vrucht"] },
    { subject: "Mosterd", keywords: ["Geel", "Scherp", "Saus", "Zaad"] },
    { subject: "Tomaat", keywords: ["Rood", "Groente/Fruit", "Soep", "Ketchup"] },

    // --- 🖼️ Kunst & Cultuur (30x) ---
    { subject: "Vincent van Gogh", keywords: ["Zonnebloemen", "Nederlands", "Oor", "Post-impressionisme"] },
    { subject: "Claude Monet", keywords: ["Frans", "Impressionisme", "Waterlelies", "Licht"] },
    { subject: "Michelangelo", keywords: ["David", "Sixtijnse Kapel", "Italiaans", "Renaissance"] },
    { subject: "Pablo Picasso", keywords: ["Guernica", "Kubisme", "Spaans", "Twintigste eeuw"] },
    { subject: "Leonardo da Vinci", keywords: ["Mona Lisa", "Uitvinder", "Italiaans", "Renaissance"] },
    { subject: "Andy Warhol", keywords: ["Pop Art", "Marilyn Monroe", "Campbell's soep", "Amerikaans"] },
    { subject: "Salvador Dalí", keywords: ["Surrealisme", "Snor", "Smeltende klokken", "Spaans"] },
    { subject: "Frida Kahlo", keywords: ["Mexicaans", "Zelfportret", "Wenkbrauw", "Vrouw"] },
    { subject: "De Denker", keywords: ["Auguste Rodin", "Beeldhouwwerk", "Brons", "Filosofie"] },
    { subject: "Ballet", keywords: ["Dans", "Tutu", "Spitzen", "Klassiek"] },
    { subject: "Opera", keywords: ["Zang", "Italiaans", "Podium", "Hoog"] },
    { subject: "Jazz", keywords: ["New Orleans", "Improvisatie", "Saxofoon", "Blues"] },
    { subject: "Gotiek", keywords: ["Kathedralen", "Hoog", "Middel", "Frankrijk"] },
    { subject: "Barok", keywords: ["Overdreven", "Rijk", "17e eeuw", "Kunststijl"] },
    { subject: "Fotografie", keywords: ["Camera", "Licht", "Beeld", "Lens"] },
    { subject: "Schildersezel", keywords: ["Hout", "Doek", "Standaard", "Atelier"] },
    { subject: "Poëzie", keywords: ["Gedicht", "Rijm", "Strofe", "Woorden"] },
    { subject: "Architectuur", keywords: ["Gebouw", "Ontwerp", "Stijl", "Bouwkunst"] },
    { subject: "Het Laatste Avondmaal", keywords: ["Da Vinci", "Jezus", "Muurschildering", "Milaan"] },
    { subject: "Guernica", keywords: ["Picasso", "Oorlog", "Zwart-wit", "Spaans"] },
    { subject: "Vrijheidsbeeld", keywords: ["New York", "Gift", "Fakkel", "Koper"] },
    { subject: "Colosseum", keywords: ["Rome", "Gladiatoren", "Oud", "Amfitheater"] },
    { subject: "Het Meisje met de Parel", keywords: ["Vermeer", "Schilderij", "Den Haag", "Hoofddoek"] },
    { subject: "Pop Art", keywords: ["Andy Warhol", "Commercieel", "Felle kleuren", "Lichtenstein"] },
    { subject: "Impressionisme", keywords: ["Monet", "Licht", "Parijs", "Buiten"] },
    { subject: "Sprookjes", keywords: ["Grimm", "Disney", "Magie", "Verhaal"] },
    { subject: "Manga", keywords: ["Japan", "Stripboek", "Animatie", "Tekening"] },
    { subject: "Haiku", keywords: ["Japan", "Dichtvorm", "Drie regels", "Natuur"] },
    { subject: "Keramiek", keywords: ["Klei", "Gebakken", "Vaas", "Potten"] },
    { subject: "Film Noir", keywords: ["Zwart-wit", "Detective", "Klassieke film", "Donker"] },

    // --- 👑 Geschiedenis & Politiek (30x) ---
    { subject: "Julius Caesar", keywords: ["Rome", "Generaal", "Dictator", "Idus van maart"] },
    { subject: "Winston Churchill", keywords: ["Groot-Brittannië", "Premier", "WO II", "Sigaar"] },
    { subject: "Napoleon Bonaparte", keywords: ["Frankrijk", "Keizer", "Waterloo", "Klein"] },
    { subject: "Cleopatra", keywords: ["Egypte", "Koningin", "Nijl", "Ptolemaeën"] },
    { subject: "Mahatma Gandhi", keywords: ["India", "Geweldloos", "Onafhankelijkheid", "Zoutmars"] },
    { subject: "Martin Luther King Jr.", keywords: ["Amerika", "Rechten", "I Have a Dream", "Burgerrechten"] },
    { subject: "George Washington", keywords: ["Eerste president", "Amerika", "Revolutie", "Vader des vaderlands"] },
    { subject: "Nelson Mandela", keywords: ["Zuid-Afrika", "Apartheid", "President", "Gevangenis"] },
    { subject: "Fidel Castro", keywords: ["Cuba", "Revolutie", "Sigaren", "Dictator"] },
    { subject: "Koude Oorlog", keywords: ["VS vs USSR", "Kernwapens", "Jaren '40-'90", "Berlijn"] },
    { subject: "Franse Revolutie", keywords: ["Bastille", "1789", "Guillotine", "Lodewijk XVI"] },
    { subject: "WO I", keywords: ["Loopgraven", "1914-1918", "Verdrag van Versailles", "Gas"] },
    { subject: "WO II", keywords: ["Hitler", "Atoombom", "1939-1945", "Geallieerden"] },
    { subject: "Vladimir Poetin", keywords: ["Rusland", "President", "KGB", "Macht"] },
    { subject: "Joe Biden", keywords: ["President", "Democraat", "Amerika", "Vicepresident"] },
    { subject: "Eerste Minister", keywords: ["Regeringsleider", "België", "Wetstraat 16", "Politiek"] },
    { subject: "Senaat", keywords: ["Politiek", "Kamer", "Tweede", "Vergadering"] },
    { subject: "Parlement", keywords: ["Wetgeving", "Vertegenwoordiging", "Kamer", "Democratie"] },
    { subject: "Verenigde Naties", keywords: ["New York", "Vrede", "Veiligheidsraad", "Wereld"] },
    { subject: "NAVO", keywords: ["Militair", "Verdediging", "Trans-Atlantisch", "Brussel"] },
    { subject: "Vlaanderen", keywords: ["Regio", "Nederlands", "Gent/Antwerpen", "België"] },
    { subject: "Wallonië", keywords: ["Regio", "Frans", "Luik/Namen", "België"] },
    { subject: "Europa", keywords: ["Continent", "EU", "Lidstaten", "Brug"] },
    { subject: "Communisme", keywords: ["Marx", "Rood", "Klasse", "Sovjet-Unie"] },
    { subject: "Democratie", keywords: ["Volk", "Stemmen", "Vrijheid", "Politiek"] },
    { subject: "Brexit", keywords: ["Groot-Brittannië", "EU", "Scheiding", "Referendum"] },
    { subject: "De Gouden Eeuw", keywords: ["Nederland", "17e eeuw", "Kunst", "Handel"] },
    { subject: "De IJzeren Dame", keywords: ["Margaret Thatcher", "Premier", "Groot-Brittannië", "Vrouw"] },
    { subject: "Bartholomeus", keywords: ["Ontdekker", "Amerika", "Caribisch", "Spaans"] }, // (Columbus)
    { subject: "Tutenchamun", keywords: ["Farao", "Graf", "Egypte", "Jong"] },

    // --- 💻 Technologie & Internet (30x) ---
    { subject: "Apple", keywords: ["iPhone", "Macbook", "Steve Jobs", "Logo"] },
    { subject: "Google", keywords: ["Zoekmachine", "Android", "Alphabet", "Gmail"] },
    { subject: "Microsoft", keywords: ["Windows", "Bill Gates", "Office", "Xbox"] },
    { subject: "Facebook", keywords: ["Mark Zuckerberg", "Meta", "Sociaal", "Blauw"] },
    { subject: "Amazon", keywords: ["Jeff Bezos", "Webwinkel", "Pijl", "Online"] },
    { subject: "Twitter (X)", keywords: ["Elon Musk", "Berichten", "Vogel", "Sociaal"] },
    { subject: "YouTube", keywords: ["Video", "Google", "Streamen", "Rood"] },
    { subject: "Wikipedia", keywords: ["Online", "Encyclopedie", "Kennis", "Vrijwilligers"] },
    { subject: "Bluetooth", keywords: ["Draadloos", "Verbinding", "Kort bereik", "Logo"] },
    { subject: "Processor", keywords: ["CPU", "Hersen", "Computer", "Snelheid"] },
    { subject: "Robot", keywords: ["Automatisering", "Metaal", "Programma", "Toekomst"] },
    { subject: "Blockchain", keywords: ["Crypto", "Gedecentraliseerd", "Transacties", "Digitaal"] },
    { subject: "Artificial Intelligence", keywords: ["AI", "Leren", "Machine", "Slim"] },
    { subject: "Glasvezel", keywords: ["Kabel", "Licht", "Snel", "Internet"] },
    { subject: "Pixel", keywords: ["Beeld", "Scherm", "Punt", "Kleur"] },
    { subject: "Hacker", keywords: ["Computer", "Inbreken", "Code", "Veiligheid"] },
    { subject: "Virtual Reality", keywords: ["VR", "Bril", "3D", "Simulatie"] },
    { subject: "5G", keywords: ["Mobiel", "Netwerk", "Snel", "Generatie"] },
    { subject: "E-mail", keywords: ["Digitaal", "Post", "Verzenden", "Adres"] },
    { subject: "Firewall", keywords: ["Veiligheid", "Netwerk", "Blokkeert", "Muur"] },
    { subject: "Cloud Computing", keywords: ["Opslag", "Internet", "Bestanden", "Servers"] },
    { subject: "Smartphone", keywords: ["Bellen", "Apps", "Camera", "Mobiel"] },
    { subject: "Laptop", keywords: ["Computer", "Draagbaar", "Accu", "Scherm"] },
    { subject: "Drone", keywords: ["Vliegen", "Camera", "Afstand", "Propeller"] },
    { subject: "E-reader", keywords: ["Boek", "Digitaal", "Inkt", "Lezen"] },
    { subject: "USB", keywords: ["Poort", "Kabel", "Data", "Stick"] },
    { subject: "Software", keywords: ["Programma", "Code", "Digitaal", "Applicatie"] },
    { subject: "Hardware", keywords: ["Fysiek", "Computer", "Onderdelen", "Metaal"] },
    { subject: "Zoom", keywords: ["Video", "Vergaderen", "Online", "App"] },
    { subject: "Wi-Fi", keywords: ["Draadloos", "Internet", "Signaal", "Netwerk"] },

    // --- ⚽ Sport (30x) ---
    { subject: "Basketbal", keywords: ["Net", "Dribbelen", "Vijf", "NBA"] },
    { subject: "Zwemmen", keywords: ["Water", "Slag", "Badpak", "Olympisch"] },
    { subject: "Golf", keywords: ["Club", "Hole", "Tee", "Balletje"] },
    { subject: "Honkbal", keywords: ["Amerika", "Bat", "Pitcher", "Home run"] },
    { subject: "Formule 1", keywords: ["Auto's", "Circuit", "Max Verstappen", "Pitstop"] },
    { subject: "Hockey", keywords: ["Stick", "Kleine bal", "Veld", "Short corner"] },
    { subject: "Atletiek", keywords: ["Lopen", "Werpen", "Springen", "Tienkamp"] },
    { subject: "Roeien", keywords: ["Boot", "Riemen", "Water", "Acht"] },
    { subject: "Rugby", keywords: ["Ovaal", "Try", "Haka", "Nieuw-Zeeland"] },
    { subject: "Schaken", keywords: ["Bord", "Zwart/Wit", "Koning", "Mat"] },
    { subject: "Boksen", keywords: ["Ring", "Handschoenen", "K.O.", "Zwaargewicht"] },
    { subject: "Judo", keywords: ["Japan", "Worp", "Mat", "Gordel"] },
    { subject: "Surfen", keywords: ["Golf", "Board", "Hawaï", "Zee"] },
    { subject: "Darts", keywords: ["Pijltjes", "Bord", "Dubbel", "180"] },
    { subject: "Schermen", keywords: ["Degen", "Masker", "Epee", "Raak"] },
    { subject: "Skateboarden", keywords: ["Plank", "Trick", "Halfpipe", "Vier wielen"] },
    { subject: "Handbal", keywords: ["Zeven", "Doel", "Gooien", "Veld"] },
    { subject: "Gymnastiek", keywords: ["Balk", "Vloer", "Ringen", "Turnen"] },
    { subject: "Tennis", keywords: ["Racket", "Net", "Set", "Gras"] },
    { subject: "Voetbal", keywords: ["Bal", "Stadion", "Rode kaart", "Elf"] },
    { subject: "IJshockey", keywords: ["IJs", "Puck", "Stick", "Canada"] },
    { subject: "Curling", keywords: ["IJs", "Bezem", "Schijf", "Schotland"] },
    { subject: "Turnen", keywords: ["Balk", "Ringen", "Vloer", "Sprong"] },
    { subject: "Triatlon", keywords: ["Zwemmen", "Fietsen", "Lopen", "Drie"] },
    { subject: "Snooker", keywords: ["Tafel", "Ballen", "Keu", "Potten"] },
    { subject: "Paardrijden", keywords: ["Paard", "Zadel", "Dressuur", "Springen"] },
    { subject: "Waterskiën", keywords: ["Water", "Boot", "Lijnen", "Snelheid"] },
    { subject: "Mountainbiken", keywords: ["Fiets", "Modder", "Berg", "Off-road"] },
    { subject: "Volleybal", keywords: ["Net", "Blok", "Dienen", "Strand"] },
    { subject: "Biatlon", keywords: ["Skiën", "Schieten", "Winter", "Twee"] },

    // --- 🏠 Dagelijkse Objecten (30x) ---
    { subject: "Sleutel", keywords: ["Slot", "Metaal", "Huis", "Openen"] },
    { subject: "Schaar", keywords: ["Twee gaten", "Knippen", "Papier", "Metaal"] },
    { subject: "Paraplu", keywords: ["Regen", "Opklapbaar", "Stok", "Nat"] },
    { subject: "Tandenborstel", keywords: ["Poetsen", "Haar", "Pasta", "Mond"] },
    { subject: "Wasmachine", keywords: ["Kleding", "Schoon", "Draaien", "Zeep"] },
    { subject: "Koptelefoon", keywords: ["Oren", "Muziek", "Horen", "Draad"] },
    { subject: "Kaars", keywords: ["Vuur", "Licht", "Was", "Feest"] },
    { subject: "Spiegel", keywords: ["Reflectie", "Glas", "Kijken", "Badkamer"] },
    { subject: "Klok", keywords: ["Tijd", "Wijzers", "Tikken", "Rond"] },
    { subject: "Kussen", keywords: ["Hoofd", "Zacht", "Slapen", "Bed"] },
    { subject: "Portemonnee", keywords: ["Geld", "Kaart", "Leder", "Tas"] },
    { subject: "Gloeilamp", keywords: ["Licht", "Edison", "Glas", "Kap"] },
    { subject: "Zaklamp", keywords: ["Batterij", "Donker", "Lichtbundel", "Hand"] },
    { subject: "Kalender", keywords: ["Datum", "Maanden", "Jaren", "Afdruk"] },
    { subject: "Deurbel", keywords: ["Geluid", "Gasten", "Drukken", "Huis"] },
    { subject: "Thermosfles", keywords: ["Warm/Koud", "Drinken", "Isoleren", "Metaal"] },
    { subject: "Stofzuiger", keywords: ["Zuigen", "Vloer", "Slang", "Zak"] },
    { subject: "Magnetron", keywords: ["Warm", "Eten", "Straling", "Kort"] },
    { subject: "Koelkast", keywords: ["Koud", "Eten", "Bewaren", "Deur"] },
    { subject: "Toetsenbord", keywords: ["Typen", "QWERTY", "Enter", "Computer"] },
    { subject: "Muis", keywords: ["Cursor", "Klik", "Draadloos", "Computer"] },
    { subject: "Stopcontact", keywords: ["Stroom", "Gaten", "Muur", "Plug"] },
    { subject: "Afstandsbediening", keywords: ["TV", "Knoppen", "Zappen", "Batterij"] },
    { subject: "Potlood", keywords: ["Hout", "Schrijven", "Gum", "Grafiet"] },
    { subject: "Pen", keywords: ["Inkt", "Schrijven", "Balpunt", "Plastic"] },
    { subject: "Hangkast", keywords: ["Muur", "Opbergen", "Keuken", "Deuren"] },
    { subject: "Wekker", keywords: ["Tijd", "Geluid", "Wakker", "Bedtijd"] },
    { subject: "Bril", keywords: ["Ogen", "Zien", "Glazen", "Montuur"] },
    { subject: "Krijt", keywords: ["Wit", "Bord", "School", "Teken"] },
    { subject: "Spiegelreflexcamera", keywords: ["Fotografie", "Lens", "Groot", "SLR"] },

    // --- 🌿 Planten & Tuin (30x) ---
    { subject: "Roos", keywords: ["Bloem", "Rood", "Doorn", "Liefde"] },
    { subject: "Tulp", keywords: ["Bloem", "Nederland", "Bollen", "Lente"] },
    { subject: "Eik", keywords: ["Boom", "Eikel", "Sterk", "Hout"] },
    { subject: "Gras", keywords: ["Groen", "Veld", "Maaier", "Kort"] },
    { subject: "Kruidnagel", keywords: ["Specerij", "Nagel", "Sterk", "Glühwein"] },
    { subject: "Basilicum", keywords: ["Kruid", "Italiaans", "Pesto", "Groen"] },
    { subject: "Lavendel", keywords: ["Paars", "Geur", "Zuid-Frankrijk", "Plant"] },
    { subject: "Cactus", keywords: ["Woestijn", "Stekels", "Water", "Vetplant"] },
    { subject: "Bamboe", keywords: ["Gras", "Snel", "Panda", "Azië"] },
    { subject: "Varen", keywords: ["Blad", "Bos", "Sporen", "Plant"] },
    { subject: "Aardbei", keywords: ["Rood", "Zomer", "Zoet", "Fruit"] },
    { subject: "Wortel", keywords: ["Oranje", "Grond", "Konijn", "A-vitamine"] },
    { subject: "Tomaat", keywords: ["Rood", "Groente/Fruit", "Soep", "Ketchup"] },
    { subject: "Komkommer", keywords: ["Lang", "Groen", "Waterig", "Salade"] },
    { subject: "Bloemkool", keywords: ["Wit", "Roos", "Groente", "Koken"] },
    { subject: "Schoffel", keywords: ["Tuin", "Onkruid", "Grond", "Gereedschap"] },
    { subject: "Gieter", keywords: ["Water", "Tuin", "Plant", "Gaten"] },
    { subject: "Compost", keywords: ["Afval", "Grond", "Mest", "Vergaan"] },
    { subject: "Mos", keywords: ["Groen", "Vocht", "Grond", "Klein"] },
    { subject: "Druif", keywords: ["Wijn", "Tros", "Zoet/Zuur", "Klimplant"] },
    { subject: "Sla", keywords: ["Groen", "Blad", "Salade", "Krop"] },
    { subject: "Ui", keywords: ["Tranend", "Laagjes", "Sterk", "Smaak"] },
    { subject: "Boeket", keywords: ["Bloemen", "Cadeau", "Binden", "Vaas"] },
    { subject: "Zaad", keywords: ["Plant", "Begin", "Grond", "Klein"] },
    { subject: "Spar", keywords: ["Boom", "Kerst", "Naald", "Kegel"] },
    { subject: "Aloë Vera", keywords: ["Woestijn", "Gel", "Medisch", "Plant"] },
    { subject: "Paprika", keywords: ["Rood/Geel/Groen", "Vorm", "Pittig", "Groente"] },
    { subject: "Peterselie", keywords: ["Groen", "Kruid", "Garnering", "Italiaans"] },
    { subject: "Pioenroos", keywords: ["Bloem", "Groot", "Roze", "Lente"] },
    { subject: "Viooltjes", keywords: ["Klein", "Paars", "Bloem", "Lente"] },

    // --- 🇧🇪🇳🇱 Steden & Plaatsen (30x) ---
    { subject: "Rotterdam", keywords: ["Haven", "Erasmusbrug", "Kubuswoningen", "Maas"] },
    { subject: "Brugge", keywords: ["België", "Water", "Historisch", "Horeca"] },
    { subject: "Utrecht", keywords: ["Domtoren", "Gracht", "Midden", "Nederland"] },
    { subject: "Den Haag", keywords: ["Politiek", "Scheveningen", "Vredespaleis", "Koninklijk"] },
    { subject: "Maastricht", keywords: ["Limburg", "Sint Servaas", "Vrijthof", "Verdrag"] },
    { subject: "Kopenhagen", keywords: ["Denemarken", "Zeemeermin", "Fiets", "Hoofdstad"] },
    { subject: "Wenen", keywords: ["Oostenrijk", "Klassieke muziek", "Donau", "Keizerrijk"] },
    { subject: "Peking", keywords: ["China", "Verboden Stad", "Muur", "Olympische Spelen"] },
    { subject: "Caïro", keywords: ["Egypte", "Nijl", "Piramide", "Groot"] },
    { subject: "Mexico-Stad", keywords: ["Hoogte", "Groot", "Azteken", "Latijns-Amerika"] },
    { subject: "Dubai", keywords: ["Zand", "Hoogste", "Luxe", "Verenigde Arabische Emiraten"] },
    { subject: "Boedapest", keywords: ["Hongarije", "Donau", "Twee delen", "Baden"] },
    { subject: "Praag", keywords: ["Tsjechië", "Karel de Grote", "Brug", "Hoofdstad"] },
    { subject: "Lissabon", keywords: ["Portugal", "Tram", "Zeven heuvels", "Fado"] },
    { subject: "Milaan", keywords: ["Italië", "Mode", "Duomo", "Voetbal"] },
    { subject: "Barcelona", keywords: ["Spanje", "Gaudi", "Strand", "Catalonië"] },
    { subject: "Seoel", keywords: ["Zuid-Korea", "Technologie", "Han", "Hoofdstad"] },
    { subject: "Dublin", keywords: ["Ierland", "Guinness", "Groen", "Literatuur"] },
    { subject: "Berlijn", keywords: ["Muur", "Brandenburger Tor", "Hoofdstad", "Duitsland"] },
    { subject: "Venetië", keywords: ["Italië", "Water", "Gondel", "Bruggen"] },
    { subject: "New York", keywords: ["Vrijheidsbeeld", "Big Apple", "Manhattan", "Times Square"] },
    { subject: "Amsterdam", keywords: ["Grachten", "Fietsen", "Rijksmuseum", "Nederland"] },
    { subject: "Parijs", keywords: ["Eiffeltoren", "Liefde", "Seine", "Frankrijk"] },
    { subject: "Londen", keywords: ["Big Ben", "Thee", "Tower Bridge", "Engeland"] },
    { subject: "Wenen", keywords: ["Muziek", "Oostenrijk", "Donau", "Klassiek"] },
    { subject: "Helsinki", keywords: ["Finland", "Koud", "Zee", "Design"] },
    { subject: "Athene", keywords: ["Griekenland", "Akropolis", "Oud", "Hoofdstad"] },
    { subject: "Rio de Janeiro", keywords: ["Brazilië", "Carnaval", "Christusbeeld", "Strand"] },
    { subject: "Stockholm", keywords: ["Zweden", "Water", "Nobelprijs", "Stadhuizen"] },
    { subject: "Vaticaanstad", keywords: ["Paus", "Kleinste land", "Rome", "Basiliek"] },

    // --- 🚚 Vervoer (30x) ---
    { subject: "Vliegtuig", keywords: ["Vleugels", "Lucht", "Jet", "Reizen"] },
    { subject: "Trein", keywords: ["Rails", "Lang", "Stations", "Stoom"] },
    { subject: "Fiets", keywords: ["Twee wielen", "Pedalen", "Zadel", "Bel"] },
    { subject: "Auto", keywords: ["Vier wielen", "Motor", "Weg", "Rijden"] },
    { subject: "Schip", keywords: ["Zee", "Groot", "Varen", "Haven"] },
    { subject: "Bus", keywords: ["Groot", "Openbaar", "Passagiers", "Route"] },
    { subject: "Tram", keywords: ["Rails", "Stad", "Elektriciteit", "Wagon"] },
    { subject: "Metro", keywords: ["Ondergronds", "Stad", "Snel", "Rails"] },
    { subject: "Taxi", keywords: ["Geel/Zwart", "Huren", "Rit", "Meter"] },
    { subject: "Helikopter", keywords: ["Rotor", "Verticaal", "Vliegen", "Redding"] },
    { subject: "Scooter", keywords: ["Twee wielen", "Klein", "Brommen", "Stad"] },
    { subject: "Zeppelin", keywords: ["Lucht", "Groot", "Gas", "Oud"] },
    { subject: "Kano", keywords: ["Water", "Peddel", "Smalle boot", "Rivier"] },
    { subject: "Step", keywords: ["Plank", "Stuur", "Duwen", "Elektrisch"] },
    { subject: "Kabelbaan", keywords: ["Kabel", "Berg", "Passagiers", "Vast"] },
    { subject: "Vrachtwagen", keywords: ["Groot", "Goederen", "Weg", "Trailer"] },
    { subject: "Spaceshuttle", keywords: ["Ruimte", "Lanceer", "NASA", "Vleugels"] },
    { subject: "Slee", keywords: ["Sneeuw", "Hout", "Trekken", "Winter"] },
    { subject: "Duikboot", keywords: ["Onder water", "Militair", "Periscoop", "Zee"] },
    { subject: "Luchtballon", keywords: ["Lucht", "Warm", "Mand", "Vliegen"] },
    { subject: "Tractor", keywords: ["Boerderij", "Groot wiel", "Landbouw", "Traag"] },
    { subject: "Ferry", keywords: ["Boot", "Auto's", "Water", "Overtocht"] },
    { subject: "Motor", keywords: ["Twee wielen", "Snel", "Helm", "Benzine"] },
    { subject: "Tuktuk", keywords: ["Azië", "Driewieler", "Taxi", "Open"] },
    { subject: "Jetpack", keywords: ["Rugzak", "Vliegen", "Futuristisch", "Raket"] },
    { subject: "Skateboard", keywords: ["Vier wielen", "Plank", "Trick", "Straat"] },
    { subject: "Riksja", keywords: ["Fiets", "Azië", "Passagiers", "Trekken"] },
    { subject: "Snowboard", keywords: ["Winter", "Berg", "Sneeuw", "Bind"] },
    { subject: "Rollercoaster", keywords: ["Pretpark", "Snel", "Rails", "Achtbaan"] },
    { subject: "Zweefvliegtuig", keywords: ["Lucht", "Geen motor", "Stilte", "Vleugels"] },

    // --- 🧬 Menselijk Lichaam & Gezondheid (30x) ---
    { subject: "Hart", keywords: ["Kloppen", "Bloed", "Pomp", "Liefde"] },
    { subject: "Hersenen", keywords: ["Denken", "Hoofd", "Controle", "Grijs"] },
    { subject: "Longen", keywords: ["Ademen", "Zuurstof", "Twee", "Borst"] },
    { subject: "Lever", keywords: ["Grootste orgaan", "Ontgiften", "Gal", "Buik"] },
    { subject: "Skelet", keywords: ["Botten", "Frame", "Ondersteuning", "206"] },
    { subject: "Ogen", keywords: ["Zien", "Twee", "Kleur", "Licht"] },
    { subject: "Maag", keywords: ["Eten", "Verteren", "Zuur", "Zak"] },
    { subject: "Huid", keywords: ["Grootste orgaan", "Bedekking", "Tast", "Beschermen"] },
    { subject: "Bloed", keywords: ["Rood", "Vervoer", "Aders", "Plasma"] },
    { subject: "Spieren", keywords: ["Bewegen", "Sterk", "Vlees", "Trekken"] },
    { subject: "Tong", keywords: ["Proeven", "Spreken", "Roze", "Mond"] },
    { subject: "Oor", keywords: ["Horen", "Balans", "Schelp", "Trommel"] },
    { subject: "Slokdarm", keywords: ["Pijp", "Eten", "Maag", "Keel"] },
    { subject: "Aders", keywords: ["Bloedvaten", "Blauw", "Terug", "Hart"] },
    { subject: "Tanden", keywords: ["Bijten", "Wit", "32", "Kaak"] },
    { subject: "Zenuwen", keywords: ["Signalen", "Pijn", "Stelsel", "Snel"] },
    { subject: "Middenrif", keywords: ["Ademhaling", "Spier", "Scheiding", "Borst"] },
    { subject: "Knie", keywords: ["Gewricht", "Been", "Buigen", "Patella"] },
    { subject: "Hand", keywords: ["Vijf vingers", "Grijpen", "Pols", "Schrijven"] },
    { subject: "Nieren", keywords: ["Filteren", "Boonvormig", "Twee", "Afval"] },
    { subject: "Insuline", keywords: ["Hormoon", "Suiker", "Diabetes", "Alvleesklier"] },
    { subject: "Vitamine C", keywords: ["Ascorbinezuur", "Citrus", "Afweer", "Scheurbuik"] },
    { subject: "Griep", keywords: ["Virus", "Hoest", "Koorts", "Besmettelijk"] },
    { subject: "Cholesterol", keywords: ["Vet", "Bloed", "Goed/Slecht", "Dieet"] },
    { subject: "Antibiotica", keywords: ["Medicijn", "Bacteriën", "Infectie", "Penicilline"] },
    { subject: "Pijnstiller", keywords: ["Medicijn", "Hoofdpijn", "Paracetamol", "Verlichting"] },
    { subject: "MRI", keywords: ["Scanner", "Magnetisch", "Lichaam", "Ziekenhuis"] },
    { subject: "Hormoon", keywords: ["Chemisch", "Boodschapper", "Klieren", "Groeien"] },
    { subject: "Allergie", keywords: ["Reactie", "Immuunsysteem", "Pollen", "Niezen"] },
    { subject: "Zuurstofmasker", keywords: ["Ademen", "Nood", "Hoogte", "Medisch"] },

    // --- 🦁 Dieren (30x) ---
    { subject: "Olifant", keywords: ["Slurf", "Groot", "Grijs", "Afrika/Azië"] },
    { subject: "Zebra", keywords: ["Strepen", "Paard", "Savanne", "Zwart-wit"] },
    { subject: "Leeuw", keywords: ["Koning", "Manen", "Kat", "Jacht"] },
    { subject: "Panda", keywords: ["Bamboe", "Zwart-Wit", "China", "Bedreigd"] },
    { subject: "Tijger", keywords: ["Strepen", "Kat", "Azië", "Oranje"] },
    { subject: "Pinguïn", keywords: ["Zuidpool", "Vogel", "Zwemmen", "Zwart-wit"] },
    { subject: "Dolfijn", keywords: ["Zee", "Intelligent", "Springen", "Zoogdier"] },
    { subject: "Krokodil", keywords: ["Reptiel", "Tanden", "Lange bek", "Nijl"] },
    { subject: "Vlinder", keywords: ["Insect", "Kleur", "Rups", "Vliegen"] },
    { subject: "Walvis", keywords: ["Groot", "Zee", "Zoogdier", "Blazen"] },
    { subject: "Kameel", keywords: ["Bulten", "Woestijn", "Spugen", "Water"] },
    { subject: "Slang", keywords: ["Giftig", "Kruipen", "Geen poten", "Reptiel"] },
    { subject: "Aap", keywords: ["Slinger", "Banaan", "Jungle", "Zoogdier"] },
    { subject: "Mier", keywords: ["Klein", "Kolonie", "Werk", "Insect"] },
    { subject: "Egel", keywords: ["Stekels", "Nacht", "Rollend", "Klein"] },
    { subject: "Vleermuis", keywords: ["Vliegt", "Nacht", "Zoogdier", "Echo"] },
    { subject: "Kraai", keywords: ["Zwart", "Intelligent", "Vogel", "Roepen"] },
    { subject: "Kikker", keywords: ["Amfibie", "Springt", "Groen", "Kwak"] },
    { subject: "Hert", keywords: ["Geweien", "Bos", "Bruin", "Wild"] },
    { subject: "Wolf", keywords: ["Hond", "Roedel", "Jagen", "Huilen"] },
    { subject: "Giraffe", keywords: ["Lange nek", "Afrika", "Vlekken", "Hoog"] },
    { subject: "Koala", keywords: ["Australië", "Eucalyptus", "Buikzak", "Beer"] },
    { subject: "Flamingo", keywords: ["Roze", "Eén poot", "Vogel", "Warm"] },
    { subject: "Varken", keywords: ["Stal", "Roze", "Knorren", "Modder"] },
    { subject: "Haas", keywords: ["Langoren", "Snel", "Veld", "Konijn"] },
    { subject: "Vlieg", keywords: ["Insect", "Irritant", "Zwart", "Vliegen"] },
    { subject: "Pauw", keywords: ["Vogel", "Veren", "Staart", "Ogen"] },
    { subject: "Eend", keywords: ["Water", "Snavel", "Kwak", "Vogel"] },
    { subject: "Muis", keywords: ["Klein", "Staart", "Kaas", "Knaagdier"] },
    { subject: "Schorpioen", keywords: ["Giftig", "Staart", "Woestijn", "Acht poten"] },

    // --- 🏺 Mythen & Legenden (30x) ---
    { subject: "Zeus", keywords: ["Oppergod", "Bliksem", "Olympos", "Griek"] },
    { subject: "Sfinx", keywords: ["Egypte", "Raadsel", "Hoofd/Lichaam", "Mythe"] },
    { subject: "Medusa", keywords: ["Slangenhaar", "Verstenen", "Griek", "Gorgon"] },
    { subject: "Thor", keywords: ["Noors", "Hamer", "Donder", "Ragnarok"] },
    { subject: "Feniks", keywords: ["Vogel", "Vuur", "As", "Herrijzen"] },
    { subject: "Draak", keywords: ["Vleugels", "Vuur", "Schubben", "Mythisch"] },
    { subject: "Eenhoorn", keywords: ["Wit paard", "Hoorn", "Puur", "Magie"] },
    { subject: "Merlijn", keywords: ["Tovenaar", "Baard", "Arthur", "Magiër"] },
    { subject: "Arthur", keywords: ["Koning", "Zwaard", "Ronde Tafel", "Camelot"] },
    { subject: "Pegasus", keywords: ["Vleugels", "Wit", "Paard", "Griek"] },
    { subject: "Hades", keywords: ["Onderwereld", "Griek", "God", "Dood"] },
    { subject: "Cupido", keywords: ["Liefde", "Pijl", "Romeins", "Engel"] },
    { subject: "Valkyrie", keywords: ["Noors", "Krijger", "Walhalla", "Paard"] },
    { subject: "Kabouter", keywords: ["Klein", "Rood", "Puntmuts", "Bos"] },
    { subject: "Zeemeermin", keywords: ["Onder water", "Vrouw", "Staart", "Zingen"] },
    { subject: "Minotaurus", keywords: ["Half mens/stier", "Labyrint", "Griek", "Monster"] },
    { subject: "Anubis", keywords: ["Egypte", "Doden", "Jakhals", "Wegen"] },
    { subject: "Cycloop", keywords: ["Eén oog", "Reus", "Griek", "Odyssee"] },
    { subject: "Sleipnir", keywords: ["Noors", "Odin", "Acht poten", "Paard"] },
    { subject: "Godin van de Jacht", keywords: ["Artemis", "Pijl en boog", "Griek", "Maan"] },
    { subject: "Trollen", keywords: ["Noors", "Grot", "Groot", "Steen"] },
    { subject: "Zombies", keywords: ["Dood", "Lopen", "Hersenen", "Levende"] },
    { subject: "Goblin", keywords: ["Klein", "Groen", "Onderaards", "Slechte aard"] },
    { subject: "Gargoyle", keywords: ["Steen", "Kerk", "Afvoer", "Beeld"] },
    { subject: "Hydra", keywords: ["Slang", "Meerdere hoofden", "Griek", "Heracles"] },
    { subject: "Elf", keywords: ["Klein", "Bos", "Puntoren", "Magie"] },
    { subject: "Heks", keywords: ["Bezem", "Magie", "Ketel", "Slecht"] },
    { subject: "Jinn", keywords: ["Geest", "Lamp", "Arabisch", "Wensen"] },
    { subject: "Poseidon", keywords: ["Zee", "Drietand", "Griek", "God"] },
    { subject: "Werewolf", keywords: ["Volle maan", "Wolf", "Mens", "Transformatie"] },

    // --- ⚖️ Maten & Geld (30x) ---
    { subject: "Kilogram", keywords: ["Gewicht", "1000 gram", "Massa", "Kilo"] },
    { subject: "Meter", keywords: ["Lengte", "100 cm", "Afstand", "Basis"] },
    { subject: "Euro", keywords: ["Munt", "Europa", "100 cent", "Geld"] },
    { subject: "Liter", keywords: ["Inhoud", "Vloeistof", "Fles", "Volume"] },
    { subject: "Seconde", keywords: ["Tijd", "60", "Kort", "Uur"] },
    { subject: "Celsius", keywords: ["Temperatuur", "0/100", "Water", "Maat"] },
    { subject: "Ampère", keywords: ["Stroom", "Elektriciteit", "Eenheid", "A"] },
    { subject: "Hectare", keywords: ["Oppervlakte", "Land", "Vierkant", "100x100"] },
    { subject: "Volt", keywords: ["Spanning", "Stroom", "V", "U"] },
    { subject: "Bar", keywords: ["Druk", "Banden", "Weer", "Atmosfeer"] },
    { subject: "Decibel", keywords: ["Geluid", "Luid", "Oor", "dB"] },
    { subject: "Watt", keywords: ["Vermogen", "Lamp", "Energie", "Stroom"] },
    { subject: "Pond", keywords: ["Groot-Brittannië", "Geld", "Gewicht", "Sterling"] },
    { subject: "Kilometer", keywords: ["Afstand", "1000 meter", "Weg", "km"] },
    { subject: "Gram", keywords: ["Gewicht", "Klein", "Keuken", "G"] },
    { subject: "Karat", keywords: ["Goud", "Zuiver", "24", "Diamant"] },
    { subject: "Bitcoin", keywords: ["Crypto", "Digitaal", "Munt", "Blockchain"] },
    { subject: "Knoop", keywords: ["Snelheid", "Zeevaart", "Vliegen", "Eenheid"] },
    { subject: "Pixel", keywords: ["Beeld", "Scherm", "Punt", "Kleur"] },
    { subject: "Ounce", keywords: ["Amerikaans", "Gewicht", "Goud", "Vloeistof"] },
    { subject: "Dollar", keywords: ["Amerika", "Geld", "Groen", "Teken"] },
    { subject: "Yen", keywords: ["Japan", "Munt", "Azië", "Geld"] },
    { subject: "Mijl", keywords: ["Afstand", "Amerika", "Land", "1.6 km"] },
    { subject: "Fahrenheit", keywords: ["Temperatuur", "Amerika", "Koud/Warm", "Maat"] },
    { subject: "Hertz", keywords: ["Frequentie", "Golf", "Geluid", "Trilling"] },
    { subject: "Newton", keywords: ["Kracht", "Wet", "Appel", "SI-eenheid"] },
    { subject: "Joule", keywords: ["Energie", "Arbeid", "Warmte", "Eenheid"] },
    { subject: "Minuut", keywords: ["Tijd", "60 seconden", "Uur", "Wachten"] },
    { subject: "Week", keywords: ["Zeven dagen", "Tijd", "Kalender", "Vrijdag"] },
    { subject: "Milliliter", keywords: ["Vloeistof", "Klein", "Volume", "1/1000 liter"] },

    // --- 🛠️ Gereedschap & Materialen (30x) ---
    { subject: "Hamer", keywords: ["Spijkers", "Slag", "Kop", "Handvat"] },
    { subject: "Schroevendraaier", keywords: ["Draaien", "Philips", "Plat", "Hand"] },
    { subject: "Tang", keywords: ["Vastgrijpen", "Knippen", "Bek", "Metaal"] },
    { subject: "Boormachine", keywords: ["Gat", "Wand", "Draaien", "Elektrisch"] },
    { subject: "Zaag", keywords: ["Tanden", "Hout", "Knippen", "Hand"] },
    { subject: "Beitel", keywords: ["Hout", "Hakken", "Scherp", "Metaal"] },
    { subject: "Verfkwast", keywords: ["Schilderen", "Haar", "Kleur", "Streek"] },
    { subject: "Plug", keywords: ["Wand", "Schroef", "Plastic", "Vast"] },
    { subject: "Accu", keywords: ["Batterij", "Auto", "Opladen", "Energie"] },
    { subject: "Kettingzaag", keywords: ["Motor", "Boom", "Gevaarlijk", "Snel"] },
    { subject: "Goud", keywords: ["Metaal", "Geel", "Sieraad", "Au"] },
    { subject: "Plastic", keywords: ["Olie", "Licht", "Recyclen", "Verpakking"] },
    { subject: "Glas", keywords: ["Doorzichtig", "Breken", "Raam", "Zand"] },
    { subject: "Koper", keywords: ["Metaal", "Roodbruin", "Draad", "Geleider"] },
    { subject: "Staal", keywords: ["Ijzer", "Sterk", "Bouwen", "Legering"] },
    { subject: "Hout", keywords: ["Boom", "Bruin", "Bouwen", "Meubel"] },
    { subject: "Karton", keywords: ["Papier", "Doos", "Golf", "Verpakking"] },
    { subject: "Leder", keywords: ["Huid", "Schoenen", "Tas", "Dieren"] },
    { subject: "Klei", keywords: ["Aarde", "Keramiek", "Nat", "Vormen"] },
    { subject: "Wol", keywords: ["Schaap", "Trui", "Warm", "Breien"] },
    { subject: "Beton", keywords: ["Cement", "Water", "Steen", "Bouwen"] },
    { subject: "Rolmaat", keywords: ["Meten", "Lint", "Oprollen", "Centimeters"] },
    { subject: "Soldeerbout", keywords: ["Elektronica", "Warm", "Tin", "Verbinden"] },
    { subject: "Waterpas", keywords: ["Bubbel", "Recht", "Horizontaal", "Groen"] },
    { subject: "Ladder", keywords: ["Klimmen", "Treden", "Hoog", "Vouwen"] },
    { subject: "Zilver", keywords: ["Metaal", "Wit", "Spiegel", "Ag"] },
    { subject: "Suiker", keywords: ["Wit", "Zoet", "Riet", "Energie"] },
    { subject: "Zout", keywords: ["Wit", "Zee", "Keuken", "NaCl"] },
    { subject: "Lood", keywords: ["Zwaar", "Grijs", "Pijp", "Giftig"] },
    { subject: "Ammoniak", keywords: ["Gas", "Sterke geur", "Schoonmaak", "NH3"] },

    // --- 🌍 Willekeurige Feiten & Diversen (30x) ---
    { subject: "Zon", keywords: ["Ster", "Warm", "Licht", "Geel"] },
    { subject: "Aarde", keywords: ["Planeet", "Blauw", "Leven", "Draaien"] },
    { subject: "Sneeuw", keywords: ["Wit", "Koud", "Vlok", "Winter"] },
    { subject: "Regenboog", keywords: ["Zeven kleuren", "Water", "Zon", "Boog"] },
    { subject: "Schaduw", keywords: ["Licht", "Donker", "Vorm", "Volgen"] },
    { subject: "Olie", keywords: ["Zwart", "Motor", "Vloeistof", "Arabisch"] },
    { subject: "Papier", keywords: ["Boom", "Schrijven", "Vouwen", "Blad"] },
    { subject: "Wijn", keywords: ["Druif", "Rood/Wit", "Fles", "Alcohol"] },
    { subject: "Touw", keywords: ["Dragen", "Vastbinden", "Vlecht", "Dik"] },
    { subject: "Magnetisme", keywords: ["Aantrekken", "Noord/Zuid", "Metaal", "Kracht"] },
    { subject: "Zeven", keywords: ["Getal", "Dagen", "Wonderen", "Geluk"] },
    { subject: "Blauw", keywords: ["Kleur", "Lucht", "Zee", "Primair"] },
    { subject: "Verpakking", keywords: ["Doos", "Beschermen", "Product", "Folie"] },
    { subject: "Puzzel", keywords: ["Stukjes", "Vorm", "Oplossen", "Vrije tijd"] },
    { subject: "Balans", keywords: ["Evenwicht", "Gewicht", "Boekhouden", "Twee kanten"] },
    { subject: "Barcode", keywords: ["Strepen", "Scanner", "Product", "Winkel"] },
    { subject: "Briljant", keywords: ["Slijpvorm", "Diamant", "Schitteren", "Licht"] },
    { subject: "Vuurwerk", keywords: ["Explosie", "Licht", "Geluid", "Nieuwjaar"] },
    { subject: "Regen", keywords: ["Water", "Wolken", "Nat", "Druppels"] },
    { subject: "Woestijn", keywords: ["Zand", "Droog", "Hitte", "Kameel"] },
    { subject: "Tijd", keywords: ["Uur", "Minuut", "Seconde", "Voorbij"] },
    { subject: "Geduld", keywords: ["Wachten", "Rust", "Deugd", "Kalm"] },
    { subject: "Lachen", keywords: ["Geluid", "Blij", "Gezicht", "Grappig"] },
    { subject: "Slapen", keywords: ["Ogen dicht", "Rust", "Dromen", "Nacht"] },
    { subject: "Muziek", keywords: ["Noten", "Geluid", "Instrument", "Dansen"] },
    { subject: "Spel", keywords: ["Regels", "Winnen", "Bord", "Spelen"] },
    { subject: "Geheim", keywords: ["Niet zeggen", "Fluisteren", "Verbergen", "Shh"] },
    { subject: "Koffie", keywords: ["Boontje", "Cafeïne", "Drank", "Ochtend"] },
    { subject: "Ziek", keywords: ["Koorts", "Dokter", "Bed", "Gezondheid"] },
    { subject: "Vakantie", keywords: ["Reizen", "Vrij", "Zon", "Ontspanning"] }
];