// quizdata_r1_16_22_aangepast.js - 200 Vragen voor 16-22 jarigen

const STANDAARD_R1_POOL = [
    { q: "Wat is de naam van de technologie achter Bitcoin en andere crypto?", a: "Blockchain" },
    { q: "Wat is de naam van de populaire app voor het delen van foto's met filters?", a: "Snapchat" },
    { q: "Wie was de beroemde Amerikaanse burgerrechtenleider?", a: "Martin Luther King Jr." },
    { q: "Wat is de naam van de robot die bevriend raakt met een mens in de film 'Wall-E'?", a: "EVE" },
    { q: "Wat is de naam van het beroemde voetbalstadion van FC Barcelona?", a: "Camp Nou" },
    { q: "Welke game studio bracht 'Cyberpunk 2077' uit?", a: "CD Projekt Red" },
    { q: "In welk jaar viel de Berlijnse Muur?", a: "1989" },
    { q: "Wat is de naam van de grootste oceaan?", a: "Stille Oceaan" },
    { q: "Wat is de naam van de serie over een jonge vrouw die schaakster wordt?", a: "The Queen's Gambit" },
    { q: "Wat is de naam van de grootste vogel die niet kan vliegen?", a: "Struisvogel" },
    { q: "Wat is de naam van de bergketen die door de westkust van Zuid-Amerika loopt?", a: "Andes" },
    { q: "Wat is de naam van het beroemde meer in Schotland waar een monster zou leven?", a: "Loch Ness" },
    { q: "Wie was de beroemde zanger van de band Queen?", a: "Freddie Mercury" },
    { q: "Wat is de naam van het social media platform dat vroeger Twitter heette?", a: "X (of Twitter)" },
    { q: "Wat is de naam van de grootste regenwoud ter wereld?", a: "Amazone" },
    { q: "Welke filmfranchise bevat de personages Tony Stark en Captain America?", a: "Marvel Cinematic Universe (MCU)" },
    { q: "Wat is de eenheid van kracht in het SI-stelsel?", a: "Newton" },
    { q: "Wat is de naam van de theorie die de oorsprong van het universum verklaart?", a: "Big Bang Theorie" },
    { q: "Hoeveel nullen heeft een miljard?", a: "Negen" },
    { q: "Welke coureur won de meeste Formule 1-wereldtitels (samen met Schumacher)?", a: "Lewis Hamilton" },
    { q: "Wat is de valuta van India?", a: "Roepie" },
    { q: "Wat is de naam van de grote kloof in de VS?", a: "Grand Canyon" },
    { q: "Hoeveel spelers heeft een voetbalteam op het veld?", a: "11" },
    { q: "Welke filmstudio maakte de animatiefilms 'Toy Story' en 'Finding Nemo'?", a: "Pixar" },
    { q: "Welke stad organiseerde de Olympische Zomerspelen in 2016?", a: "Rio de Janeiro" },
    { q: "Wie is de auteur van de 'The Hunger Games' boekenreeks?", a: "Suzanne Collins" },
    { q: "Wat is de naam van de grootste maan van Jupiter?", a: "Ganymedes" },
    { q: "Wat is de naam van de populaire app voor het delen van je locatie met vrienden?", a: "Zenly (of Find My/Life360)" },
    { q: "Wat is de naam van de wet die de relatie tussen stroom, spanning en weerstand beschrijft?", a: "Wet van Ohm" },
    { q: "Welke acteur speelt Ken in de Barbie-film uit 2023?", a: "Ryan Gosling" },
    { q: "Wat is de naam van de robot in Star Wars die 'Piep' geluiden maakt en rondrijdt?", a: "R2-D2" },
    { q: "Welke popzangeres had een hit met 'Drivers License'?", a: "Olivia Rodrigo" },
    { q: "Wat is de naam van de grootste waterval ter wereld (hoogte)?", a: "Angel Falls" },
    { q: "Wat is de naam van de president van Rusland?", a: "Vladimir Poetin" },
    { q: "Hoeveel is 7 x 7?", a: "49" },
    { q: "Wat is de naam van het beroemde paleis in Parijs dat een museum is?", "a": "Louvre" },
    { q: "Wat is de naam van het grootste wielerevenement ter wereld?", "a": "Tour de France" },
    { q: "Wat is de snelste transportsnelheid ter wereld (niet-relatief)?", "a": "Lichtsnelheid" },
    { q: "Wat is de naam van de vloeistof die stroomt in een pen?", "a": "Inkt" },
    { q: "Wat is de naam van de ruimtetelescoop die in 2021 werd gelanceerd?", "a": "James Webb" },
    { q: "Wat is de naam van de Britse spion met codenaam 007?", "a": "James Bond" },
    { q: "Wat is de naam van het album van Taylor Swift dat in 2020 werd uitgebracht en zeer populair was?", "a": "Folklore" },
    { q: "Wat is de naam van de ruimtetelescoop die gelanceerd is na de Hubble?", "a": "James Webb" },
    { q: "Wat is de naam van de theorie die de oorsprong van het universum verklaart?", "a": "Big Bang Theorie" },
    { q: "Wat is de naam van de magische school uit 'Harry Potter'?", "a": "Zweinstein" },
    { q: "Wat is de naam van de grootste maan van Jupiter?", "a": "Ganymedes" },
    { q: "Welke popartiest staat bekend om het nummer 'Shape of You'?", "a": "Ed Sheeran" },
    { q: "Welke stad is de thuisbasis van de Colosseum?", "a": "Rome" },
    { q: "Welke band bracht het album 'The Dark Side of the Moon' uit?", "a": "Pink Floyd" },
    { q: "Wat is de naam van de robot die bevriend raakt met een mens in de film 'Wall-E'?", "a": "EVE" },
    { q: "Wat is de valuta van het Verenigd Koninkrijk?", "a": "Pond Sterling" },
    { q: "Welke gamefranchise staat bekend om het 'First-Person Shooter' genre met jaarlijkse releases?", "a": "Call of Duty" },
    { q: "Wat is de naam van de grote kloof in de VS?", "a": "Grand Canyon" },
    { q: "Hoeveel is 20 gedeeld door 0.5?", "a": "40" },
    { q: "Wat is de naam van de grootste zoetwatervis ter wereld?", "a": "Beluga Steur" },
    { q: "Wat is de naam van de tenniscompetitie die in Londen wordt gehouden op gras?", "a": "Wimbledon" },
    { q: "Wat is de naam van de beroemde scheve toren in Italië?", "a": "Toren van Pisa" },
    { q: "Hoe heet het Amerikaanse ministerie dat zich bezighoudt met buitenlandse zaken?", "a": "State Department" },
    { q: "Wat is de naam van de zwaarste planeet in ons zonnestelsel?", "a": "Jupiter" },
    { q: "Wie was de eerste vrouwelijke premier van het Verenigd Koninkrijk?", "a": "Margaret Thatcher" },
    { q: "Wat is de naam van de serie over een jonge vrouw die schaakster wordt?", "a": "The Queen's Gambit" },
    { q: "Wat is de naam van het beroemde meer in Schotland waar een monster zou leven?", "a": "Loch Ness" },
    { q: "Welke regisseur maakte films als 'Pulp Fiction' en 'Kill Bill'?", "a": "Quentin Tarantino" },
    { q: "Wat is de naam van de planeet met de ringen?", "a": "Saturnus" },
    { q: "Welke rapper staat bekend om zijn album 'DAMN.'?", "a": "Kendrick Lamar" },
    { q: "Welke film won in 2019 de meeste Oscars, waaronder Beste Film?", "a": "Green Book" },
    { q: "Wat is de naam van de grootste woestijn ter wereld?", "a": "Sahara" },
    { q: "Hoeveel is 1/3 van 99?", "a": "33" },
    { q: "Wat is de naam van de centrale verwerkingseenheid in een computer?", "a": "CPU (Central Processing Unit)" },
    { q: "Wie zingt het nummer 'Blinding Lights'?", "a": "The Weeknd" },
    { q: "Wat is de naam van de populaire battle royale game van Epic Games?", "a": "Fortnite" },
    { q: "Welke zangeres heeft hits zoals 'Bad Guy' en 'Ocean Eyes'?", "a": "Billie Eilish" },
    { q: "Wie speelde Hermione Granger in de Harry Potter-films?", "a": "Emma Watson" },
    { q: "Wat is 1/4 van 100?", "a": "25" },
    { q: "Wat is de naam van de hoogste berg ter wereld?", "a": "Mount Everest" },
    { q: "Welke coureur won de meeste Formule 1-wereldtitels (samen met Schumacher)?", "a": "Lewis Hamilton" },
    { q: "Hoeveel spelers heeft een basketbalteam op het veld?", "a": "5" },
    { q: "Wie formuleerde de relativiteitstheorie?", "a": "Albert Einstein" },
    { q: "Wat is de naam van de bergketen die door de westkust van Zuid-Amerika loopt?", "a": "Andes" },
    { q: "Wie schreef '1984'?", "a": "George Orwell" },
    { q: "Wat is de naam van de grootste slang ter wereld?", "a": "Groene Anaconda" },
    { q: "Wat is de naam van de grootste vogelspin ter wereld?", "a": "Goliath vogelspin" },
    { q: "Wat is de naam van de grootste vis ter wereld?", "a": "Walvishaai" },
    { q: "Welke film bevat de beroemde quote 'May the Force be with you'?", "a": "Star Wars" },
    { q: "Wat is de naam van de robot in Star Wars die 'Piep' geluiden maakt en rondrijdt?", a: "R2-D2" },
    { q: "Wat is de naam van de technologie achter Bitcoin en andere crypto?", a: "Blockchain" },
    { q: "Welke filmfranchise bevat de personages Tony Stark en Captain America?", a: "Marvel Cinematic Universe (MCU)" },
    { q: "Wat is de naam van de meest verkochte game aller tijden (in één versie)?", a: "Minecraft" },
    { q: "Welke gamebedrijf ontwikkelde 'The Legend of Zelda' en 'Mario'?", a: "Nintendo" },
    { q: "Wat is de naam van de populaire social media app bekend om korte video's?", a: "TikTok" },
    { q: "Welke sport maakt gebruik van de term 'touchdown'?", a: "American Football" },
    { q: "Wat is de valuta van India?", "a": "Roepie" },
    { q: "Wat is de naam van de bergketen die door de westkust van Zuid-Amerika loopt?", "a": "Andes" },
    { q: "Wat is de naam van de grootste maan van Jupiter?", "a": "Ganymedes" },
    { q: "Wat is de naam van de grondlegger van het boeddhisme?", "a": "Siddhartha Gautama (Boeddha)" },
    { q: "Wie schreef 'De metamorfose'?", "a": "Franz Kafka" },
    { q: "Wat is de naam van de grootste regenwoud ter wereld?", "a": "Amazone" },
    { q: "Wat is de naam van het beroemde paleis in Parijs dat een museum is?", "a": "Louvre" },
    { q: "Wat is de naam van de grootste vis ter wereld?", "a": "Walvishaai" },
    { q: "Wat is de naam van de theorie die de oorsprong van het universum verklaart?", "a": "Big Bang Theorie" },
    { q: "Wat is de naam van de snelste transportsnelheid ter wereld (niet-relatief)?", "a": "Lichtsnelheid" },
    { q: "Wat is de naam van de theorie die de oorsprong van het universum verklaart?", "a": "Big Bang Theorie" },
    { q: "Wat is de naam van de grootste oceaan?", "a": "Stille Oceaan" },
    { q: "Wat is de naam van de bergketen die door de westkust van Zuid-Amerika loopt?", "a": "Andes" },
    { q: "Wat is de naam van de grootste slang ter wereld?", "a": "Groene Anaconda" },
    { q: "Wat is de naam van de grootste vogelspin ter wereld?", "a": "Goliath vogelspin" },
    { q: "Welke actrice speelt Wednesday Addams in de gelijknamige Netflix-serie?", "a": "Jenna Ortega" },
    { q: "Wie speelde Hermione Granger in de Harry Potter-films?", "a": "Emma Watson" },
    { q: "Wie is de auteur van de 'The Hunger Games' boekenreeks?", "a": "Suzanne Collins" },
    { q: "Wie is de zangeres van het nummer 'Hello'?", "a": "Adele" },
    { q: "Welke game studio bracht 'Cyberpunk 2077' uit?", "a": "CD Projekt Red" },
    { q: "Welke filmfranchise bevat de personages Tony Stark en Captain America?", "a": "Marvel Cinematic Universe (MCU)" },
    { q: "Welke popartiest staat bekend om het nummer 'Shape of You'?", "a": "Ed Sheeran" },
    { q: "Wat is de naam van de populaire social media app bekend om korte video's?", "a": "TikTok" },
    { q: "Welke streamingdienst is bekend van series als 'Stranger Things' en 'The Crown'?", "a": "Netflix" },
    { q: "Wat is de naam van de magische school uit 'Harry Potter'?", "a": "Zweinstein" },
    { q: "Wie is de zanger van de Nederlandse band Kensington?", "a": "Eloi Youssef" },
    { q: "Wat is de naam van het social media platform dat vroeger Twitter heette?", "a": "X (of Twitter)" },
    { q: "Welk platform is het meest populair voor live game streaming?", "a": "Twitch" },
    { q: "Welke popzangeres had een hit met 'Drivers License'?", "a": "Olivia Rodrigo" },
    { q: "Wat is de voornaam van de zangeres die bekend staat als 'Queen B'?", "a": "Beyoncé" },
    { q: "Welke band is bekend van het nummer 'Smells Like Teen Spirit'?", "a": "Nirvana" },
    { q: "Welke filmstudio maakte de animatiefilms 'Toy Story' en 'Finding Nemo'?", "a": "Pixar" },
    { q: "Wie is de zanger van de band Coldplay?", "a": "Chris Martin" },
    { q: "Wat is de naam van de populaire app voor het delen van je locatie met vrienden?", "a": "Zenly (of Find My/Life360)" },
    { q: "Wat is de naam van de ring die in 'Lord of the Rings' gezocht wordt?", "a": "De Ene Ring" },
    { q: "Welk genre vertegenwoordigt artiest als Tiësto en Martin Garrix?", "a": "EDM (Electronic Dance Music)" },
    { q: "Wat is de naam van de fictieve drug in de serie 'Breaking Bad'?", "a": "Crystal Meth (Blue Sky)" },
    { q: "Welke streamingdienst is eigendom van Amazon?", "a": "Prime Video" },
    { q: "Wie speelde de hoofdrol in 'Titanic'?", "a": "Leonardo DiCaprio" },
    { q: "Wat is de naam van de populaire app voor het delen van foto's met filters?", "a": "Snapchat" },
    { q: "Welke band bracht het album 'The Dark Side of the Moon' uit?", "a": "Pink Floyd" },
    { q: "Wat is de meest verkochte game aller tijden (in één versie)?", "a": "Minecraft" },
    { q: "In welke fictieve stad speelt de Batman zich af?", "a": "Gotham City" },
    { q: "Wie is de auteur van de 'The Hunger Games' boekenreeks?", "a": "Suzanne Collins" },
    { q: "Wat is de naam van de populaire app voor het delen van je locatie met vrienden?", "a": "Zenly (of Find My/Life360)" },
    { q: "Welke popartiest staat bekend om het nummer 'Shape of You'?", "a": "Ed Sheeran" },
    { q: "Wat is de naam van de robot die bevriend raakt met een mens in de film 'Wall-E'?", "a": "EVE" },
    { q: "Welke artiest had een hit met 'As It Was' in 2022?", "a": "Harry Styles" },
    { q: "Wat is de naam van de fictieve planeet van Superman?", "a": "Krypton" },
    { q: "Wie speelde Hermione Granger in de Harry Potter-films?", "a": "Emma Watson" },
    { q: "Welk platform is het meest populair voor live game streaming?", "a": "Twitch" },
    { q: "Wat is de naam van de serie over een jonge vrouw die schaakster wordt?", "a": "The Queen's Gambit" },
    { q: "Wie is de zangeres van het nummer 'Hello'?", "a": "Adele" },
    { q: "Welke film won in 2019 de meeste Oscars, waaronder Beste Film?", "a": "Green Book" },
    { q: "Welke band is bekend van het nummer 'Smells Like Teen Spirit'?", "a": "Nirvana" },
    { q: "Wat is de naam van de fictieve school in de serie 'Glee'?", "a": "William McKinley High School" },
    { q: "Welke rapper staat bekend om zijn album 'DAMN.'?", "a": "Kendrick Lamar" },
    { q: "Wat is de naam van de Disney-prinses die haar stem verliest?", "a": "Ariël" },
    { q: "Welke game studio bracht 'Cyberpunk 2077' uit?", "a": "CD Projekt Red" },
    { q: "Wie schreef de roman 'The Fault in Our Stars' (Een Weeffout in Onze Sterren)?", "a": "John Green" },
    { q: "Welk muziekgenre ontstond in Jamaica en is populair gemaakt door Bob Marley?", "a": "Reggae" },
    { q: "Wat is de naam van de fictieve stad waarin 'SpongeBob SquarePants' leeft?", "a": "Bikini Bottom" },
    { q: "Wie is de zanger van de Nederlandse band Kensington?", "a": "Eloi Youssef" },
    { q: "Welke film bevat de beroemde quote 'May the Force be with you'?", "a": "Star Wars" },
    { q: "Wat is de naam van de populaire battle royale game van Epic Games?", "a": "Fortnite" },
    { q: "Wie is de regisseur van de film 'Inception' en 'Oppenheimer'?", "a": "Christopher Nolan" },
    { q: "Welke actrice speelt Wednesday Addams in de gelijknamige Netflix-serie?", "a": "Jenna Ortega" },
    { q: "Wat is de naam van het album van Taylor Swift dat in 2020 werd uitgebracht en zeer populair was?", "a": "Folklore" },
    { q: "Welk personage in de Mario-games draagt een groen shirt en is Mario's broer?", "a": "Luigi" },
    { q: "Wat is de naam van de technologie achter Bitcoin en andere crypto?", "a": "Blockchain" },
    { q: "Welke planeet staat bekend als de 'Rode Planeet'?", "a": "Mars" },
    { q: "Wie formuleerde de relativiteitstheorie?", "a": "Albert Einstein" },
    { q: "Wat is de naam van de grootste maan van Jupiter?", "a": "Ganymedes" },
    { q: "Wat is de eenheid van kracht in het SI-stelsel?", "a": "Newton" },
    { q: "Wat is de naam van de ruimtetelescoop die in 2021 werd gelanceerd?", "a": "James Webb" },
    { q: "Wat is de kleinste bouwsteen van materie?", "a": "Quark (of lepton)" },
    { q: "Welk orgaan filtert bloed en verwijdert gifstoffen uit het lichaam?", "a": "Lever" },
    { q: "Wat is de snelste transportsnelheid ter wereld (niet-relatief)?", "a": "Lichtsnelheid" },
    { q: "Hoeveel tanden heeft een volwassen mens (inclusief verstandskiezen)?", "a": "32" },
    { q: "Wat is de naam van de centrale verwerkingseenheid in een computer?", "a": "CPU (Central Processing Unit)" },
    { q: "Wat is de naam van de grootste oceaan?", "a": "Stille Oceaan" },
    { q: "Wat is de naam van de laag in de atmosfeer die ons beschermt tegen UV-straling?", "a": "Ozonlaag" },
    { q: "Wat is de naam van de supercontinent dat 200 miljoen jaar geleden bestond?", "a": "Pangea" },
    { q: "Wat is het grootste interne orgaan van het menselijk lichaam?", "a": "Lever" },
    { q: "Welke eenheid wordt gebruikt om computeropslag te meten?", "a": "Byte" },
    { q: "Wat is de naam van de theorie die de oorsprong van het universum verklaart?", "a": "Big Bang Theorie" },
    { q: "Wat is de naam van het kleinste botje in het menselijk lichaam?", "a": "Stijgbeugel" },
    { q: "Wat is de valuta van het Verenigd Koninkrijk?", "a": "Pond Sterling" },
    { q: "Wat is de naam van de wet die de relatie tussen stroom, spanning en weerstand beschrijft?", "a": "Wet van Ohm" },
    { q: "Wat is de naam van de wetenschapper die penicilline ontdekte?", "a": "Alexander Fleming" },
    { q: "Welke planeet heeft de meeste manen?", "a": "Saturnus" },
    { q: "Wat is de naam van het gas dat de ozonlaag aantastte (nu verboden)?", "a": "CFK's (Chloorfluorkoolwaterstoffen)" },
    { q: "Wat is de munteenheid van Turkije?", "a": "Turkse Lira" },
    { q: "In welk jaar viel de Berlijnse Muur?", "a": "1989" },
    { q: "Welke rivier stroomt door Londen?", "a": "Theems" },
    { q: "Welke stad is de thuisbasis van de Colosseum?", "a": "Rome" },
    { q: "Wat is de naam van de bergketen die door de westkust van Zuid-Amerika loopt?", "a": "Andes" },
    { q: "Wie was de president van de VS tijdens de aanslagen op 11 september 2001?", "a": "George W. Bush" },
    { q: "In welk jaar begon de Eerste Wereldoorlog?", "a": "1914" },
    { q: "Wat is de hoogste berg ter wereld?", "a": "Mount Everest" },
    { q: "Wat is de hoofdstad van IJsland?", "a": "Reykjavik" },
    { q: "Wat was de naam van de koude periode na de Tweede Wereldoorlog tussen de VS en de Sovjet-Unie?", "a": "Koude Oorlog" },
    { q: "In welk land zijn de piramides van Gizeh te vinden?", "a": "Egypte" },
    { q: "Wat is de munteenheid van Japan?", "a": "Yen" },
    { q: "Wat is de hoofdstad van Australië?", "a": "Canberra" },
    { q: "Wie schilderde de Mona Lisa?", "a": "Leonardo da Vinci" },
    { q: "Welke Nederlandse schilder sneed zijn oor af?", "a": "Vincent van Gogh" },
    { q: "Wat is de naam van de grote kloof in de VS?", "a": "Grand Canyon" },
    { q: "Wie was de eerste man die de aarde rondzeilde?", "a": "Ferdinand Magellaan" },
    { q: "Wat is de hoofdstad van Rusland?", "a": "Moskou" },
    { q: "In welk land ligt de Nijl?", "a": "Egypte" },
    { q: "Wat is de munteenheid van China?", "a": "Yuan (Renminbi)" },
    { q: "Wat is de naam van het beroemde paleis in Parijs dat een museum is?", "a": "Louvre" },
    { q: "Wat is de naam van de langste rivier in Zuid-Amerika?", "a": "Amazone" },
    { q: "Welke bergketen loopt door Zwitserland en Oostenrijk?", "a": "Alpen" },
    { q: "Wat is de hoofdstad van Peru?", "a": "Lima" },
    { q: "Wat is de valuta van Zwitserland?", "a": "Zwitserse Frank" },
    { q: "Wie was de grondlegger van het communisme?", "a": "Karl Marx" },
    { q: "Wat is de hoofdstad van India?", "a": "New Delhi" },
    { q: "Wie was de Romeinse keizer die christenen vervolgde?", "a": "Nero" },
    { q: "Wat is de hoofdstad van Zuid-Korea?", "a": "Seoel" },
    { q: "Hoeveel continenten zijn er op aarde?", "a": "Zeven" },
    { q: "Wat is de naam van de kleinste oceaan?", "a": "Noordelijke IJszee" },
    { q: "Wat is de hoofdstad van Marokko?", "a": "Rabat" },
    { q: "Welke stad staat bekend om de Eiffeltoren?", "a": "Parijs" },
    { q: "Wat is de naam van de bergketen die door Noord-Amerika loopt?", "a": "Rocky Mountains" },
    { q: "Wat is de hoofdstad van Thailand?", "a": "Bangkok" },
    { q: "Wie was de beroemde Amerikaanse burgerrechtenleider?", "a": "Martin Luther King Jr." },
    { q: "In welk jaar werd de euro officieel als contant geld ingevoerd?", "a": "2002" },
    { q: "Wat is de naam van de grootste waterval ter wereld (hoogte)?", "a": "Angel Falls" },
    { q: "Hoeveel spelers heeft een voetbalteam op het veld?", "a": "11" },
    { q: "Hoeveel spelers heeft een basketbalteam op het veld?", "a": "5" },
    { q: "Welk land won de FIFA Wereldbeker in 2014?", "a": "Duitsland" },
    { q: "Wie is de topscorer aller tijden in de Champions League (per 2023)?", "a": "Cristiano Ronaldo" },
    { q: "Wat is de naam van de tenniscompetitie die in Londen wordt gehouden op gras?", "a": "Wimbledon" },
    { q: "Welke coureur won de meeste Formule 1-wereldtitels (samen met Schumacher)?", "a": "Lewis Hamilton" },
    { q: "Wat is de naam van het grootste wielerevenement ter wereld?", "a": "Tour de France" },
    { q: "Hoeveel rondes telt een Olympische zwemcompetitie voor 50 meter vrije slag?", "a": "1" },
    { q: "Wat is de maximale score die je kunt behalen bij een 9-dart finish in Darts?", "a": "501" },
    { q: "Welke stad organiseerde de Olympische Zomerspelen in 2016?", "a": "Rio de Janeiro" },
    { q: "Wat is een 'hole-in-one' in golf?", "a": "De bal in één slag in de hole slaan" },
    { q: "Wat is de naam van de beroemde basketballer met rugnummer 23 voor de Chicago Bulls?", "a": "Michael Jordan" },
    { q: "Hoe lang duurt een reguliere wedstrijd in het American Football (in minuten)?", "a": "60 (vier kwarten van 15)" },
    { q: "Welke sport maakt gebruik van de term 'touchdown'?", "a": "American Football" },
    { q: "Wat is de naam van de Australische open tennistoernooi?", "a": "Australian Open" },
    { q: "Welke twee teams strijden om 'De Klassieker' in Nederland?", "a": "Ajax en Feyenoord" },
    { q: "Hoeveel seconden is de standaard duur van een bokswedstrijdronde?", "a": "180 (3 minuten)" },
    { q: "Welke atleet verbrak in 2009 het wereldrecord op de 100 meter sprint?", "a": "Usain Bolt" },
    { q: "Wat is de naam van het beroemde voetbalstadion van FC Barcelona?", "a": "Camp Nou" },
    { q: "Wat is de naam van het toernooi dat jaarlijks in Azië wordt gehouden met de beste e-sportsteams (bijv. in League of Legends)?", "a": "Worlds (World Championship)" },
    { q: "Hoeveel nullen heeft een miljard?", "a": "Negen" },
    { q: "Wat is de valuta van India?", "a": "Roepie" },
    { q: "Wat is de naam van de vloeistof die stroomt in een pen?", "a": "Inkt" },
    { q: "Wat is de naam van de president van Rusland?", "a": "Vladimir Poetin" },
    { q: "Hoe heet het Amerikaanse ministerie dat zich bezighoudt met buitenlandse zaken?", "a": "State Department" },
    { q: "Hoeveel is 100 gedeeld door 5?", "a": "20" },
    { q: "Wie was de eerste vrouwelijke premier van het Verenigd Koninkrijk?", "a": "Margaret Thatcher" },
    { q: "Wat is de naam van de grootste regenwoud ter wereld?", "a": "Amazone" },
    { q: "Wat is de naam van het beroemde meer in Schotland waar een monster zou leven?", "a": "Loch Ness" },
    { q: "Wie schreef '1984'?", "a": "George Orwell" },
    { q: "Hoeveel is 7 x 7?", "a": "49" },
    { q: "Wat is de naam van de grondlegger van het boeddhisme?", "a": "Siddhartha Gautama (Boeddha)" },
    { q: "Welk orgaan reguleert de bloedsuikerspiegel?", "a": "Alvleesklier" },
    { q: "Wie was de beroemde Oostenrijkse psychiater die de psychoanalyse ontwikkelde?", "a": "Sigmund Freud" },
    { q: "Wat is de naam van de beroemde Italiaanse ontdekkingsreiziger die naar China reisde?", "a": "Marco Polo" },
    { q: "Welke kleur is het symbool voor hoop?", "a": "Groen" },
    { q: "Wat is de naam van de hoogste waterval ter wereld?", "a": "Angel Falls" },
    { q: "Wie schreef 'De Drie Musketiers'?", "a": "Alexandre Dumas" },
    { q: "Wat is de naam van de grootste maan van Saturnus?", "a": "Titan" },
    { q: "Hoeveel is 1/2 van 50?", "a": "25" },
    { q: "Welk orgaan reguleert de lichaamstemperatuur?", "a": "Hypothalamus (in de hersenen)" },
    { q: "Wie schreef 'De metamorfose'?", "a": "Franz Kafka" },
    { q: "Hoeveel is 20 gedeeld door 0.5?", "a": "40" },
    { q: "Wat is de naam van de grootste zoetwatervis ter wereld?", "a": "Beluga Steur" },
    { q: "Wat is 1/3 van 99?", "a": "33" },
    { q: "Wie schreef 'Moby Dick'?", "a": "Herman Melville" },
    { q: "Wat is de naam van de grootste slang ter wereld?", "a": "Groene Anaconda" },
    { q: "Hoeveel is 50 x 50?", "a": "2500" },
    { q: "Wie was de beroemde Amerikaanse president tijdens de Tweede Wereldoorlog?", "a": "Franklin D. Roosevelt" },

    // --- NIEUWE VRAGEN (77 totaal) ---
    // SPORT (20)
    { q: "In welke sport wordt de term 'forehand' en 'backhand' gebruikt?", a: "Tennis" },
    { q: "Welk land organiseerde het WK Voetbal in 2010?", a: "Zuid-Afrika" },
    { q: "Wat is de bijnaam van het Belgisch nationaal voetbalelftal?", a: "De Rode Duivels" },
    { q: "In welke sport kun je een 'strike' gooien?", a: "Bowling" },
    { q: "Wat is de naam van de beroemde basketbalcompetitie in de VS?", a: "NBA (National Basketball Association)" },
    { q: "Hoeveel sets moet een speler winnen om een grandslam-tennisfinale te winnen (bij de mannen)?", a: "Drie" },
    { q: "Wie wordt vaak beschouwd als de beste voetballer aller tijden (samen met Pelé)?", a: "Lionel Messi (of Maradona)" },
    { q: "Wat is de naam van de Belgische wielerklassieker die ook 'Vlaanderens Mooiste' wordt genoemd?", a: "Ronde van Vlaanderen" },
    { q: "Welke kleur kaart krijgt een speler in voetbal voor een zware overtreding en moet hij het veld verlaten?", a: "Rood" },
    { q: "Wat is de naam van de sport die wordt gespeeld met een puck en sticks op ijs?", a: "IJshockey" },
    { q: "Hoeveel gaten telt een standaard golfbaan?", a: "18" },
    { q: "Wat is de naam van de beroemde Amerikaanse zwemmer met 23 Olympische gouden medailles?", a: "Michael Phelps" },
    { q: "Welke sport kent termen als 'halfpipe' en 'ollie'?", a: "Skateboarden (of Snowboarden)" },
    { q: "Welk land is de bakermat van de sport judo?", a: "Japan" },
    { q: "Wat is een 'triple-double' in basketbal?", a: "Tien of meer in drie statistische categorieën" },
    { q: "In welke raceklasse rijdt de Belgische coureur Stoffel Vandoorne (als voormalig F1-coureur)?", a: "Formule E (of WEC/Hypercar)" },
    { q: "Wat is de naam van de sport waarbij je met een speer naar een doel gooit (darts, maar als Olympische sport)?", a: "Speerwerpen" },
    { q: "Welke club won de meeste keren de UEFA Champions League?", a: "Real Madrid" },
    { q: "Wat is de naam van de atleet die het wereldrecord polsstokhoogspringen bezit (per 2024)?", a: "Armand 'Mondo' Duplantis" },
    { q: "Wat is de naam van de sport waarbij je met een boog en pijlen op een doel schiet?", a: "Boogschieten" },

    // MUZIEK (20)
    { q: "Wie is de leadzanger van de Britse band Arctic Monkeys?", a: "Alex Turner" },
    { q: "Welke Belgische zangeres werd beroemd met het nummer 'Fever'?", a: "Angèle" },
    { q: "Wat is de naam van het instrument met 88 toetsen dat vaak wordt gebruikt in klassieke muziek?", a: "Piano" },
    { q: "Welke artiest is bekend van het nummer 'Bohemian Rhapsody'?", a: "Queen" },
    { q: "Wat is de naam van de Nederlandse DJ die hits scoorde als 'Animals' en 'In the Name of Love'?", a: "Martin Garrix" },
    { q: "Wat is de naam van het muziekgenre dat in de jaren '70 in New York ontstond en gekenmerkt wordt door MC's en DJ's?", a: "Hiphop" },
    { q: "Welke zangeres brak in 2023 door met het nummer 'Ella Elle L'a' (cover)?", a: "Pommelien Thijs" },
    { q: "Wat is de naam van de K-popgroep die hits heeft als 'Dynamite' en 'Butter'?", a: "BTS" },
    { q: "Wie is de zanger van de Amerikaanse band Foo Fighters?", a: "Dave Grohl" },
    { q: "Wat is de naam van het grootste jaarlijkse Belgische muziekfestival in Werchter?", a: "Rock Werchter" },
    { q: "Welke Amerikaanse popster staat bekend om de nummers 'Bad Romance' en 'Poker Face'?", "a": "Lady Gaga" },
    { q: "Welke Belgische artiest bracht het album 'Racine Carrée' uit?", "a": "Stromae" },
    { q: "In welk jaar vond het Woodstock festival plaats?", "a": "1969" },
    { q: "Wat is de naam van het muzikale symbool dat een noot met halve waarde verhoogt?", "a": "Kruis (#)" },
    { q: "Welke Amerikaanse rapper staat bekend als 'Slim Shady'?", "a": "Eminem" },
    { q: "Wat is de naam van de popzangeres die bekend staat om haar krachtige stem en het nummer 'Chandelier'?", "a": "Sia" },
    { q: "Welke band maakte in 2000 een comeback met het nummer 'It's My Life'?", "a": "Bon Jovi" },
    { q: "Wat is de naam van de zangeres die het nummer 'Wrecking Ball' zingt?", "a": "Miley Cyrus" },
    { q: "Welke Nederlandse rapper staat bekend om zijn maatschappijkritische teksten en albums als 'Lobi Da Basi'?", "a": "Typhoon" },
    { q: "Wat is de naam van het genre dat klassieke elementen mixt met elektronische beats (vaak voor films)?", "a": "Neoklassieke muziek (of Cinematic)" },

    // BEKENDE (VLAAMSE) FILMS/SERIES (20)
    { q: "Wat is de naam van de fictieve drug in de Vlaamse film 'Patser'?", a: "White T." },
    { q: "In welke Vlaamse serie staat een groep vrienden centraal die het kotleven ontdekken?", a: "Dertigers" },
    { q: "Wat is de naam van de Vlaamse film over een bankoverval waarbij de daders ontsnappen via de riolering?", a: "Rundskop" },
    { q: "Wie is de hoofdrolspeler in de Vlaamse serie 'Salamander'?", a: "Filip Peeters" },
    { q: "Wat is de naam van de populaire Vlaamse misdaadserie over een familie van motorcrossers?", a: "Eigen Kweek" },
    { q: "Welke Vlaamse komedie/drama film uit 2018 won de publieksprijs op Film Fest Gent?", a: "Niet Schieten" },
    { q: "Wat is de naam van de Vlaamse jeugdserie over tieners die in een internaat wonen en mysteries oplossen?", a: "Ghost Rockers" },
    { q: "Wie is de regisseur van de Vlaamse film 'De Zaak Alzheimer'?", a: "Erik Van Looy" },
    { q: "Wat is de naam van de Vlaamse serie over een undercoveroperatie rond de haven van Antwerpen?", a: "GR5" },
    { q: "Welke Vlaamse film uit 2000 met Tom Van Landuyt als drugsbaron wordt als een cultklassieker beschouwd?", a: "Ad fundum" },
    { q: "Wat is de naam van de Vlaamse serie waarin een vermoorde vrouw terugkeert als geest om haar moordenaar te vinden?", "a": "Beau Séjour" },
    { q: "Wie speelde de rol van 'Safety First'-eigenaar Luc in de gelijknamige Vlaamse sitcom?", "a": "Bruno Vanden Broecke" },
    { q: "Wat is de naam van de Vlaamse serie waarin een jury zich moet buigen over de zaak van een moord verdachte?", "a": "De twaalf" },
    { q: "Welke Vlaamse film uit 2007 volgt het leven van een jonge man die uit de kast komt?", "a": "Noordzee, Texas" },
    { q: "Wat is de naam van de Vlaamse soap over een jonge, onzekere vrouw die gaat werken in een modebedrijf?", "a": "Sara" },
    { q: "Wie speelt de hoofdrol in de Vlaamse serie 'Over Water' over de drugshandel in de haven?", "a": "Tom Van Dyck" },
    { q: "Wat is de naam van de filmreeks over de stuntelige voetbalploeg F.C. De Kampioenen?", "a": "F.C. De Kampioenen" },
    { q: "In welke Vlaamse serie speelt Maaike Cafmeyer de rol van psycholoog/profiler?", "a": "Professor T." },
    { q: "Welke Vlaamse film met Jan Decleir gaat over de sociale strijd van een priester-politicus in Aalst?", "a": "Daens" },
    { q: "Welke Vlaamse film uit 2012 gaat over de vriendschap tussen twee jongens in een asielcentrum?", "a": "Hasta La Vista" },

    // ETEN (17)
    { q: "Welk land staat bekend om de culinaire uitvinding van pizza?", a: "Italië" },
    { q: "Wat is de naam van het gerecht dat bestaat uit een dunne laag deeg met beleg, gebakken in een steenoven (niet pizza)?", a: "Flammkuchen" },
    { q: "Wat is het hoofdingrediënt van hummus?", a: "Kikkererwten" },
    { q: "Wat is de naam van de Japanse methode om vis rauw te serveren, vaak op rijst?", a: "Sushi" },
    { q: "Welke groente is het hoofdingrediënt van traditionele gazpacho?", a: "Tomaat" },
    { q: "Wat is de naam van de beroemde Belgische chocolade die in een kegelvorm wordt gemaakt en vaak met een vulling?", a: "Praline" },
    { q: "Welke saus is het hoofdingrediënt in de klassieke spaghetti carbonara?", a: "Ei (en Pecorino/Guanciale)" },
    { q: "Wat is de naam van het Franse gerecht van eieren, melk en kaas in een korst?", a: "Quiche" },
    { q: "Welke plant wordt gebruikt om tequila te maken?", a: "Blauwe agave" },
    { q: "Wat is de naam van de kruidige mix van vlees, groenten en rijst uit Spanje?", a: "Paella" },
    { q: "Wat is de naam van de beroemde Belgische frietsaus op basis van eigeel en azijn?", a: "Mayonaise" },
    { q: "Uit welk land komt de Moussaka?", a: "Griekenland" },
    { q: "Wat is de naam van het traditionele Chinese gerecht dat wordt gestoomd in bamboemandjes?", a: "Dim sum" },
    { q: "Wat is de naam van de kaassoort die in Zwitserland vaak wordt gesmolten en geserveerd met aardappelen en augurken?", a: "Raclette" },
    { q: "Welke citrusvrucht wordt vaak gebruikt om een 'Mojito' cocktail te maken?", a: "Limoen" },
    { q: "Wat is de naam van het Belgische bier dat wordt gebrouwen in abdijen?", a: "Trappistenbier (of Abdijbier)" },
    { q: "Wat is het hoofdingrediënt van een traditionele Tiramisu?", a: "Mascarpone" }
];