// quizdata_r2.js - Complete data voor Ronde 2 (Puzzel) - 500 Items

var STANDAARD_R2_POOL = [
    // --- Oorspronkelijke Pool (Opgekuist) ---
    { answer: "Voetbal", clues: ["Bal", "Met 11", "Rode kaart", "Stadion"] },
    { answer: "Tennis", clues: ["Racket", "Net", "Set", "Gravel"] },
    { answer: "Wielrennen", clues: ["Fiets", "Peloton", "Gele trui", "Kasseien"] },
    { answer: "Harry Potter", clues: ["Zweinstein", "Uil", "Dreuzels", "Onzichtbaarheidsmantel"] },
    { answer: "James Bond", clues: ["007", "Martini", "MI6", "Aston Martin"] },
    { answer: "Star Wars", clues: ["Lightsaber", "The Force", "Darth Vader", "Jedi"] },
    { answer: "Appel", clues: ["Fruit", "Boom", "Rood/Groen", "Sneeuwwitje"] },
    { answer: "Banaan", clues: ["Geel", "Krom", "Aap", "Smoothie"] },
    { answer: "Peer", clues: ["Fruit", "Lamp", "Vorm", "Stoof"] },
    { answer: "Brussel", clues: ["Hoofdstad", "België", "Manneken Pis", "Atomium"] },
    { answer: "Antwerpen", clues: ["Haven", "Diamant", "Zoo", "Mode"] },
    { answer: "Gent", clues: ["9000", "Strop", "Gravensteen", "Feesten"] },
    { answer: "Olifant", clues: ["Slurf", "Groot", "Grijs", "Savanne"] },
    { answer: "Zebra", clues: ["Strepen", "Paard", "Savanne", "Zwart-wit"] },
    { answer: "Leeuw", clues: ["Koning", "Manen", "Kat", "Jacht"] },
    { answer: "Apple", clues: ["iPhone", "Macbook", "Steve Jobs", "Logo"] },
    { answer: "Google", clues: ["Zoekmachine", "Android", "Alphabet", "Gmail"] },
    { answer: "Microsoft", clues: ["Windows", "Bill Gates", "Office", "Xbox"] },
    { answer: "Gitaar", clues: ["Snaren", "Muziek", "Rock", "Plectrum"] },
    { answer: "Piano", clues: ["Toetsen", "Zwart-wit", "Vleugel", "Klassiek"] },

    // --- 🌍 Geografie ---
    { answer: "Parijs", clues: ["Frankrijk", "Eiffeltoren", "Liefde", "Seine"] },
    { answer: "Rome", clues: ["Italië", "Colosseum", "Vaticaanstad", "Gladiatoren"] },
    { answer: "Amsterdam", clues: ["Grachten", "Nederland", "Fietsen", "Rijksmuseum"] },
    { answer: "Tokio", clues: ["Japan", "Hoofdstad", "Druk", "Sushi"] },
    { answer: "Rio de Janeiro", clues: ["Brazilië", "Carnaval", "Christusbeeld", "Strand"] },
    { answer: "Londen", clues: ["Verenigd Koninkrijk", "Big Ben", "Torenbrug", "Thee"] },
    { answer: "Berlijn", clues: ["Duitsland", "Muur", "Brandenburger Tor", "Hoofdstad"] },
    { answer: "New York", clues: ["Vrijheidsbeeld", "Big Apple", "Manhattan", "Times Square"] },
    { answer: "Spanje", clues: ["Madrid", "Tapas", "Stierenvechten", "Iberisch Schiereiland"] },
    { answer: "Australië", clues: ["Kangoeroe", "Sydney", "Down Under", "Groot Barrièrerif"] },

    // --- 🎵 Muziek & Instrumenten ---
    { answer: "Drumstel", clues: ["Ritme", "Stokken", "Bekken", "Percussie"] },
    { answer: "Madonna", clues: ["Queen of Pop", "Material Girl", "Blond", "Verenigde Staten"] },
    { answer: "The Beatles", clues: ["Liverpool", "Vier", "Yellow Submarine", "Lennon"] },
    { answer: "Saxofoon", clues: ["Blaasinstrument", "Jazz", "Koper", "Riet"] },
    { answer: "Queen", clues: ["Bohemian Rhapsody", "Freddie Mercury", "Rock", "Gitaar"] },
    { answer: "Viool", clues: ["Strijkinstrument", "Klassiek", "Hout", "Vier snaren"] },
    { answer: "Adele", clues: ["Zangeres", "Hello", "21", "Groot-Brittannië"] },
    { answer: "Trompet", clues: ["Koper", "Blaasinstrument", "Jazz", "Klep"] },
    { answer: "Elvis Presley", clues: ["King", "Rock 'n Roll", "Memphis", "Witte pak"] },
    { answer: "Michael Jackson", clues: ["King of Pop", "Thriller", "Moonwalk", "Handschoen"] },

    // --- 🍽️ Eten & Drinken ---
    { answer: "Pizza", clues: ["Italië", "Kaas", "Oven", "Rond"] },
    { answer: "Koffie", clues: ["Boontje", "Cafeïne", "Ochtend", "Zwart/Melk"] },
    { answer: "Chocolade", clues: ["Cacao", "Bruin", "Zwitserland/België", "Zoet"] },
    { answer: "Hamburger", clues: ["Broodje", "Vlees", "Fastfood", "Amerika"] },
    { answer: "Aardappel", clues: ["Knol", "Friet", "Jassen", "Zuid-Amerika"] },
    { answer: "Pasta", clues: ["Deeg", "Spaghetti", "Italië", "Saus"] },
    { answer: "Tomaat", clues: ["Rood", "Groente/Fruit", "Soep", "Salade"] },
    { answer: "Kaas", clues: ["Melk", "Gat", "Gouds", "Boterham"] },
    { answer: "Bier", clues: ["Alcohol", "Gerst", "Schuim", "Koud"] },
    { answer: "Wafel", clues: ["België", "Stroop", "Suiker", "Oven"] },

    // --- 💡 Tech & Wetenschap ---
    { answer: "Zwaartekracht", clues: ["Newton", "Valt", "Aarde", "Massa"] },
    { answer: "Internet", clues: ["WWW", "Browser", "Connectie", "Wereldwijd"] },
    { answer: "Telescoop", clues: ["Sterren", "Verre", "Galaxie", "Kijken"] },
    { answer: "Robot", clues: ["Automatisering", "Metaal", "Programma", "Toekomst"] },
    { answer: "DNA", clues: ["Erfelijk", "Dubbele Helix", "Genen", "Biologie"] },
    { answer: "Vulkaan", clues: ["Lava", "Berg", "Eruptie", "Krater"] },
    { answer: "Zuurstof", clues: ["Ademen", "Gas", "O2", "Water"] },
    { answer: "Batterij", clues: ["Stroom", "Opladen", "Energie", "Plus/Min"] },
    { answer: "Mars", clues: ["Rode planeet", "Aarde", "Rover", "God van de Oorlog"] },
    { answer: "Fotosynthese", clues: ["Planten", "Zonlicht", "Groen", "Energie"] },

    // --- 🎬 Film & TV ---
    { answer: "Titanic", clues: ["Schip", "Zinken", "DiCaprio", "IJsberg"] },
    { answer: "Lord of the Rings", clues: ["Tolkien", "Midden-Aarde", "Ring", "Hobbit"] },
    { answer: "Friends", clues: ["Central Perk", "New York", "Zes", "Sitcom"] },
    { answer: "Jurassic Park", clues: ["Dinosaurussen", "Eiland", "Steven Spielberg", "Mosquito"] },
    { answer: "Mulan", clues: ["Disney", "China", "Vrouw", "Draak"] },
    { answer: "Avatar", clues: ["Blauw", "Na'vi", "Pandora", "James Cameron"] },
    { answer: "The Godfather", clues: ["Maffia", "Italië", "Corleone", "Marlon Brando"] },
    { answer: "Stranger Things", clues: ["Jaren '80", "Upside Down", "Kids", "Netflix"] },
    { answer: "The Crown", clues: ["Koningshuis", "Elizabeth", "Netflix", "Engeland"] },
    { answer: "Frozen", clues: ["Disney", "IJs", "Elsa", "Laat Los"] },

    // --- 🦁 Dieren ---
    { answer: "Pinguïn", clues: ["Zuidpool", "Vogel", "Zwemmen", "Zwart-wit"] },
    { answer: "Vleermuis", clues: ["Vliegt", "Nacht", "Zoogdier", "Echo"] },
    { answer: "Dolfijn", clues: ["Zee", "Intelligent", "Springen", "Zoogdier"] },
    { answer: "Kikker", clues: ["Amfibie", "Springt", "Groen", "Kwak"] },
    { answer: "Eekhoorn", clues: ["Boom", "Noot", "Staart", "Herfst"] },
    { answer: "Tijger", clues: ["Strepen", "Kat", "Azië", "Oranje"] },
    { answer: "Hond", clues: ["Vriend", "Blaffen", "Viervoeter", "Trouw"] },
    { answer: "Kat", clues: ["Miauwen", "Negen levens", "Spinnen", "Jagen"] },
    { answer: "Papegaai", clues: ["Praten", "Kleurrijk", "Tropisch", "Kromme snavel"] },
    { answer: "Haai", clues: ["Tanden", "Oceaan", "Groot", "Roofvis"] },

    // --- 🏰 Historische Figuren ---
    { answer: "Napoleon", clues: ["Frankrijk", "Keizer", "Waterloo", "Klein"] },
    { answer: "Albert Einstein", clues: ["E=mc²", "Duitsland", "Relativiteit", "Natuurkundige"] },
    { answer: "Leonardo da Vinci", clues: ["Mona Lisa", "Uitvinder", "Italiaans", "Renaissance"] },
    { answer: "Cleopatra", clues: ["Egypte", "Koningin", "Nijl", "Ptolemaeën"] },
    { answer: "Julius Caesar", clues: ["Rome", "Generaal", "Dictator", "Idus van maart"] },
    { answer: "Winston Churchill", clues: ["Groot-Brittannië", "Premier", "WO II", "Sigaar"] },
    { answer: "Vincent van Gogh", clues: ["Schilder", "Oor", "Zonnebloemen", "Nederlander"] },
    { answer: "Nelson Mandela", clues: ["Zuid-Afrika", "Apartheid", "President", "Robbeneiland"] },
    { answer: "Marco Polo", clues: ["Reiziger", "Venetië", "Zijderoute", "China"] },
    { answer: "Isaac Newton", clues: ["Zwaartekracht", "Appel", "Engels", "Drie wetten"] },
    { answer: "Galileo Galilei", clues: ["Sterren", "Telescoop", "Italië", "Kerk"] },
    { answer: "Marie Curie", clues: ["Polonium", "Radioactiviteit", "Nobelprijs", "Vrouw"] },
    { answer: "Abraham Lincoln", clues: ["Amerika", "President", "Burgeroorlog", "Emancipatie"] },
    { answer: "Mozart", clues: ["Componist", "Oostenrijk", "Klassiek", "Wonderkind"] },
    { answer: "Christoffel Columbus", clues: ["Ontdekker", "Amerika", "Schepen", "1492"] },
    { answer: "Jeanne d'Arc", clues: ["Frankrijk", "Maagd van Orléans", "Oorlog", "Brandstapel"] },
    { answer: "Plato", clues: ["Filosoof", "Oud-Grieks", "Socrates", "Ideeënleer"] },
    { answer: "Mahatma Gandhi", clues: ["India", "Geweldloos", "Onafhankelijkheid", "Zoutmars"] },
    { answer: "Martin Luther King Jr.", clues: ["Amerika", "Rechten", "I Have a Dream", "Burgerrechten"] },
    { answer: "Tutenchamun", clues: ["Farao", "Graf", "Egypte", "Jong"] },

    // --- ⚽ Sporten & Termen ---
    { answer: "Basketbal", clues: ["Net", "Dribbelen", "Vijf", "NBA"] },
    { answer: "Zwemmen", clues: ["Water", "Slag", "Badpak", "Olympisch"] },
    { answer: "Golf", clues: ["Club", "Hole", "Tee", "Balletje"] },
    { answer: "Honkbal", clues: ["Amerika", "Bat", "Pitcher", "Home run"] },
    { answer: "Curling", clues: ["IJs", "Bezem", "Schijf", "Schotland"] },
    { answer: "Volleybal", clues: ["Net", "Zes", "Blokkeren", "Strand"] },
    { answer: "Formule 1", clues: ["Auto's", "Circuit", "Max Verstappen", "Pitstop"] },
    { answer: "Hockey", clues: ["Stick", "Kleine bal", "Veld", "Short corner"] },
    { answer: "Atletiek", clues: ["Lopen", "Werpen", "Springen", "Tienkamp"] },
    { answer: "Roeien", clues: ["Boot", "Riemen", "Water", "Acht"] },
    { answer: "Rugby", clues: ["Ovaal", "Try", "Haka", "Nieuw-Zeeland"] },
    { answer: "Schaken", clues: ["Bord", "Zwart/Wit", "Koning", "Mat"] },
    { answer: "Boksen", clues: ["Ring", "Handschoenen", "K.O.", "Zwaargewicht"] },
    { answer: "Judo", clues: ["Japan", "Worp", "Mat", "Gordel"] },
    { answer: "Surfen", clues: ["Golf", "Board", "Hawaï", "Zee"] },
    { answer: "Darts", clues: ["Pijltjes", "Bord", "Dubbel", "180"] },
    { answer: "Schermen", clues: ["Degen", "Masker", "Epee", "Raak"] },
    { answer: "Skateboarden", clues: ["Vier wielen", "Plank", "Trick", "Halfpipe"] },
    { answer: "Handbal", clues: ["Zeven", "Doel", "Gooien", "Veld"] },
    { answer: "Gymnastiek", clues: ["Balk", "Vloer", "Ringen", "Turnen"] },

    // --- 🤖 Tech & Gadgets ---
    { answer: "Smartphone", clues: ["Bellen", "Internet", "Camera", "App"] },
    { answer: "Drone", clues: ["Vliegen", "Afstand", "Vier propellers", "Camera"] },
    { answer: "VR Bril", clues: ["Virtueel", "Hoofd", "Spel", "3D"] },
    { answer: "Toetsenbord", clues: ["Typen", "QWERTY", "Enter", "Computer"] },
    { answer: "Muis", clues: ["Cursor", "Klik", "Draadloos", "Computer"] },
    { answer: "Webcam", clues: ["Beeld", "Video", "Online", "Laptop"] },
    { answer: "Router", clues: ["Wifi", "Internet", "Kabel", "Signaal"] },
    { answer: "Bluetooth", clues: ["Draadloos", "Verbinding", "Kort bereik", "Logo"] },
    { answer: "Processor", clues: ["CPU", "Hersen", "Snelheid", "Computer"] },
    { answer: "Firewall", clues: ["Veiligheid", "Netwerk", "Blokkeert", "Muur"] },
    { answer: "Luidspreker", clues: ["Geluid", "Muziek", "Versterken", "Trillen"] },
    { answer: "USB-stick", clues: ["Opslag", "Poort", "Klein", "Data"] },
    { answer: "Robotstofzuiger", clues: ["Schoonmaken", "Rond", "Opladen", "Slim"] },
    { answer: "Laser", clues: ["Licht", "Gebundeld", "Rood", "Snijden"] },
    { answer: "Cryptocurrency", clues: ["Digitaal", "Bitcoin", "Blockchain", "Munt"] },
    { answer: "GPS", clues: ["Navigatie", "Satelliet", "Locatie", "Rijden"] },
    { answer: "Microfoon", clues: ["Opnemen", "Zingen", "Geluid", "Stem"] },
    { answer: "Tablet", clues: ["Touchscreen", "Tussenin", "Dun", "Apps"] },
    { answer: "E-reader", clues: ["Boek", "Digitaal", "Inkt", "Lezen"] },
    { answer: "Cloud", clues: ["Opslag", "Internet", "Bestanden", "Hemel"] },

    // --- 🍎 Fruit & Groenten ---
    { answer: "Rijst", clues: ["Azië", "Korrel", "Water", "Sushi"] },
    { answer: "Wortel", clues: ["Oranje", "Onder de grond", "Konijn", "A-vitamine"] },
    { answer: "Aardbei", clues: ["Rood", "Zomer", "Zoet", "Jam"] },
    { answer: "Citroen", clues: ["Geel", "Zuur", "Sap", "Drankje"] },
    { answer: "Broccoli", clues: ["Groen", "Bloemkool", "Boompje", "Gezond"] },
    { answer: "Ananas", clues: ["Tropisch", "Geel/Bruin", "Stekelig", "Pizza Hawaii"] },
    { answer: "Sla", clues: ["Groen", "Blad", "Salade", "Krop"] },
    { answer: "Druif", clues: ["Tros", "Wijn", "Klein", "Paars/Groen"] },
    { answer: "Ui", clues: ["Tranend", "Laagjes", "Sterk", "Smaak"] },
    { answer: "Paprika", clues: ["Rood/Geel/Groen", "Gevuld", "Vorm", "Pittig"] },
    { answer: "Komkommer", clues: ["Langwerpig", "Groen", "Waterig", "Salade"] },
    { answer: "Sinaasappel", clues: ["Oranje", "C-vitamine", "Sap", "Winter"] },
    { answer: "Mango", clues: ["Tropisch", "Zoet", "Grote pit", "Oranje"] },
    { answer: "Champignon", clues: ["Paddenstoel", "Wit/Bruin", "Pizza", "Bos"] },
    { answer: "Courgette", clues: ["Langwerpig", "Groen", "Aubergine", "Zomer"] },
    { answer: "Framboos", clues: ["Klein", "Rood", "Zacht", "Zomer"] },
    { answer: "Knoflook", clues: ["Teentjes", "Sterke geur", "Vampieren", "Wit"] },
    { answer: "Aubergine", clues: ["Paars", "Langwerpig", "Moussaka", "Groente"] },
    { answer: "Avocado", clues: ["Groen", "Grote pit", "Guacamole", "Vrucht"] },
    { answer: "Peper", clues: ["Pittig", "Groen/Rood", "Chili", "Hete"] },

    // --- 🎶 Muziekstijlen ---
    { answer: "Jazz", clues: ["New Orleans", "Improvisatie", "Saxofoon", "Blues"] },
    { answer: "Rock", clues: ["Gitaar", "Drums", "Luid", "Jaren '50"] },
    { answer: "Popmuziek", clues: ["Populair", "Top 40", "Commercieel", "Mainstream"] },
    { answer: "Klassiek", clues: ["Orkest", "Mozart", "Noten", "Viool"] },
    { answer: "Hip Hop", clues: ["Rap", "DJ", "Graffiti", "New York"] },
    { answer: "Blues", clues: ["Verdrietig", "Gitaar", "Mississippidelta", "Jaren '20"] },
    { answer: "Techno", clues: ["Detroit", "Beats", "Herhalend", "Dans"] },
    { answer: "Reggae", clues: ["Jamaica", "Bob Marley", "Rasta", "Groen-Geel-Rood"] },
    { answer: "Country", clues: ["Nashville", "Gitaar", "Cowboy", "Amerika"] },
    { answer: "Metal", clues: ["Hard", "Distortion", "Snel", "Heavy"] },
    { answer: "Disco", clues: ["Jaren '70", "Dansvloer", "Glitter", "Saturday Night Fever"] },
    { answer: "Folk", clues: ["Akoestisch", "Traditioneel", "Verhaal", "Gitaar"] },
    { answer: "Gospel", clues: ["Kerk", "Zang", "Religieus", "Zuidelijke VS"] },
    { answer: "Soul", clues: ["Emotie", "Motown", "R&B", "Zwarte muziek"] },
    { answer: "Punk", clues: ["Anarchie", "Lawaai", "Londen", "DIY"] },
    { answer: "Flamenco", clues: ["Spanje", "Gitaar", "Dans", "Klappen"] },
    { answer: "Indie", clues: ["Onafhankelijk", "Bandjes", "Alternatief", "Gitaarpop"] },
    { answer: "House", clues: ["Chicago", "Dans", "Synthesizer", "DJ"] },
    { answer: "Salsa", clues: ["Cuba", "Dans", "Latijns-Amerika", "Ritme"] },
    { answer: "K-Pop", clues: ["Zuid-Korea", "Boyband", "Idool", "Gekleurd haar"] },

    // --- 🎨 Kunst & Cultuur ---
    { answer: "Mona Lisa", clues: ["Da Vinci", "Lachen", "Parijs", "Portret"] },
    { answer: "De Nachtwacht", clues: ["Rembrandt", "Rijksmuseum", "Amsterdam", "Groot"] },
    { answer: "Beeldhouwwerk", clues: ["Steen", "Vorm", "3D", "Michelangelo"] },
    { answer: "Ballet", clues: ["Dans", "Spitzen", "Tutu", "Klassiek"] },
    { answer: "Opera", clues: ["Zang", "Italiaans", "Podium", "Hoog"] },
    { answer: "Impressionisme", clues: ["Monet", "Licht", "Frankrijk", "Stijl"] },
    { answer: "Kubisme", clues: ["Picasso", "Geometrisch", "Vormen", "Braque"] },
    { answer: "Aquarel", clues: ["Waterverf", "Licht", "Papier", "Dun"] },
    { answer: "Architectuur", clues: ["Gebouw", "Ontwerp", "Stijl", "Huis"] },
    { answer: "Schildersezel", clues: ["Hout", "Doek", "Standaard", "Atelier"] },
    { answer: "Poëzie", clues: ["Gedicht", "Rijm", "Strofe", "Woorden"] },
    { answer: "Fotografie", clues: ["Camera", "Licht", "Beeld", "Lens"] },
    { answer: "Mozaïek", clues: ["Stukjes", "Tegel", "Oud", "Vloer"] },
    { answer: "Graffiti", clues: ["Muur", "Spuitbus", "Straat", "Kunst"] },
    { answer: "Aardewerk", clues: ["Klei", "Gebakken", "Vaas", "Potten"] },
    { answer: "Renaissance", clues: ["Wedergeboorte", "Italië", "15e eeuw", "Kunsttijd"] },
    { answer: "Museum", clues: ["Kunst", "Oud", "Zaal", "Kijken"] },
    { answer: "Sculptuur", clues: ["Vorm", "Beeld", "Brons", "Materiaal"] },
    { answer: "Stripboek", clues: ["Tekeningen", "Ballon", "Verhaal", "Omslag"] },
    { answer: "Keramiek", clues: ["Klei", "Bakken", "Potten", "Vaas"] },

    // --- 🦁 Dieren (Extra) ---
    { answer: "Krokodil", clues: ["Reptiel", "Tanden", "Lange bek", "Nijl"] },
    { answer: "Varken", clues: ["Stal", "Roze", "Knorren", "Modder"] },
    { answer: "Vos", clues: ["Slim", "Rood", "Staart", "Bos"] },
    { answer: "Panda", clues: ["Bamboe", "Zwart-Wit", "China", "Bedreigd"] },
    { answer: "Egel", clues: ["Stekels", "Klein", "Nacht", "Rollend"] },
    { answer: "Koe", clues: ["Melk", "Vier magen", "Loeien", "Weide"] },
    { answer: "Vlinder", clues: ["Insect", "Kleur", "Rups", "Vliegen"] },
    { answer: "Aap", clues: ["Slinger", "Banaan", "Jungle", "Zoogdier"] },
    { answer: "Mier", clues: ["Klein", "Kolonie", "Werk", "Insect"] },
    { answer: "Uil", clues: ["Nacht", "Ogen", "Zweinstein", "Roepen"] },
    { answer: "Kameel", clues: ["Bulten", "Woestijn", "Spugen", "Water"] },
    { answer: "Slang", clues: ["Giftig", "Kruipen", "Geen poten", "Eva"] },
    { answer: "Konijn", clues: ["Langoren", "Huppelen", "Gras", "Paas"] },
    { answer: "Kolibrie", clues: ["Vogel", "Snel", "Zoemen", "Nectar"] },
    { answer: "Bizon", clues: ["Groot", "Amerika", "Hoorns", "Gras"] },
    { answer: "Pauw", clues: ["Vogel", "Veren", "Staart", "Ogen"] },
    { answer: "Walvis", clues: ["Groot", "Zee", "Zoogdier", "Blazen"] },
    { answer: "Kip", clues: ["Ei", "Tokken", "Vogel", "Boerderij"] },
    { answer: "Inktvis", clues: ["Acht armen", "Inkt", "Zee", "Weekdier"] },
    { answer: "Zalm", clues: ["Vis", "Rood", "Rivier", "Zwemmen"] },

    // --- 🌎 Natuur & Wetenschap (Extra) ---
    { answer: "Zon", clues: ["Ster", "Warm", "Licht", "Geel"] },
    { answer: "Aarde", clues: ["Planeet", "Blauw", "Leven", "Draaien"] },
    { answer: "Water", clues: ["H₂O", "Vloeistof", "Dorst", "Zee"] },
    { answer: "Bliksem", clues: ["Donder", "Hemel", "Ontlading", "Snel"] },
    { answer: "Fossiel", clues: ["Steen", "Oud", "Dinosaurus", "Gevonden"] },
    { answer: "Atmosfeer", clues: ["Lucht", "Laag", "Aarde", "Gas"] },
    { answer: "Magma", clues: ["Vloeibaar", "Hitte", "Vulkaan", "Onder de grond"] },
    { answer: "Gletsjer", clues: ["IJs", "Berg", "Traag", "Koud"] },
    { answer: "Kristal", clues: ["Vorm", "Doorzichtig", "Groei", "Mooi"] },
    { answer: "Tsunami", clues: ["Golf", "Zeebeving", "Groot", "Kust"] },
    { answer: "Orkaan", clues: ["Wind", "Oog", "Tropisch", "Storm"] },
    { answer: "Eclips", clues: ["Zon/Maan", "Donker", "Bedekking", "Hemel"] },
    { answer: "Klimaat", clues: ["Weer", "Lange termijn", "Verandering", "Temperatuur"] },
    { answer: "Biologie", clues: ["Leven", "Studie", "Organisme", "Wetenschap"] },
    { answer: "Geologie", clues: ["Aarde", "Stenen", "Lagen", "Studie"] },
    { answer: "Tij", clues: ["Zee", "Hoog/Laag", "Maan", "Waterstand"] },
    { answer: "Koraal", clues: ["Oceaan", "Rif", "Kleurrijk", "Dier"] },
    { answer: "Komeet", clues: ["IJsbal", "Staart", "Ruimte", "Orbit"] },
    { answer: "Neutron", clues: ["Atoom", "Kern", "Lading", "Deeltje"] },
    { answer: "Kalksteen", clues: ["Steen", "Wit", "Zee", "Bouw"] },

    // --- 🎬 Film & TV (Extra) ---
    { answer: "The Matrix", clues: ["Keuze", "Rood/Blauw", "Neo", "Kogels"] },
    { answer: "De Leeuwenkoning", clues: ["Disney", "Jungle", "Simba", "Cirkel van het Leven"] },
    { answer: "Pulp Fiction", clues: ["Tarantino", "Dans", "Koffer", "Bloed"] },
    { answer: "The Big Bang Theory", clues: ["Nerd", "Sheldon", "Wetenschap", "Sitcom"] },
    { answer: "Breaking Bad", clues: ["Blauw", "Leraar", "Nieuw-Mexico", "Koken"] },
    { answer: "Avatar: The Last Airbender", clues: ["Elementen", "Lucht", "Vier naties", "Aang"] },
    { answer: "Forrest Gump", clues: ["Rennen", "Chocolade", "Vietnam", "Tom Hanks"] },
    { answer: "Jaws", clues: ["Haai", "Zee", "Gevaarlijk", "Muziek"] },
    { answer: "The Simpsons", clues: ["Geel", "Familie", "Springfield", "Duff"] },
    { answer: "Toy Story", clues: ["Speelgoed", "Buzz", "Woody", "Pixar"] },
    { answer: "Batman", clues: ["Gothic", "Vleermuis", "Gotham", "Joker"] },
    { answer: "Indiana Jones", clues: ["Hoed", "Zweep", "Archeoloog", "Avontuur"] },
    { answer: "Modern Family", clues: ["Mockumentary", "Gezin", "Los Angeles", "Humor"] },
    { answer: "The Office (US)", clues: ["Papier", "Michael Scott", "Dwight", "Kantoor"] },
    { answer: "Willy Wonka", clues: ["Chocolade", "Fabriek", "Oompa Loompa", "Goud"] },
    { answer: "Black Panther", clues: ["Wakanda", "Afrika", "Koninkrijk", "Marvel"] },
    { answer: "Squid Game", clues: ["Zuid-Korea", "Spellen", "Rood/Groen", "Netflix"] },
    { answer: "The Witcher", clues: ["Geralt", "Monsters", "Zwaard", "Pools"] },
    { answer: "Game of Thrones", clues: ["Winter", "Draken", "IJzeren Troon", "Westeros"] },
    { answer: "Peaky Blinders", clues: ["Engeland", "Hoed", "Bende", "Birmingham"] },

    // --- 📝 Literaire Werken ---
    { answer: "De Hobbit", clues: ["Tolkien", "Dwergen", "Bilbo", "Ring"] },
    { answer: "1984", clues: ["Orwell", "Big Brother", "Dystopie", "Grote Broer"] },
    { answer: "De Odyssee", clues: ["Homerus", "Grieks", "Zee", "Ithaka"] },
    { answer: "Jip en Janneke", clues: ["Annie M.G.", "Twee kinderen", "Torenkraai", "Hond"] },
    { answer: "Romeo en Julia", clues: ["Shakespeare", "Liefde", "Tragedie", "Verona"] },
    { answer: "De Kleine Prins", clues: ["Vliegtuig", "Roos", "Planeet", "Vos"] },
    { answer: "Moby Dick", clues: ["Walvis", "Kapitein", "Boot", "Wit"] },
    { answer: "Het Achterhuis", clues: ["Anne Frank", "Dagboek", "WO II", "Amsterdam"] },
    { answer: "De Da Vinci Code", clues: ["Dan Brown", "Parijs", "Geheim", "Kerk"] },
    { answer: "Jane Eyre", clues: ["Brontë", "Gouvernante", "Engels", "Romantiek"] },
    { answer: "De Grote Gatsby", clues: ["Jaren '20", "Amerika", "Rijkdom", "Liefde"] },
    { answer: "De Naam van de Roos", clues: ["Eco", "Klooster", "Middeleeuwen", "Moord"] },
    { answer: "De Hongerspelen", clues: ["Districten", "Katniss", "Toernooi", "President Snow"] },
    { answer: "De Meester en Margarita", clues: ["Rusland", "Duivel", "Kat", "Moskou"] },
    { answer: "De Drie Musketiers", clues: ["Frankrijk", "Zwaarden", "Vier", "Koninklijk"] },
    { answer: "Reis naar het Middenpunt van de Aarde", clues: ["Jules Verne", "Ondergronds", "Avontuur", "Professor"] },
    { answer: "Het Verhaal van de Dienstmeid", clues: ["Atwood", "Dystopie", "Rood", "Gilead"] },
    { answer: "De Schaduw van de Wind", clues: ["Barcelona", "Boeken", "Geheim", "Zafón"] },
    { answer: "Lord of the Flies", clues: ["Eiland", "Kinderen", "Orde", "Varken"] },
    { answer: "Frankenstein", clues: ["Monster", "Schepper", "Lichaam", "Wetenschap"] },

    // --- 🇧🇪🇳🇱 Steden & Plaatsen ---
    { answer: "Rotterdam", clues: ["Haven", "Erasmusbrug", "Kubuswoningen", "Maas"] },
    { answer: "Brugge", clues: ["België", "Water", "Historisch", "Horeca"] },
    { answer: "Utrecht", clues: ["Domtoren", "Gracht", "Midden", "Nederland"] },
    { answer: "Luik", clues: ["België", "Waals", "Vurige Stede", "Maas"] },
    { answer: "Den Haag", clues: ["Politiek", "Scheveningen", "Vredespaleis", "Koninklijk"] },
    { answer: "Maastricht", clues: ["Limburg", "Sint Servaas", "Vrijthof", "Verdrag"] },
    { answer: "Kopenhagen", clues: ["Denemarken", "Zeemeermin", "Fiets", "Hoofdstad"] },
    { answer: "Wenen", clues: ["Oostenrijk", "Klassieke muziek", "Donau", "Keizerrijk"] },
    { answer: "Peking", clues: ["China", "Verboden Stad", "Muur", "Olympische Spelen"] },
    { answer: "Caïro", clues: ["Egypte", "Nijl", "Piramide", "Groot"] },
    { answer: "Mexico-Stad", clues: ["Hoogte", "Groot", "Azteken", "Latijns-Amerika"] },
    { answer: "Dubai", clues: ["Zand", "Hoogste", "Luxe", "Verenigde Arabische Emiraten"] },
    { answer: "Boedapest", clues: ["Hongarije", "Donau", "Twee delen", "Baden"] },
    { answer: "Praag", clues: ["Tsjechië", "Karel de Grote", "Brug", "Hoofdstad"] },
    { answer: "Helsinki", clues: ["Finland", "Koud", "Zee", "Design"] },
    { answer: "Lissabon", clues: ["Portugal", "Tram", "Zeven heuvels", "Fado"] },
    { answer: "Milaan", clues: ["Italië", "Mode", "Duomo", "Voetbal"] },
    { answer: "Barcelona", clues: ["Spanje", "Gaudi", "Strand", "Catalonië"] },
    { answer: "Seoel", clues: ["Zuid-Korea", "Technologie", "Han", "Hoofdstad"] },
    { answer: "Dublin", clues: ["Ierland", "Guinness", "Groen", "Literatuur"] },

    // --- 📦 Dagelijkse Objecten ---
    { answer: "Sleutel", clues: ["Slot", "Metaal", "Huis", "Openen"] },
    { answer: "Schaar", clues: ["Twee gaten", "Knippen", "Metaal", "Papier"] },
    { answer: "Paraplu", clues: ["Regen", "Opklapbaar", "Stok", "Nat"] },
    { answer: "Leesbril", clues: ["Ogen", "Klein", "Lezen", "Helpen"] },
    { answer: "Tandenborstel", clues: ["Poetsen", "Haar", "Pasta", "Mond"] },
    { answer: "Föhn", clues: ["Warmte", "Haar", "Droog", "Elektriciteit"] },
    { answer: "Wasmachine", clues: ["Kleding", "Schoon", "Draaien", "Zeep"] },
    { answer: "Koptelefoon", clues: ["Oren", "Muziek", "Horen", "Draad"] },
    { answer: "Kaars", clues: ["Vuur", "Licht", "Was", "Feest"] },
    { answer: "Spiegel", clues: ["Reflectie", "Glas", "Kijken", "Badkamer"] },
    { answer: "Kussen", clues: ["Hoofd", "Zacht", "Slapen", "Bed"] },
    { answer: "Krijt", clues: ["Wit", "Bord", "School", "Teken"] },
    { answer: "Gloeilamp", clues: ["Licht", "Edison", "Glas", "Kap"] },
    { answer: "Zaklamp", clues: ["Batterij", "Donker", "Lichtbundel", "Hand"] },
    { answer: "Tape", clues: ["Plakken", "Rol", "Transparant", "Vast"] },
    { answer: "Kalender", clues: ["Datum", "Maanden", "Jaren", "Afdruk"] },
    { answer: "Deurbel", clues: ["Geluid", "Gasten", "Drukken", "Huis"] },
    { answer: "Thermosfles", clues: ["Warm/Koud", "Drinken", "Isoleren", "Metaal"] },
    { answer: "Afstandsbediening", clues: ["TV", "Zappen", "Batterijen", "Knoppen"] },

    // --- 🖼️ Merken & Logo's ---
    { answer: "Coca-Cola", clues: ["Frisdrank", "Rood-wit", "Amerika", "Kerstman"] },
    { answer: "Nike", clues: ["Sportkleding", "Swoosh", "Just Do It", "Grieks"] },
    { answer: "LEGO", clues: ["Deens", "Plastic blokjes", "Kinderen", "Bouwen"] },
    { answer: "Mercedes", clues: ["Duits", "Auto", "Ster", "Luxe"] },
    { answer: "Amazon", clues: ["Webwinkel", "Pijl", "Jeff Bezos", "Rivier"] },
    { answer: "Netflix", clues: ["Streamen", "Rood", "Films/Series", "N"] },
    { answer: "Samsung", clues: ["Zuid-Korea", "Telefoon", "TV", "Technologie"] },
    { answer: "McDonald's", clues: ["Goud", "M", "Fastfood", "Hamburger"] },
    { answer: "IKEA", clues: ["Zweeds", "Meubels", "Blauw-geel", "Zelfbouw"] },
    { answer: "Toyota", clues: ["Japans", "Auto", "Betrouwbaar", "Drie ovalen"] },
    { answer: "Red Bull", clues: ["Energy", "Oostenrijk", "Twee stieren", "Vleugels"] },
    { answer: "Adidas", clues: ["Drie strepen", "Duitsland", "Sport", "Kleding"] },
    { answer: "YouTube", clues: ["Video", "Rood", "Uploaden", "Google"] },
    { answer: "Starbucks", clues: ["Koffie", "Groen", "Zeemeermin", "Beker"] },
    { answer: "Ferrari", clues: ["Italië", "Rood", "Paard", "Sportwagen"] },
    { answer: "Disney", clues: ["Kasteel", "Mickey", "Films", "Pretpark"] },
    { answer: "Audi", clues: ["Vier ringen", "Duitsland", "Auto", "Vorsprung"] },
    { answer: "Spotify", clues: ["Groen", "Muziek", "Streamen", "Drie lijnen"] },
    { answer: "Barbie", clues: ["Pop", "Roze", "Ken", "Mattel"] },
    { answer: "VISA", clues: ["Creditcard", "Blauw-geel", "Betalen", "Wereldwijd"] },

    // --- 🧪 Chemie & Materialen ---
    { answer: "Goud", clues: ["Metaal", "Geel", "Sieraad", "Au"] },
    { answer: "Zilver", clues: ["Metaal", "Wit", "Spiegel", "Ag"] },
    { answer: "Zout", clues: ["Wit", "Zee", "Keuken", "NaCl"] },
    { answer: "Koolstof", clues: ["Element", "C", "Diamant", "Leven"] },
    { answer: "Staal", clues: ["Ijzer", "Sterk", "Bouwen", "Legering"] },
    { answer: "Plastic", clues: ["Olie", "Licht", "Recyclen", "Verpakking"] },
    { answer: "Suiker", clues: ["Wit", "Zoet", "Riet", "Energie"] },
    { answer: "Alcohol", clues: ["Drank", "Vloeistof", "Sterk", "Desinfectie"] },
    { answer: "Glas", clues: ["Doorzichtig", "Breken", "Raam", "Zand"] },
    { answer: "Koper", clues: ["Metaal", "Roodbruin", "Draad", "Geleider"] },
    { answer: "Kwik", clues: ["Vloeibaar", "Metaal", "Thermometer", "Giftig"] },
    { answer: "Lood", clues: ["Zwaar", "Grijs", "Pijp", "Giftig"] },
    { answer: "Kalk", clues: ["Wit", "Steen", "Water", "Bouw"] },
    { answer: "Ammoniak", clues: ["Gas", "Sterke geur", "Schoonmaak", "NH3"] },
    { answer: "Diesel", clues: ["Brandstof", "Motor", "Vies", "Olie"] },
    { answer: "Rubber", clues: ["Elastisch", "Band", "Boom", "Waterdicht"] },
    { answer: "Cement", clues: ["Grijs", "Water", "Bouw", "Hard"] },
    { answer: "Katoen", clues: ["Plant", "Wit", "Kleding", "Stof"] },
    { answer: "Atoom", clues: ["Kleinste", "Deel", "Kern", "Neutron"] },
    { answer: "Polymeren", clues: ["Keten", "Plastic", "Groot", "Moleculen"] },

    // --- 🎭 Fictieve Personages ---
    { answer: "Sherlock Holmes", clues: ["Detective", "Londen", "Pijp", "Watson"] },
    { answer: "Darth Vader", clues: ["Star Wars", "Zwart", "Adem", "Vader"] },
    { answer: "Mickey Mouse", clues: ["Disney", "Muis", "Rood", "Oren"] },
    { answer: "Hulk", clues: ["Groen", "Woede", "Sterk", "Marvel"] },
    { answer: "Pikachu", clues: ["Pokémon", "Geel", "Staart", "Elektrisch"] },
    { answer: "Kuifje", clues: ["België", "Hond", "Reporter", "Haar"] },
    { answer: "Tarzan", clues: ["Jungle", "Lianen", "Apen", "Blote"] },
    { answer: "Captain America", clues: ["Schild", "Blauw", "Superheld", "Amerika"] },
    { answer: "Pippi Langkous", clues: ["Zweeds", "Vlechten", "Aap", "Sterk"] },
    { answer: "Dracula", clues: ["Vampier", "Transsylvanië", "Bloed", "Tanden"] },
    { answer: "Wall-E", clues: ["Robot", "Film", "Afval", "Liefde"] },
    { answer: "Shrek", clues: ["Groen", "Oger", "Ezel", "Moeras"] },
    { answer: "Robin Hood", clues: ["Boog", "Engeland", "Rijk", "Armen"] },
    { answer: "Popeye", clues: ["Zeeman", "Spinazie", "Pijp", "Olijf"] },
    { answer: "Yoda", clues: ["Groen", "Jedi", "Klein", "Spraak"] },
    { answer: "Paddington", clues: ["Beer", "Marmelade", "Peru", "Engeland"] },
    { answer: "Superman", clues: ["Krypton", "Kaap", "Vliegen", "Rood/Blauw"] },
    { answer: "Pinokkio", clues: ["Neus", "Hout", "Leugen", "Pop"] },
    { answer: "Winnie de Poeh", clues: ["Honing", "Beer", "Ezel", "Bos"] },
    { answer: "Hermelien Griffel", clues: ["Harry Potter", "Muis", "Slim", "Tijd"] },

    // --- 🛠️ Gereedschap & Machines ---
    { answer: "Hamer", clues: ["Spijkers", "Slag", "Kop", "Handvat"] },
    { answer: "Schroevendraaier", clues: ["Draaien", "Philips", "Plat", "Hand"] },
    { answer: "Tang", clues: ["Vastgrijpen", "Knippen", "Bek", "Metaal"] },
    { answer: "Boormachine", clues: ["Gat", "Wand", "Draaien", "Elektrisch"] },
    { answer: "Waterpas", clues: ["Bubbel", "Recht", "Horizontaal", "Groen"] },
    { answer: "Rolmaat", clues: ["Meten", "Lint", "Oprollen", "Centimeters"] },
    { answer: "Zaag", clues: ["Tanden", "Hout", "Knippen", "Hand"] },
    { answer: "Ladder", clues: ["Klimmen", "Treden", "Hoog", "Vouwen"] },
    { answer: "Beitel", clues: ["Hout", "Hakken", "Scherp", "Metaal"] },
    { answer: "Verfkwast", clues: ["Schilderen", "Haar", "Kleur", "Streek"] },
    { answer: "Slijptol", clues: ["Rond", "Metaal", "Vonken", "Snijden"] },
    { answer: "Plug", clues: ["Wand", "Schroef", "Plastic", "Vast"] },
    { answer: "Wielsleutel", clues: ["Auto", "Moeren", "Band", "Kruis"] },
    { answer: "Kruiwagen", clues: ["Wiel", "Tuin", "Grond", "Duwen"] },
    { answer: "Soldeerbout", clues: ["Elektronica", "Warm", "Tin", "Verbinden"] },
    { answer: "Accu", clues: ["Batterij", "Auto", "Opladen", "Energie"] },
    { answer: "Compressor", clues: ["Lucht", "Druk", "Banden", "Blaas"] },
    { answer: "Kettingzaag", clues: ["Motor", "Boom", "Gevaarlijk", "Snel"] },
    { answer: "Steeksleutel", clues: ["Moer", "Vastdraaien", "Maat", "Open"] },
    { answer: "Nietmachine", clues: ["Kantoor", "Papier", "Metaal", "Vastzetten"] },

    // --- 🐉 Mythen & Legenden ---
    { answer: "Pegasus", clues: ["Griekse mythe", "Vleugels", "Wit", "Paard"] },
    { answer: "Zeus", clues: ["Oppergod", "Bliksem", "Olympos", "Griek"] },
    { answer: "Sfinx", clues: ["Egypte", "Hoofd/Lichaam", "Raadsel", "Groot"] },
    { answer: "Minotaurus", clues: ["Half mens/stier", "Labyrint", "Kretenzer", "Griek"] },
    { answer: "Medusa", clues: ["Slangenhaar", "Kijken", "Verstenen", "Griek"] },
    { answer: "Arthur", clues: ["Koning", "Zwaard", "Ronde Tafel", "Camelot"] },
    { answer: "Merlijn", clues: ["Tovenaar", "Baard", "Arthur", "Magiër"] },
    { answer: "Valkyrie", clues: ["Noors", "Paard", "Krijger", "Walhalla"] },
    { answer: "Thor", clues: ["Noors", "Hamer", "Donder", "Ragnarok"] },
    { answer: "Sirene", clues: ["Zee", "Zang", "Gevaarlijk", "Vrouw"] },
    { answer: "Feniks", clues: ["Vogel", "Vuur", "As", "Herrijzen"] },
    { answer: "Zeemeermin", clues: ["Onder water", "Vrouw", "Staart", "Zingen"] },
    { answer: "Draak", clues: ["Vleugels", "Vuur", "Schubben", "Bewaker"] },
    { answer: "Kabouter", clues: ["Klein", "Rood", "Puntmuts", "Bos"] },
    { answer: "Eenhoorn", clues: ["Wit paard", "Hoorn", "Puur", "Magie"] },
    { answer: "Gargoyle", clues: ["Steen", "Beeld", "Kerk", "Afvoer"] },
    { answer: "Weerwolf", clues: ["Volle maan", "Wolf", "Mens", "Transformatie"] },
    { answer: "Leviathan", clues: ["Zee", "Monster", "Bijbels", "Groot"] },
    { answer: "Anubis", clues: ["Egypte", "Doden", "Jakhals", "Wegen"] },
    { answer: "Vampier", clues: ["Nacht", "Bloed", "Tanden", "Dracula"] },

    // --- 👕 Kleding & Accessoires ---
    { answer: "Spijkerbroek", clues: ["Denim", "Blauw", "Werkkleding", "Levi's"] },
    { answer: "Schoenen", clues: ["Voeten", "Leder", "Veters", "Lopen"] },
    { answer: "Handschoenen", clues: ["Handen", "Koud", "Tien vingers", "Leer"] },
    { answer: "Riem", clues: ["Taille", "Broek", "Gesp", "Leer"] },
    { answer: "Zonnebril", clues: ["Ogen", "Zon", "Donker", "Zomer"] },
    { answer: "Jas", clues: ["Bovenkleding", "Koud", "Rits", "Warm"] },
    { answer: "T-shirt", clues: ["Korte mouw", "Katoen", "Print", "Zomer"] },
    { answer: "Sokken", clues: ["Voeten", "Wassen", "Paar", "Warmte"] },
    { answer: "Muts", clues: ["Hoofd", "Koud", "Wol", "Winter"] },
    { answer: "Rok", clues: ["Vrouw", "Onder", "Jurk", "Lang/Kort"] },
    { answer: "Pyjama", clues: ["Slapen", "Nacht", "Zacht", "Twee stukken"] },
    { answer: "Sjaal", clues: ["Nek", "Wol", "Lang", "Mode"] },
    { answer: "Strikdas", clues: ["Nek", "Feest", "Vlinder", "Netjes"] },
    { answer: "Horloge", clues: ["Pols", "Tijd", "Wijzers", "Cadeau"] },
    { answer: "Oorbellen", clues: ["Oor", "Sieraad", "Piercing", "Goud/Zilver"] },
    { answer: "Portemonnee", clues: ["Geld", "Kaart", "Leder", "Tas"] },
    { answer: "Rugzak", clues: ["Rug", "Twee banden", "School", "Wandelen"] },
    { answer: "Badjas", clues: ["Badkamer", "Zacht", "Water", "Ochtend"] },
    { answer: "Veters", clues: ["Schoen", "Strik", "Vastmaken", "Draad"] },
    { answer: "Ketting", clues: ["Nek", "Goud", "Hanger", "Sieraad"] },

    // --- ⚖️ Maten, Gewichten & Geld ---
    { answer: "Kilogram", clues: ["Gewicht", "1000 gram", "Massa", "Kilo"] },
    { answer: "Meter", clues: ["Lengte", "100 cm", "Afstand", "Basis"] },
    { answer: "Euro", clues: ["Munt", "Europa", "100 cent", "Geld"] },
    { answer: "Liter", clues: ["Inhoud", "Vloeistof", "Fles", "Volume"] },
    { answer: "Seconde", clues: ["Tijd", "60", "Kort", "Uur"] },
    { answer: "Celsius", clues: ["Temperatuur", "0/100", "Water", "Maat"] },
    { answer: "Ampère", clues: ["Stroom", "Elektriciteit", "Eenheid", "A"] },
    { answer: "Hectare", clues: ["Oppervlakte", "Land", "Vierkant", "100x100"] },
    { answer: "Volt", clues: ["Spanning", "Stroom", "U", "V"] },
    { answer: "Bar", clues: ["Druk", "Banden", "Weer", "Atmosfeer"] },
    { answer: "Decibel", clues: ["Geluid", "Luid", "Oor", "dB"] },
    { answer: "Watt", clues: ["Vermogen", "Lamp", "Energie", "Stroom"] },
    { answer: "Pond", clues: ["Groot-Brittannië", "Geld", "Gewicht", "Sterling"] },
    { answer: "Kilometer", clues: ["Afstand", "1000 meter", "Weg", "km"] },
    { answer: "Gram", clues: ["Gewicht", "Klein", "Keuken", "G"] },
    { answer: "Karat", clues: ["Goud", "Zuiver", "24", "Diamant"] },
    { answer: "Bitcoin", clues: ["Crypto", "Digitaal", "Munt", "Blockchain"] },
    { answer: "Knoop", clues: ["Snelheid", "Zeevaart", "Vliegen", "Eenheid"] },
    { answer: "Pixel", clues: ["Beeld", "Scherm", "Punt", "Kleur"] },
    { answer: "Ounce", clues: ["Amerikaans", "Gewicht", "Goud", "Vloeistof"] },

    // --- 🌿 Kruiden & Specerijen ---
    { answer: "Zwarte Peper", clues: ["Zwart", "Strooien", "Scherp", "Bessen"] },
    { answer: "Zeezout", clues: ["Wit", "Zee", "Keuken", "Kristallen"] },
    { answer: "Kaneel", clues: ["Bruin", "Stokje", "Zoet", "Speculaas"] },
    { answer: "Nootmuskaat", clues: ["Nootsmaak", "Rasp", "Indonesië", "Oranje"] },
    { answer: "Basilicum", clues: ["Groen", "Italiaans", "Pesto", "Plant"] },
    { answer: "Vanille", clues: ["Stokje", "Zoet", "IJs", "Orchidee"] },
    { answer: "Gember", clues: ["Wortel", "Pittig", "Geel", "Thee"] },
    { answer: "Curry", clues: ["Geel", "India", "Mengsel", "Geur"] },
    { answer: "Tijm", clues: ["Kruid", "Aards", "Klein blad", "Frans"] },
    { answer: "Rozemarijn", clues: ["Naald", "Mediterraan", "Vlees", "Sterke geur"] },
    { answer: "Oregano", clues: ["Pizza", "Italiaans", "Griekse", "Droog"] },
    { answer: "Saffraan", clues: ["Duur", "Rood", "Paella", "Kleur"] },
    { answer: "Kruidnagel", clues: ["Nagel", "Sterk", "Glühwein", "Zoet"] },
    { answer: "Paprikapoeder", clues: ["Rood", "Hongarije", "Zoet/Pittig", "Poeder"] },
    { answer: "Munt", clues: ["Groen", "Thee", "Fris", "Blad"] },
    { answer: "Koriander", clues: ["Blad/Zaad", "Zeep", "Aziatisch", "Groen"] },
    { answer: "Laurierblad", clues: ["Soep", "Sterk", "Blad", "Mediterraan"] },
    { answer: "Komijn", clues: ["Zaad", "Midden-Oosten", "Kaas", "Sterk"] },
    { answer: "Anijs", clues: ["Zoet", "Drank", "Ouzo", "Ster"] },
    { answer: "Mosterdzaad", clues: ["Geel", "Scherp", "Saus", "Zaad"] },

    // --- 🧑 De Mens (Anatomie) ---
    { answer: "Hart", clues: ["Kloppen", "Bloed", "Pomp", "Liefde"] },
    { answer: "Hersenen", clues: ["Denken", "Hoofd", "Controle", "Grijs"] },
    { answer: "Longen", clues: ["Ademen", "Zuurstof", "Twee", "Borst"] },
    { answer: "Lever", clues: ["Grootste", "Ontgiften", "Orgaan", "Gal"] },
    { answer: "Nieren", clues: ["Filteren", "Boonvormig", "Twee", "Afval"] },
    { answer: "Skelet", clues: ["Botten", "Frame", "Ondersteuning", "206"] },
    { answer: "Ogen", clues: ["Zien", "Twee", "Kleur", "Licht"] },
    { answer: "Maag", clues: ["Eten", "Verteren", "Zuur", "Zak"] },
    { answer: "Huid", clues: ["Grootste", "Orgaan", "Bedekking", "Tast"] },
    { answer: "Bloed", clues: ["Rood", "Vervoer", "Aders", "Plasma"] },
    { answer: "Spieren", clues: ["Bewegen", "Sterk", "Vlees", "Trekken"] },
    { answer: "Tong", clues: ["Proeven", "Spreken", "Roze", "Mond"] },
    { answer: "Oor", clues: ["Horen", "Balans", "Schelp", "Drie delen"] },
    { answer: "Slokdarm", clues: ["Pijp", "Eten", "Maag", "Keel"] },
    { answer: "Aders", clues: ["Bloedvaten", "Blauw", "Terug", "Hart"] },
    { answer: "Tanden", clues: ["Bijten", "Wit", "32", "Kaak"] },
    { answer: "Zenuwen", clues: ["Signalen", "Pijn", "Stelsel", "Snel"] },
    { answer: "Middenrif", clues: ["Ademhaling", "Spier", "Scheiding", "Onder longen"] },
    { answer: "Knie", clues: ["Gewricht", "Been", "Buigen", "Patella"] },
    { answer: "Hand", clues: ["Vijf vingers", "Grijpen", "Pols", "Schrijven"] },

    // --- 🚀 Vervoer ---
    { answer: "Auto", clues: ["Vier wielen", "Motor", "Weg", "Rijden"] },
    { answer: "Vliegtuig", clues: ["Vleugels", "Lucht", "Jet", "Reizen"] },
    { answer: "Trein", clues: ["Rails", "Lang", "Stoom", "Stations"] },
    { answer: "Fiets", clues: ["Twee wielen", "Pedalen", "Zadel", "Bel"] },
    { answer: "Motor", clues: ["Twee wielen", "Snel", "Helm", "Benzine"] },
    { answer: "Schip", clues: ["Zee", "Groot", "Varen", "Haven"] },
    { answer: "Bus", clues: ["Groot", "Openbaar", "Passagiers", "Route"] },
    { answer: "Tram", clues: ["Rails", "Stad", "Elektriciteit", "Wagon"] },
    { answer: "Scooter", clues: ["Twee wielen", "Klein", "Brommen", "Stad"] },
    { answer: "Zeppelin", clues: ["Lucht", "Groot", "Gas", "Oud"] },
    { answer: "Metro", clues: ["Ondergronds", "Stad", "Snel", "Rails"] },
    { answer: "Taxi", clues: ["Geel/Zwart", "Huren", "Rit", "Meter"] },
    { answer: "Kano", clues: ["Water", "Peddel", "Smalle boot", "Rivier"] },
    { answer: "Step", clues: ["Plank", "Stuur", "Duwen", "Elektrisch"] },
    { answer: "Helikopter", clues: ["Rotor", "Verticaal", "Vliegen", "Redding"] },
    { answer: "Kabelbaan", clues: ["Kabel", "Berg", "Passagiers", "Vast"] },
    { answer: "Driewieler", clues: ["Drie wielen", "Kinderen", "Fiets", "Stabiliteit"] },
    { answer: "Vrachtwagen", clues: ["Groot", "Goederen", "Weg", "Trailer"] },
    { answer: "Spaceshuttle", clues: ["Ruimte", "Lanceer", "NASA", "Vleugels"] },
    { answer: "Slee", clues: ["Sneeuw", "Hout", "Trekken", "Winter"] },

    // --- 💡 Willekeurige Feiten (Diversen) ---
    { answer: "Diamant", clues: ["Koolstof", "Hardst", "Ring", "Wit"] },
    { answer: "Vierkant", clues: ["Vier", "Gelijk", "Hoeken", "Vorm"] },
    { answer: "Echo", clues: ["Geluid", "Terug", "Bergen", "Herhaling"] },
    { answer: "Wapenstilstand", clues: ["Oorlog", "Einde", "11 november", "Pauze"] },
    { answer: "China", clues: ["Azië", "Grootste", "Muur", "Taal"] },
    { answer: "Zijde", clues: ["Stof", "Worm", "Zacht", "Chinees"] },
    { answer: "Potlood", clues: ["Hout", "Schrijven", "Gum", "Grijs"] },
    { answer: "Luchtbel", clues: ["Water", "Rond", "Boven", "Gas"] },
    { answer: "Sneeuw", clues: ["Wit", "Koud", "Vlok", "Winter"] },
    { answer: "Zomer", clues: ["Warm", "Zon", "Vakantie", "Juni/Juli/Augustus"] },
    { answer: "Regenboog", clues: ["Zeven kleuren", "Water", "Zon", "Boog"] },
    { answer: "Schaduw", clues: ["Licht", "Donker", "Vorm", "Volgen"] },
    { answer: "Olie", clues: ["Zwart", "Motor", "Dikke vloeistof", "Arabisch"] },
    { answer: "Papier", clues: ["Boom", "Schrijven", "Vouwen", "Blad"] },
    { answer: "Klokkentoren", clues: ["Kerk", "Hoog", "Geluid", "Uur"] },
    { answer: "Wijn", clues: ["Druif", "Rood/Wit", "Fles", "Alcohol"] },
    { answer: "Kopje", clues: ["Drinken", "Oor", "Koffie/Thee", "Keramiek"] },
    { answer: "Touw", clues: ["Dragen", "Vastbinden", "Vlecht", "Dik"] },
    { answer: "Magnetisme", clues: ["Aantrekken", "Noord/Zuid", "Metaal", "Kracht"] },
    { answer: "Zeven", clues: ["Getal", "Dagen", "Wonderen", "Geluk"] },
    { answer: "Blauw", clues: ["Kleur", "Lucht", "Zee", "Primair"] },
    { answer: "Hoofddeksel", clues: ["Hoofd", "Pet", "Warmte", "Accessoire"] },
    { answer: "Verpakking", clues: ["Doos", "Beschermen", "Product", "Folie"] },
    { answer: "Puzzel", clues: ["Stukjes", "Vorm", "Oplossen", "Vrije tijd"] },
    { answer: "Balans", clues: ["Evenwicht", "Gewicht", "Boekhouden", "Twee kanten"] },
    { answer: "Telefooncel", clues: ["Oud", "Bellen", "Rood", "Straat"] },
    { answer: "Barcode", clues: ["Strepen", "Scanner", "Product", "Winkel"] },
    { answer: "Klok", clues: ["Tijd", "Rond", "Wijzers", "Geluid"] },
    { answer: "Briljant", clues: ["Slijpvorm", "Diamant", "Schitteren", "Licht"] },

    // --- 👷 Beroepen (Nieuw) ---
    { answer: "Brandweerman", clues: ["Vuur", "Slang", "Rood", "Blussen"] },
    { answer: "Politieagent", clues: ["Blauw", "Boeien", "Wet", "Sirene"] },
    { answer: "Dokter", clues: ["Ziekenhuis", "Wit", "Patiënt", "Medicijn"] },
    { answer: "Piloot", clues: ["Vliegtuig", "Cockpit", "Uniform", "Vliegen"] },
    { answer: "Bakker", clues: ["Brood", "Oven", "Meel", "Vroeg"] },
    { answer: "Slager", clues: ["Vlees", "Mes", "Schort", "Worst"] },
    { answer: "Kapper", clues: ["Haar", "Schaar", "Spiegel", "Föhn"] },
    { answer: "Leraar", clues: ["School", "Klas", "Bord", "Les"] },
    { answer: "Tandarts", clues: ["Kies", "Boor", "Stoel", "Mond"] },
    { answer: "Boer", clues: ["Land", "Tractor", "Dieren", "Oogst"] },
    { answer: "Astronaut", clues: ["Ruimte", "Raket", "Pak", "NASA"] },
    { answer: "Schilder", clues: ["Kwast", "Verf", "Muur", "Ladder"] },
    { answer: "Ober", clues: ["Restaurant", "Dienblad", "Bestelling", "Fooi"] },
    { answer: "Dierenarts", clues: ["Huisdier", "Ziek", "Praktijk", "Spuitje"] },
    { answer: "Rechter", clues: ["Rechtbank", "Hamer", "Toga", "Vonnis"] },
    { answer: "Soldaat", clues: ["Leger", "Wapen", "Camouflage", "Oorlog"] },
    { answer: "Kapitein", clues: ["Schip", "Boot", "Rang", "Stuur"] },
    { answer: "Postbode", clues: ["Brieven", "Fiets/Auto", "Bezorgen", "Bus"] },
    { answer: "Timmerman", clues: ["Hout", "Zaag", "Hamer", "Bouwen"] },
    { answer: "Loodgieter", clues: ["Buizen", "Lek", "Water", "WC"] },
    { answer: "Kok", clues: ["Keuken", "Muts", "Eten", "Restaurant"] },
    { answer: "Bibliothecaris", clues: ["Boeken", "Stilte", "Uitleen", "Bieb"] },
    { answer: "Detective", clues: ["Onderzoek", "Vergrootglas", "Misdaad", "Speuren"] },
    { answer: "Verpleger", clues: ["Zorg", "Ziekenhuis", "Bed", "Hulp"] },
    { answer: "Fotograaf", clues: ["Camera", "Foto", "Lens", "Flits"] },

    // --- 🏠 Huis & Interieur (Nieuw) ---
    { answer: "Bank", clues: ["Zitten", "Woonkamer", "TV", "Kussens"] },
    { answer: "Tafel", clues: ["Eten", "Poten", "Blad", "Stoelen"] },
    { answer: "Stoel", clues: ["Zitten", "Leuning", "Vier poten", "Tafel"] },
    { answer: "Bed", clues: ["Slapen", "Matras", "Deken", "Nacht"] },
    { answer: "Kast", clues: ["Opbergen", "Deuren", "Planken", "Kleding"] },
    { answer: "Deur", clues: ["Open/Dicht", "Klink", "Slot", "Ingang"] },
    { answer: "Raam", clues: ["Glas", "Kijken", "Licht", "Openen"] },
    { answer: "Tapijt", clues: ["Vloer", "Zacht", "Stof", "Kleed"] },
    { answer: "Gordijn", clues: ["Raam", "Stof", "Dicht", "Donker"] },
    { answer: "Lamp", clues: ["Licht", "Aan/Uit", "Plafond", "Peer"] },
    { answer: "Trap", clues: ["Omhoog", "Treden", "Leuning", "Etage"] },
    { answer: "Dak", clues: ["Bovenkant", "Pannen", "Regen", "Beschutting"] },
    { answer: "Schoorsteen", clues: ["Rook", "Dak", "Haard", "Sinterklaas"] },
    { answer: "Garage", clues: ["Auto", "Opslag", "Deur", "Gereedschap"] },
    { answer: "Zolder", clues: ["Bovenste", "Opslag", "Dak", "Stof"] },
    { answer: "Kelder", clues: ["Onder", "Koud", "Opslag", "Donker"] },
    { answer: "Keuken", clues: ["Koken", "Eten", "Aanrecht", "Koelkast"] },
    { answer: "Badkamer", clues: ["Douche", "Wassen", "Tandenpoetsen", "Handdoek"] },
    { answer: "Slaapkamer", clues: ["Bed", "Rust", "Nacht", "Kledingkast"] },
    { answer: "Toilet", clues: ["WC", "Doortrekken", "Bril", "Kleinste kamertje"] },

    // --- 🍳 Keukengerei (Nieuw) ---
    { answer: "Vork", clues: ["Prikken", "Eten", "Bestek", "Vier tanden"] },
    { answer: "Mes", clues: ["Snijden", "Scherp", "Bestek", "Smeren"] },
    { answer: "Lepel", clues: ["Soep", "Roeren", "Opscheppen", "Rond"] },
    { answer: "Pan", clues: ["Koken", "Vuur", "Deksel", "Bakken"] },
    { answer: "Bord", clues: ["Eten", "Rond", "Plat", "Servies"] },
    { answer: "Glas", clues: ["Drinken", "Doorzichtig", "Breken", "Water"] },
    { answer: "Beker", clues: ["Oor", "Koffie", "Warm", "Mok"] },
    { answer: "Vergiet", clues: ["Gaten", "Afgieten", "Pasta", "Water"] },
    { answer: "Rasp", clues: ["Kaas", "Scherp", "Wortel", "Metaal"] },
    { answer: "Schilmesje", clues: ["Aardappel", "Klein", "Schillen", "Fruit"] },
    { answer: "Spatel", clues: ["Omkeren", "Bakken", "Plat", "Pan"] },
    { answer: "Garde", clues: ["Kloppen", "Ei", "Slagroom", "Metaaldraad"] },
    { answer: "Beslagkom", clues: ["Mixen", "Deeg", "Taart", "Rond"] },
    { answer: "Weegschaal", clues: ["Gewicht", "Gram", "Meten", "Keuken"] },
    { answer: "Ovenwant", clues: ["Heet", "Hand", "Bescherming", "Oven"] },

    // --- 🏫 Kantoor & School (Nieuw) ---
    { answer: "Pen", clues: ["Schrijven", "Inkt", "Blauw", "Papier"] },
    { answer: "Gum", clues: ["Wissen", "Potlood", "Fout", "Rubber"] },
    { answer: "Liniaal", clues: ["Recht", "Meten", "Centimeters", "Lijnen"] },
    { answer: "Schrift", clues: ["Schrijven", "Lijntjes", "School", "Papier"] },
    { answer: "Agenda", clues: ["Afspraken", "Data", "Huiswerk", "Boekje"] },
    { answer: "Nietjes", clues: ["Vastmaken", "Metaal", "Papier", "Apparaat"] },
    { answer: "Lijm", clues: ["Plakken", "Vloeibaar/Stift", "Knutselen", "Vast"] },
    { answer: "Dossier", clues: ["Papieren", "Map", "Informatie", "Bewaren"] },
    { answer: "Bureaustoel", clues: ["Zitten", "Wielen", "Draaien", "Werk"] },
    { answer: "Whiteboard", clues: ["Stift", "Wissen", "Muur", "Wit"] },
    { answer: "Markeerstift", clues: ["Geel", "Opvallen", "Tekst", "Neon"] },
    { answer: "Paperclip", clues: ["Metaal", "Buigen", "Vasthouden", "Papier"] },
    { answer: "Envelop", clues: ["Brief", "Post", "Dichtlikken", "Adres"] },
    { answer: "Rekenmachine", clues: ["Cijfers", "Sommen", "Wiskunde", "Knoppen"] },
    { answer: "Puntenslijper", clues: ["Potlood", "Scherp", "Draaien", "Afval"] },

    // --- 🌳 Natuur & Landschap (Nieuw) ---
    { answer: "Bos", clues: ["Bomen", "Wandelen", "Groen", "Dieren"] },
    { answer: "Strand", clues: ["Zand", "Zee", "Zomer", "Schelpen"] },
    { answer: "Berg", clues: ["Hoog", "Klimmen", "Top", "Sneeuw"] },
    { answer: "Rivier", clues: ["Water", "Stromen", "Lang", "Bedding"] },
    { answer: "Meer", clues: ["Water", "Stilstaand", "Eenden", "Zoet"] },
    { answer: "Woestijn", clues: ["Zand", "Droog", "Kameel", "Cactus"] },
    { answer: "Eiland", clues: ["Water", "Omringd", "Land", "Varen"] },
    { answer: "Grot", clues: ["Donker", "Steen", "Vleermuis", "Onder"] },
    { answer: "Dal", clues: ["Laag", "Tussen bergen", "Vallei", "Groen"] },
    { answer: "Waterval", clues: ["Water", "Naar beneden", "Geluid", "Hoog"] },
    { answer: "Oerwoud", clues: ["Tropisch", "Dicht", "Planten", "Jungle"] },
    { answer: "Wei", clues: ["Gras", "Koeien", "Groen", "Boerderij"] },
    { answer: "Heuvel", clues: ["Bult", "Gras", "Omhoog", "Klein"] },
    { answer: "Duin", clues: ["Zand", "Kust", "Gras", "Wind"] },
    { answer: "Moeras", clues: ["Nat", "Modder", "Vies", "Zakken"] },

    // --- 🌤️ Weer & Seizoenen (Nieuw) ---
    { answer: "Winter", clues: ["Koud", "Sneeuw", "December", "Schaatsen"] },
    { answer: "Lente", clues: ["Bloemen", "Lammetjes", "Groen", "Maart"] },
    { answer: "Herfst", clues: ["Bladeren", "Wind", "Regen", "Oktober"] },
    { answer: "Hagel", clues: ["IJs", "Neerslag", "Hard", "Tikken"] },
    { answer: "Mist", clues: ["Wit", "Slecht zicht", "Vocht", "Grijs"] },
    { answer: "Storm", clues: ["Wind", "Waaien", "Schade", "Bomen"] },
    { answer: "Onweer", clues: ["Bliksem", "Donder", "Bui", "Lichtflits"] },
    { answer: "Hittegolf", clues: ["Warm", "Zomer", "Zon", "Zweten"] },
    { answer: "Vorst", clues: ["Vriezen", "Koud", "Glad", "IJs"] },
    { answer: "Regen", clues: ["Nat", "Wolken", "Paraplu", "Plassen"] },

    // --- 🎉 Feestdagen (Nieuw) ---
    { answer: "Kerstmis", clues: ["Boom", "25 december", "Cadeaus", "Lichtjes"] },
    { answer: "Pasen", clues: ["Eieren", "Haas", "Verstoppen", "Lente"] },
    { answer: "Sinterklaas", clues: ["5 december", "Piet", "Cadeaus", "Stoomboot"] },
    { answer: "Halloween", clues: ["Pompoen", "Griezelen", "Snoep", "Oktober"] },
    { answer: "Oudjaar", clues: ["31 december", "Vuurwerk", "Oliebollen", "Aftellen"] },
    { answer: "Valentijn", clues: ["Liefde", "14 februari", "Hartje", "Rozen"] },
    { answer: "Carnaval", clues: ["Verkleden", "Optocht", "Feest", "Alaaf"] },
    { answer: "Verjaardag", clues: ["Taart", "Kaarsjes", "Jaar", "Feest"] },
    { answer: "Moederdag", clues: ["Mama", "Ontbijt", "Zondag", "Mei"] },
    { answer: "Vaderdag", clues: ["Papa", "Cadeau", "Zondag", "Juni"] },

    // --- 🎲 Spelletjes & Hobby's (Nieuw) ---
    { answer: "Monopoly", clues: ["Geld", "Straat", "Hotel", "Bordspel"] },
    { answer: "Domino", clues: ["Stenen", "Ogen", "Aansluiten", "Omvallen"] },
    { answer: "Dammen", clues: ["Schijven", "Zwart/Wit", "Bord", "Slaan"] },
    { answer: "Ganzenbord", clues: ["Gans", "Dobbelsteen", "Put", "Bord"] },
    { answer: "Kaarten", clues: ["Harten", "Schoppen", "Koning", "Aas"] },
    { answer: "Poker", clues: ["Gokken", "Fiches", "Bluf", "Kaarten"] },
    { answer: "Verstoppertje", clues: ["Zoeken", "Tellen", "Kinderspel", "Buut"] },
    { answer: "Tikkertje", clues: ["Rennen", "Aanraken", "Hem", "Spel"] },
    { answer: "Breien", clues: ["Wol", "Naalden", "Trui", "Oma"] },
    { answer: "Vissen", clues: ["Hengel", "Water", "Geduld", "Worm"] },
    { answer: "Lezen", clues: ["Boek", "Letters", "Verhaal", "Bladzijde"] },
    { answer: "Gamen", clues: ["Computer", "Console", "Spelen", "Controller"] },
    { answer: "Schilderen", clues: ["Verf", "Doek", "Kunst", "Kwast"] },
    { answer: "Kruiswoordraadsel", clues: ["Puzzel", "Woorden", "Krant", "Invullen"] },
    { answer: "Sudoku", clues: ["Cijfers", "9x9", "Vierkant", "Logica"] },

    // --- 🌈 Kleuren (Nieuw) ---
    { answer: "Rood", clues: ["Bloed", "Liefde", "Stoplicht", "Warm"] },
    { answer: "Groen", clues: ["Gras", "Natuur", "Stoplicht", "Kikker"] },
    { answer: "Geel", clues: ["Zon", "Banaan", "Citroen", "Licht"] },
    { answer: "Paars", clues: ["Violet", "Druif", "Kerk", "Mengkleur"] },
    { answer: "Oranje", clues: ["Nederland", "Sinaasappel", "Wortel", "Koningsdag"] },
    { answer: "Zwart", clues: ["Donker", "Nacht", "Rouw", "Kleur"] },
    { answer: "Wit", clues: ["Sneeuw", "Licht", "Bruid", "Vrede"] },
    { answer: "Roze", clues: ["Varken", "Meisje", "Zoet", "Flamingo"] },
    { answer: "Bruin", clues: ["Aarde", "Chocolade", "Hout", "Beer"] },
    { answer: "Grijs", clues: ["Muis", "Wolken", "Oud", "Tussenin"] },

    // --- 😊 Emoties & Staten (Nieuw) ---
    { answer: "Blij", clues: ["Lachen", "Gelukkig", "Vrolijk", "Glimlach"] },
    { answer: "Boos", clues: ["Kwaad", "Schreeuwen", "Rood", "Woede"] },
    { answer: "Verdrietig", clues: ["Huilen", "Tranen", "Somber", "Pijn"] },
    { answer: "Bang", clues: ["Angst", "Schrikken", "Trillen", "Gevaar"] },
    { answer: "Moe", clues: ["Slapen", "Gapen", "Bed", "Rust"] },
    { answer: "Honger", clues: ["Eten", "Maag", "Knocren", "Voedsel"] },
    { answer: "Dorst", clues: ["Drinken", "Water", "Droog", "Keel"] },
    { answer: "Ziek", clues: ["Koorts", "Bed", "Dokter", "Niet lekker"] },
    { answer: "Verliefd", clues: ["Hartje", "Vlinders", "Kus", "Roze"] },
    { answer: "Jaloers", clues: ["Groen", "Ander", "Willen", "Afgunst"] },

    // --- 🦒 Extra Dieren (Nieuw) ---
    { answer: "Giraf", clues: ["Lange nek", "Vlekken", "Afrika", "Hoog"] },
    { answer: "Nijlpaard", clues: ["Water", "Groot", "Afrika", "Gevaarlijk"] },
    { answer: "Neushoorn", clues: ["Hoorn", "Grijs", "Savanne", "Zwaar"] },
    { answer: "Hert", clues: ["Bos", "Gewaai", "Bambi", "Schuw"] },
    { answer: "Beer", clues: ["Honing", "Hol", "Winter", "Bruin/IJs"] },
    { answer: "Wolf", clues: ["Hond", "Roedel", "Huilen", "Bos"] },
    { answer: "Eend", clues: ["Kwak", "Water", "Snavel", "Vogel"] },
    { answer: "Zwaan", clues: ["Wit", "Meer", "Lange nek", "Sierlijk"] },
    { answer: "Muis", clues: ["Kaas", "Klein", "Piepen", "Staart"] },
    { answer: "Rat", clues: ["Riool", "Staart", "Knaagdier", "Grijs"] },
    { answer: "Hamster", clues: ["Wiel", "Kooi", "Wangen", "Huisdier"] },
    { answer: "Cavia", clues: ["Piepen", "Kooi", "Huisdier", "Geen staart"] },
    { answer: "Schildpad", clues: ["Schild", "Traag", "Oud", "Reptiel"] },
    { answer: "Slak", clues: ["Huisje", "Slijm", "Traag", "Tuin"] },
    { answer: "Spin", clues: ["Web", "Acht poten", "Eng", "Insect"] },

    // --- 🍔 Extra Eten (Nieuw) ---
    { answer: "Pannenkoek", clues: ["Plat", "Stroop", "Bakken", "Rond"] },
    { answer: "Ei", clues: ["Kip", "Schaal", "Bakken/Koken", "Ovaal"] },
    { answer: "Soep", clues: ["Kom", "Lepel", "Warm", "Vloeibaar"] },
    { answer: "IJs", clues: ["Koud", "Hoorntje", "Zomer", "Smaken"] },
    { answer: "Taart", clues: ["Verjaardag", "Zoet", "Kaarsjes", "Slagroom"] },
    { answer: "Koekje", clues: ["Trommel", "Zoet", "Kruimels", "Thee"] },
    { answer: "Snoep", clues: ["Zoet", "Kinderen", "Suiker", "Zak"] },
    { answer: "Drop", clues: ["Zwart", "Zout/Zoet", "Snoep", "Nederlands"] },
    { answer: "Chips", clues: ["Aardappel", "Zak", "Kraken", "Zout"] },
    { answer: "Nootjes", clues: ["Borrel", "Zout", "Schaaltje", "Pinda"] },
    { answer: "Yoghurt", clues: ["Zuivel", "Wit", "Ontbijt", "Schaaltje"] },
    { answer: "Melk", clues: ["Koe", "Wit", "Drinken", "Calcium"] },
    { answer: "Thee", clues: ["Zakje", "Heet", "Water", "Engels"] },
    { answer: "Sap", clues: ["Fruit", "Drinken", "Glas", "Sinaasappel"] },
    { answer: "Cola", clues: ["Zwart", "Prik", "Suiker", "Merk"] }
];